Refactoring: massive changes to scripts to bring them into line with shell script coding standards. Other improvements to, and new scripts.

diff --git a/scripts/usr/local/bin/fdo-postgresql-backup b/scripts/usr/local/bin/fdo-postgresql-backup
--- a/scripts/usr/local/bin/fdo-postgresql-backup
+++ b/scripts/usr/local/bin/fdo-postgresql-backup
@@ -1,17 +1,136 @@
 #!/bin/sh
 
-if [ $# -ne 1 ]
-then
-  echo ""
-  echo "Usage:   ${0} DB_NAME"
-  echo "Example: ${0} free-dominion.org"
-  echo ""
-  exit 1
-fi
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-DB_NAME=$1
 
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+DB_NAME="${1}"
+BACKUP_DIR="${2}"
+NUM_MANDATORY_ARGS=2
+PG_DUMP_CMD="/usr/local/bin/pg_dump"
 DATE_CMD=/bin/date
 NOW=`${DATE_CMD} +%Y-%m-%d_%H-%M`
 
-/usr/local/bin/pg_dump -w ${DB_NAME} > /backup/pg_dumps/${DB_NAME}.${NOW}.sql
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} backup (dump) postgresql databases."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} database_name backup_directory${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} somedb /backup/pg_dumps${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
+fi
+
+if [ ! -d "${BACKUP_DIR}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Backup directory does not exist!\nAborting."
+	usage
+	exit 3
+fi
+
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Dump the dB to the backup directory.
+${PG_DUMP_CMD} -w ${DB_NAME} > "${BACKUP_DIR}/${DB_NAME}.${NOW}.sql"
+if [ ${?} -ne 0 ]
+then
+	ERROR_COUNT=$(( ${ERROR_COUNT} + 1 ))
+	echo -e "\n${LRED}ERROR:${NRML} Backup (dump) seems to have failed!\nAborting."
+fi
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 4
+fi
+
+################################################################################
diff --git a/scripts/usr/local/bin/findinfiles b/scripts/usr/local/bin/findinfiles
--- a/scripts/usr/local/bin/findinfiles
+++ b/scripts/usr/local/bin/findinfiles
@@ -1,42 +1,133 @@
 #!/bin/sh
+
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
 #
-#  Copyright (c) 2012, Euan A. Thoms
-#  All rights reserved.
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
 #
-#  Redistribution and use in source and binary forms, with or without
-#  modification, are permitted provided that the following conditions are met:
-#
-#  1. Redistributions of source code must retain the above copyright notice, this
-#     list of conditions and the following disclaimer.
-#  2. Redistributions in binary form must reproduce the above copyright notice,
-#     this list of conditions and the following disclaimer in the documentation
-#     and/or other materials provided with the distribution.
-#
-#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
-#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
-#  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-#  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 
-# Find specified "text" within all files under specified folder
-# Usage: findinfiles "text to search for" /Folder/to/search
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
-SEARCH_TEXT=$1
-SEARCH_FOLDER=$2
+SCRIPT_NAME=`basename ${0}`
+SEARCH_TEXT="${1}"
+SEARCH_PATH="${2}"
+NUM_MANDATORY_ARGS=2
 
-if [ $# -ne 2 ]
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} find all occurences of search text within a directory or file."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} search_text search_directory${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} needle /usr/local/share/haystack${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} \"needle in a\" /home/haystack${NRML}"
+	echo -e ""
+	echo -e "${ORNG}Note:    ${NRML} It's recommended to use single quotes around the search text."
+    echo -e "          This command is designed to ignore regex/patterns."
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
 then
-  echo ""
-  echo "Usage:   ${0} SEARCH_TEXT SEARCH_FOLDER"
-  echo "Example: ${0} needle /usr/share/haystack"
-  echo ""
-  exit 1
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
 
-find "${SEARCH_FOLDER}" -type f -exec grep "${SEARCH_TEXT}" {} \; -print
+if [ ! -e "${SEARCH_PATH}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Search path does not exist!\nAborting."
+	usage
+	exit 3
+fi
+
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Find and display all occurences of search text recursively within all files under search path.
+find "${SEARCH_PATH}" -type f -exec grep --color=always "${SEARCH_TEXT}" {} \; -print
+
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 4
+fi
+
+################################################################################
diff --git a/scripts/usr/local/bin/replaceinfiles b/scripts/usr/local/bin/replaceinfiles
--- a/scripts/usr/local/bin/replaceinfiles
+++ b/scripts/usr/local/bin/replaceinfiles
@@ -1,85 +1,208 @@
 #!/bin/sh
 
-#  Copyright (c) 2012, Euan A. Thoms
-#  All rights reserved.
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
 #
-#  Redistribution and use in source and binary forms, with or without
-#  modification, are permitted provided that the following conditions are met:
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
 #
-#  1. Redistributions of source code must retain the above copyright notice, this
-#     list of conditions and the following disclaimer.
-#  2. Redistributions in binary form must reproduce the above copyright notice,
-#     this list of conditions and the following disclaimer in the documentation
-#     and/or other materials provided with the distribution.
-#
-#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
-#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-#  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
-#  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-#  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
-#  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
-#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Find and replace specified "text" within all files under specified folder
-# Usage (1): findinfiles "text to search for" "text to replace with" /Folder/to/search
-# Usage (2): findinfiles "text to search for" "text to replace with" /Folder/to/search <case-sensitive>?(true|false)
 
-SEARCH_TEXT=$1
-REPLACE_TEXT=$2
-SEARCH_FOLDER=$3
-SLASH_CHR="/"
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
-SEARCH_TEXT=`echo $SEARCH_TEXT | sed "s/@/\\\\\@/"`
-REPLACE_TEXT=`echo $REPLACE_TEXT | sed "s/@/\\\\\@/"`
+SCRIPT_NAME=`basename ${0}`
+SEARCH_TEXT="${1}"
+REPLACE_TEXT="${2}"
+SEARCH_PATH="${3}"
+NUM_MANDATORY_ARGS=3
+CASE_INSENSITIVE="no"
+TEXT_HAS_PIPE_CHR="no"
 
-if [ $# -eq 4 ]
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+PIPE_CHR="|"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} replace all occurences of search text within a directory or file."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} search_text replace_text search_directory [--case-insenstive]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} 'needle' 'Thimble' /usr/local/share/haystack --case-insensitive${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} 'needle in a' 'thimble under a' /home/haystack${NRML}"
+	echo -e ""
+	echo -e "${ORNG}Note:    ${NRML} It's recommended to use single quotes around the search and"
+    echo -e "          replace text. This command is designed to ignore regex/patterns."
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--case-insensitive)
+				CASE_INSENSITIVE="yes"
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
 then
-  if [ $4 = "true" ]
-  then
-    test "${1#*$SLASH_CHR}" != "$1"
-    SEARCH_HAS_SLASH=$?
-    test "${2#*$SLASH_CHR}" != "$2"
-    REPLACE_HAS_SLASH=$?
-    if [ $SEARCH_HAS_SLASH -eq 0 ] || [ $REPLACE_HAS_SLASH -eq 0 ]
-    then
-      find "${SEARCH_FOLDER}" -type f -exec perl -pi -e "s:$SEARCH_TEXT:$REPLACE_TEXT:g" {} \;
-    else
-      find "${SEARCH_FOLDER}" -type f -exec perl -pi -e "s/$SEARCH_TEXT/$REPLACE_TEXT/g" {} \;
-    fi
-  elif [ $4 = "false" ]
-  then
-    test "${1#*$SLASH_CHR}" != "$1"
-    SEARCH_HAS_SLASH=$?
-    test "${2#*$SLASH_CHR}" != "$2"
-    REPLACE_HAS_SLASH=$?
-    if [ $SEARCH_HAS_SLASH -eq 0 ] || [ $REPLACE_HAS_SLASH -eq 0 ]
-    then
-      find "${SEARCH_FOLDER}" -type f -exec perl -pi -e "s:$SEARCH_TEXT:$REPLACE_TEXT:gi" {} \;
-    else
-      find "${SEARCH_FOLDER}" -type f -exec perl -pi -e "s/$SEARCH_TEXT/$REPLACE_TEXT/gi" {} \;
-    fi
-  else
-    echo "usage (1): ${0} <SEARCH_TEXT> <REPLACE_TEXT> <SEARCH_FOLDER>"
-    echo "usage (2): ${0} <SEARCH_TEXT> <REPLACE_TEXT> <SEARCH_FOLDER> <CASE_SENSITIVE>?(true|false)"
-    exit 1
-  fi
-elif [ $# -eq 3 ]
-then
-  test "${1#*$SLASH_CHR}" != "$1"
-  SEARCH_HAS_SLASH=$?
-  test "${2#*$SLASH_CHR}" != "$2"
-  REPLACE_HAS_SLASH=$?
-  if [ $SEARCH_HAS_SLASH -eq 0 ] || [ $REPLACE_HAS_SLASH -eq 0 ]
-  then
-    find "${SEARCH_FOLDER}" -type f -exec perl -pi -e "s:$SEARCH_TEXT:$REPLACE_TEXT:g" {} \;
-  else
-    find "${SEARCH_FOLDER}" -type f -exec perl -pi -e "s/$SEARCH_TEXT/$REPLACE_TEXT/g" {} \;
-  fi
-else
-  echo "usage (1): ${0} <SEARCH_TEXT> <REPLACE_TEXT> <SEARCH_FOLDER>"
-  echo "usage (2): ${0} <SEARCH_TEXT> <REPLACE_TEXT> <SEARCH_FOLDER> <CASE_SENSITIVE>?(true|false)"
-  exit 1
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
+
+if [ ! -e "${SEARCH_PATH}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Search path does not exist!\nAborting."
+	usage
+	exit 3
+fi
+
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Determine if the search or replace texts have any pipe characters in them.
+test "${SEARCH_TEXT#*$PIPE_CHR}" != "${SEARCH_TEXT}"
+if [ ${?} -eq 0 ]
+then
+	TEXT_HAS_PIPE_CHR="yes"
+fi
+test "${REPLACE_TEXT#*$PIPE_CHR}" != "${REPLACE_TEXT}"
+if [ ${?} -eq 0 ]
+then
+	TEXT_HAS_PIPE_CHR="yes"
+fi
+
+if [ "${DEBUG}" = "yes" ]
+then
+	echo ""
+	echo "BEFORE adding escape chars:"
+	echo "SEARCH_TEXT=${SEARCH_TEXT}"
+	echo "REPLACE_TEXT=${REPLACE_TEXT}"
+fi
+
+# Escape BRE special characters: \$.*/[]^&
+# \
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|[\]|\\\\\\\|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|[\]|\\\\\\\|g'`
+# $
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|[$]|\\\\\\$|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|[$]|\\\\\\$|g'`
+# .
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|[.]|\\\\\\.|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|[.]|\\\\\\.|g'`
+# *
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|[*]|\\\\\\*|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|[*]|\\\\\\*|g'`
+# /
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|[/]|\\\\\\/|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|[/]|\\\\\\/|g'`
+# [
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|[[]|\\\\\\[|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|[[]|\\\\\\[|g'`
+# ]
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|[]]|\\\\\\]|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|[]]|\\\\\\]|g'`
+# ^
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|\^|\\\\\\^|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|\^|\\\\\\^|g'`
+# &
+SEARCH_TEXT=`echo "${SEARCH_TEXT}" | sed -e 's|[&]|\\\\\\&|g'`
+REPLACE_TEXT=`echo "${REPLACE_TEXT}" | sed 's|[&]|\\\\\\&|g'`
+
+if [ "${DEBUG}" = "yes" ]
+then
+	echo ""
+	echo "AFTER adding escape chars:"
+	echo "SEARCH_TEXT=${SEARCH_TEXT}"
+	echo "REPLACE_TEXT=${REPLACE_TEXT}"
+fi
+
+if [ "${CASE_INSENSITIVE}" = "yes" ]
+then
+	PATTERN_FLAGS="gi"
+else
+	PATTERN_FLAGS="g"
+fi
+
+if [ "${TEXT_HAS_PIPE_CHR}" = "yes" ]
+then
+	find "${SEARCH_PATH}" -type f -exec sed -i "" "s/${SEARCH_TEXT}/${REPLACE_TEXT}/${PATTERN_FLAGS}" {} \;
+else
+	find "${SEARCH_PATH}" -type f -exec sed -i "" "s|${SEARCH_TEXT}|${REPLACE_TEXT}|${PATTERN_FLAGS}" {} \;
+fi
+
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 4
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-backupz b/scripts/usr/local/sbin/fdo-backupz
--- a/scripts/usr/local/sbin/fdo-backupz
+++ b/scripts/usr/local/sbin/fdo-backupz
@@ -32,8 +32,9 @@ DAV_SERVER_GROUPID=`cat /usr/local/etc/fdo/webdav_groupid.conf`
 DATE_CMD=/bin/date
 DATE_VERSION="freebsd" #choices of "freebsd" and "gnu"
 NOW=`${DATE_CMD} +%Y-%m-%d_%H-%M`
-POOL=$1
-BACKUP_POOL=$2
+POOL=${1}
+BACKUP_POOL=${2}
+NUM_MANDATORY_ARGS=2
 DAY_IN_SECS=86400
 CLONE_WINDOW_DAYS=5
 NOW_IN_SECS=`${DATE_CMD} +%s`
@@ -72,26 +73,50 @@ usage ()
 	echo -e ""
 }
 
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
 ##### SANITY TESTS #############################################################
 
-if [ $# != 2 ]
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
 then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
 	usage
-	exit 1
+	exit 2
 fi
 
 BACKUP_POOL_ATTRIBUTES=`zpool list -H | egrep "^${BACKUP_POOL}	" 2> /dev/null`
 if [ $? -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' does not appear to be imported."
-	exit 2
+	exit 3
 fi
 
 BACKUP_POOL_HEALTH=`echo ${BACKUP_POOL_ATTRIBUTES} | awk '{print $9}'`
 if [ "${BACKUP_POOL_HEALTH}" != "ONLINE" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' appears to be unhealthy."
-	exit 3
+	exit 4
 fi
 
 BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
@@ -99,32 +124,19 @@ BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
 if [ -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The last backup from '${POOL}' to '${BACKUP_POOL}' failed!\nAborting.\n"
-	exit 4
+	exit 5
 fi
 
 if [ -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} There apppers to be a backup running for '${POOL}'!\nAborting.\n"
-	exit 5
+	exit 6
 fi
 
 ################################################################################
 
 
-# Create log dataset if log directory doesn't already exist.
-if [ ! -d ${BACKUP_POOL_ROOT_PATH}/log ]
-then
-	zfs create -o mountpoint=/${BACKUP_POOL_ROOT_PATH}/log -o compression=on ${BACKUP_POOL}/log
-fi
-
-if [ -f ${BACKUP_POOL_ROOT_PATH}/last-successful-backupz-${POOL}@${BACKUP_POOL}.inf ]
-then
-	PREVIOUS=`cat ${BACKUP_POOL_ROOT_PATH}/last-successful-backupz-${POOL}@${BACKUP_POOL}.inf`
-else
-	PREVIOUS="last-successful-backupz-missing"
-fi
-
-echo "Previous backup: ${PREVIOUS}"
+##### FUNCTIONS ################################################################
 
 WARNING_CODE=0
 WARNING_SNAPSHOT="NULL"
@@ -143,6 +155,27 @@ error_occured () {
 	rm ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf
 	exit 5
 }
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+# Create log dataset if log directory doesn't already exist.
+if [ ! -d ${BACKUP_POOL_ROOT_PATH}/log ]
+then
+	zfs create -o mountpoint=/${BACKUP_POOL_ROOT_PATH}/log -o compression=on ${BACKUP_POOL}/log
+fi
+
+if [ -f ${BACKUP_POOL_ROOT_PATH}/last-successful-backupz-${POOL}@${BACKUP_POOL}.inf ]
+then
+	PREVIOUS=`cat ${BACKUP_POOL_ROOT_PATH}/last-successful-backupz-${POOL}@${BACKUP_POOL}.inf`
+else
+	PREVIOUS="last-successful-backupz-missing"
+fi
+
+echo "Previous backup: ${PREVIOUS}"
+
 
 echo ${NOW} > ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf
 
@@ -319,3 +352,5 @@ echo "Backupz finished." >> ${BACKUP_POOL_ROOT_PATH}/log/backupz-${POOL}@${BACKU
 
 # Remove backup 'is-running' marker file.
 rm ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-backupz-destroy-snapshot b/scripts/usr/local/sbin/fdo-backupz-destroy-snapshot
--- a/scripts/usr/local/sbin/fdo-backupz-destroy-snapshot
+++ b/scripts/usr/local/sbin/fdo-backupz-destroy-snapshot
@@ -1,42 +1,143 @@
 #!/bin/sh
 
-if [ $# -lt 2 ]
-then
-  echo "Usage:   $0 pool_to_destroy_from snapshot_pattern [OPTION]..."
-  echo "Example: $0 backup 1978-08-01_12-00"
-  echo ""
-  echo ""
-  echo "Options:"
-  echo ""
-  echo "-s, --simulate          simulation mode, will output the command but execute them."
-  echo ""
-  exit 1
-fi
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-POOL=$1
-SNAPSHOT_PATTERN=$2
 
-for i in ${@}
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+POOL=${1}
+SNAPSHOT_PATTERN=${2}
+NUM_MANDATORY_ARGS=2
+SIMULATION_MODE="no"
+
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} destroy all snapshots from a given pool that match a given"
+	echo -e "             pattern in their name."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} pool_to_destroy_from snapshot_pattern [--simulate]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} backup Accounts@2013${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} backup @2013-10-03 --simulate${NRML}"
+	echo -e ""
+	echo -e "${YELL}Options:${NRML}"
+	echo -e ""
+	echo -e "${YELL}--simulate  Simulation mode. Will output the commands but not execute them.${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
 do
-  case ${i} in
-  -s) SIMULATION="true"
-      ;;
-  --simulate) SIMULATION="true"
-      ;;
-  esac
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--simulate)
+				SIMULATION_MODE="yes"
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
 done
 
-TO_DESTROY=`zfs list -t snapshot -r ${POOL} | grep "@${SNAPSHOT_PATTERN}" | cut -d " " -f 1`
-if [ "${SIMULATION}" = "true" ]
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
 then
-  echo ""
-  echo "!!! SIMULATION Mode !!!"
-  echo ""
-  echo ""
-  for i in ${TO_DESTROY} ; do echo "zfs destroy -v ${i}" ; done
-else
-  echo ""
-  echo "Destroying snapshot starts!"
-  echo ""
-  for i in ${TO_DESTROY} ; do zfs destroy -v ${i} ; done
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Find and destroy all matching snapshots.
+TO_DESTROY=`zfs list -H -t snapshot -r ${POOL}  | awk '{print $1}' | grep "${SNAPSHOT_PATTERN}"`
+
+if [ "${SIMULATION_MODE}" = "yes" ]
+then
+	echo -e "\n${YELL}   --- SIMULATION MODE ---   ${NRML}\n"
+	for SNAPSHOT in ${TO_DESTROY}
+	do
+		echo -e "zfs destroy -v ${SNAPSHOT}"
+	done
+else
+	echo -e "\n${YELL}Destroying snapshots...${NRML}\n"
+	for SNAPSHOT in ${TO_DESTROY}
+	do
+		zfs destroy -v ${SNAPSHOT}
+		if [ ${?} -ne 0 ]
+		then
+			ERROR_COUNT=$(( ${ERROR_COUNT} + 1 ))
+		fi
+	done
+fi
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 3
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-backupz-thin-snapshots b/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
--- a/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
+++ b/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
@@ -1,135 +1,265 @@
 #!/usr/local/bin/bash
 
-# VERSION 2.1
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-if [ $# -ne 3 ] && [ $# -ne 4 ]
-then
-  echo ""
-  echo "Usage   (1): $0 pool offset interval"
-  echo "Example (1): $0 backup 28 7"
-  echo ""
-  echo "Usage   (2): $0 pool offset interval \"snapshot_pattern\""
-  echo "Example (2): $0 backup 28 28 \"/users\""
-  echo ""
-  echo "Note       : offset and interval are number of days."
-  echo ""
-  exit 1
-fi
 
-POOL=$1
-OFFSET_DAYS=$2
-INTERVAL_DAYS=$3
-INCLUSSION_PATTERN=$4
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
+SCRIPT_NAME=`basename ${0}`
+POOL=${1}
+BACKUP_POOL=${2}
+OFFSET_DAYS=${3}
+INTERVAL_DAYS=${4}
+NUM_MANDATORY_ARGS=4
+FILESYSTEM_FILTER=""
+SIMULATION_MODE="no"
 NOW=`date +%s`
 NOW_DATE_TIME=`date +%Y-%m-%d_%H-%M`
 DAY_IN_SECS=86400
 OFFSET=$((${OFFSET_DAYS} * ${DAY_IN_SECS}))
 INTERVAL=$((${INTERVAL_DAYS} * ${DAY_IN_SECS}))
 
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
 
-######## SANITY TESTS ###############################################################
+CARRIAGE_RETURN="
+"
 
-zpool list | tail -n +2 | awk '{print $1}' | grep backup > /dev/null 2>&1
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} pool backup_pool offset interval [--simulate]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup 28 7${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup 28 7 --simulate${NRML}"
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} pool backup_pool offset interval [--filter=\"filesystem_filter\"] [--simulate]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup 28 7 --filter=\"/users\"${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup 28 7 --filter=\"/users\" --simulate${NRML}"
+	echo -e ""
+	echo -e "${GREY}Note   :  offset and interval are in number of days.${NRML}"
+	echo -e ""
+	echo -e "${YELL}Options:${NRML}"
+	echo -e ""
+	echo -e "${YELL}--filter    Only thins snapshots with the specified pattern in it's${NRML}"
+	echo -e "${YELL}            filesystem name.${NRML}"
+	echo -e ""
+	echo -e "${YELL}--simulate  Simulation mode. Will output the commands but not execute them.${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--fiter)
+				FILESYSTEM_FILTER="${OPTIONAL_ARG_VALUE}"
+				;;
+			--simulate)
+				SIMULATION_MODE="yes"
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
+fi
+
+BACKUP_POOL_ATTRIBUTES=`zpool list -H | egrep "^${BACKUP_POOL}	" 2> /dev/null`
 if [ $? -ne 0 ]
 then
-   exit 2
+	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' does not appear to be imported."
+	exit 3
 fi
 
-BACKUP_ERROR_MARKERS=`ls /backup/last-backup-error-*.inf 2> /dev/null | wc -l`
-
-if [ ${BACKUP_ERROR_MARKERS} -ne 0 ]
+BACKUP_POOL_HEALTH=`echo ${BACKUP_POOL_ATTRIBUTES} | awk '{print $9}'`
+if [ "${BACKUP_POOL_HEALTH}" != "ONLINE" ]
 then
-  exit 3
+	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' appears to be unhealthy."
+	exit 4
 fi
 
-BACKUP_RUNNING_MARKERS=`ls /backup/backup-*-running.inf 2> /dev/null | wc -l`
+BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
 
-if [ ${BACKUP_RUNNING_MARKERS} -ne 0 ]
+if [ -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf ]
 then
-  exit 4
+	echo -e "\n${LRED}ERROR:${NRML} The last backup from '${POOL}' to '${BACKUP_POOL}' failed!\nAborting.\n"
+	exit 5
 fi
 
-######################################################################################
+if [ -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There apppers to be a backup running for '${POOL}'!\nAborting.\n"
+	exit 6
+fi
 
+################################################################################
+
+
+##### FUNCTIONS ################################################################
 
 thin_snapshots_by_filesystem()
 {
 
-FILESYSTEM=${1}
+	FILESYSTEM=${1}
 
-SNAPSHOTS=`zfs list -r -d 1 -H -t snapshot -o name ${FILESYSTEM}`
+	SNAPSHOTS=`zfs list -r -d 1 -H -t snapshot -o name ${FILESYSTEM}`
 
-EARLIEST_TIMESTAMP=${NOW}
-i=0
-for snapshot in ${SNAPSHOTS}
-do
-  SNAPSHOT_NAMES[$i]=${snapshot}
-  SNAPSHOT_TIMESTAMPS[$i]=`echo ${snapshot} | sed 's|^.*@||' | xargs date -j -f "%Y-%m-%d_%H-%M" -- +%s`
-  SNAPSHOT_ACTION[$i]="keep"
+	EARLIEST_TIMESTAMP=${NOW}
+	i=0
+	for SNAPSHOT in ${SNAPSHOTS}
+	do
+		SNAPSHOT_NAMES[$i]=${SNAPSHOT}
+		SNAPSHOT_TIMESTAMPS[$i]=`echo ${SNAPSHOT} | sed 's|^.*@||' | xargs date -j -f "%Y-%m-%d_%H-%M" -- +%s`
+		SNAPSHOT_ACTION[$i]="keep"
 
-  if [ ${SNAPSHOT_TIMESTAMPS[$i]} -lt ${EARLIEST_TIMESTAMP} ]
-  then
-    EARLIEST_TIMESTAMP=${SNAPSHOT_TIMESTAMPS[$i]}
-  fi
-  i=$(($i+1))
-done
+		if [ ${SNAPSHOT_TIMESTAMPS[$i]} -lt ${EARLIEST_TIMESTAMP} ]
+		then
+			EARLIEST_TIMESTAMP=${SNAPSHOT_TIMESTAMPS[$i]}
+		fi
+		i=$(( $i + 1 ))
+	done
 
-NUM_SNAPSHOTS=${#SNAPSHOT_NAMES[@]}
+	NUM_SNAPSHOTS=${#SNAPSHOT_NAMES[@]}
 
-FIRST_PROJECTION=$((${NOW} - ${OFFSET}))
+	FIRST_PROJECTION=$((${NOW} - ${OFFSET}))
 
-PROJECTIONS[0]=${FIRST_PROJECTION}
+	PROJECTIONS[0]=${FIRST_PROJECTION}
 
-NEXT_PROJECTION=${FIRST_PROJECTION}
+	NEXT_PROJECTION=${FIRST_PROJECTION}
 
-j=1
-while [ ${NEXT_PROJECTION} -gt ${EARLIEST_TIMESTAMP} ]
-do
-  NEXT_PROJECTION=$((${NEXT_PROJECTION} - ${INTERVAL}))
-  PROJECTIONS[${j}]=${NEXT_PROJECTION}
-  j=$(($j+1))
-done
+	j=1
+	while [ ${NEXT_PROJECTION} -gt ${EARLIEST_TIMESTAMP} ]
+	do
+		NEXT_PROJECTION=$((${NEXT_PROJECTION} - ${INTERVAL}))
+		PROJECTIONS[${j}]=${NEXT_PROJECTION}
+		j=$(( $j + 1 ))
+	done
 
-if [ ! -d /backup/log ]
-then
-  mkdir /backup/log
-fi
+	j=0
+	i=$(( $i - 1 ))
+	while [ ${i} -ge 0 ]
+	do
+		if [ ${SNAPSHOT_TIMESTAMPS[${i}]} -lt ${FIRST_PROJECTION} ]
+		then
 
-j=0
-i=$(($i-1))
-while [ ${i} -ge 0 ]
-do
-  if [ ${SNAPSHOT_TIMESTAMPS[${i}]} -lt ${FIRST_PROJECTION} ]
-  then
-    if [ ${SNAPSHOT_TIMESTAMPS[${i}]} -gt ${PROJECTIONS[${j}]} ] && [ ${i} -gt 0 ]
-    then
-      # we've need reached the next projection, destroy this snapshot
-      SNAPSHOT_ACTION[$i]="destroy"
-    else
-      # this the first snaphot older than current projection,  keep it and iterate to next projection
-      j=$(($j+1))
-    fi
-  fi
-  echo "${SNAPSHOT_NAMES[${i}]} -> ${SNAPSHOT_ACTION[${i}]}" >> /backup/log/test-thin-snapshots.${POOL}.${NOW_DATE_TIME}.log
-  if [ "${SNAPSHOT_ACTION[$i]}" = "destroy" ]
-  then
-    echo "zfs destroy ${SNAPSHOT_NAMES[$i]}"
-  fi
-  i=$(($i-1))
-done
+			echo -e "\nDEBUG: SNAPSHOT_NAMES[${i}] = ${SNAPSHOT_NAMES[${i}]}  LAST_SUCCESSFUL_BACKUP_SNAPSHOT = ${LAST_SUCCESSFUL_BACKUP_SNAPSHOT}\n"
+
+			if [ ${SNAPSHOT_TIMESTAMPS[${i}]} -gt ${PROJECTIONS[${j}]} ] && [ ${i} -gt 0 ] && [ "${SNAPSHOT_NAMES[${i}]}" != "${LAST_SUCCESSFUL_BACKUP_SNAPSHOT}" ]
+			then
+				# We've reached the next projection, destroy this snapshot.
+				SNAPSHOT_ACTION[$i]="destroy"
+			else
+				# This is the first snaphot older than the current projection, keep it and iterate to next projection.
+				j=$(( $j + 1 ))
+			fi
+		fi
+		echo "${SNAPSHOT_NAMES[${i}]} -> ${SNAPSHOT_ACTION[${i}]}" >> ${BACKUP_POOL_ROOT_PATH}/log/thin-snapshots.${POOL}@${BACKUP_POOL}.${NOW_DATE_TIME}.log
+		if [ "${SNAPSHOT_ACTION[$i]}" = "destroy" ]
+		then
+			if [ ${SIMULATION_MODE} = "yes" ]
+			then
+				echo -e "${LBLU}zfs destroy ${SNAPSHOT_NAMES[$i]}${NRML}"
+			else
+				zfs destroy ${SNAPSHOT_NAMES[$i]}
+			fi
+		fi
+		i=$(( $i - 1 ))
+	done
 
 }
 
-if [ "${INCLUSSION_PATTERN}" != "" ]
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+# Create log filesystem if log directory doesn't already exist.
+if [ ! -d ${BACKUP_POOL_ROOT_PATH}/log ]
 then
-  for filesystem in `zfs list -H -t filesystem -o name -r ${POOL} | egrep "${INCLUSSION_PATTERN}"`
-  do
-    thin_snapshots_by_filesystem ${filesystem}
-  done
-else
-  for filesystem in `zfs list -H -t filesystem -o name -r ${POOL}`
-  do
-    thin_snapshots_by_filesystem ${filesystem}
-  done
+	zfs create -o mountpoint=/${BACKUP_POOL_ROOT_PATH}/log -o compression=on ${BACKUP_POOL}/log
 fi
+
+# Get the last successful backup snaphot name
+LAST_SUCCESSFUL_BACKUP_SNAPSHOT=`cat ${BACKUP_POOL_ROOT_PATH}/last-successful-backupz-${POOL}@${BACKUP_POOL}.inf`
+
+if [ "${SIMULATION_MODE}" = "yes" ]
+then
+	echo -e "\n${YELL}   --- SIMULATION MODE ---   ${NRML}\n"
+fi
+
+
+if [ "${FILESYSTEM_FILTER}" != "" ]
+then
+	for FILESYSTEM in `zfs list -H -t filesystem -o name -r ${BACKUP_POOL}/${POOL} | egrep "${FILESYSTEM_FILTER}"`
+	do
+		thin_snapshots_by_filesystem ${FILESYSTEM}
+	done
+else
+	for FILESYSTEM in `zfs list -H -t filesystem -o name -r ${BACKUP_POOL}/${POOL}`
+	do
+		thin_snapshots_by_filesystem ${FILESYSTEM}
+	done
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-dhcpd-edit b/scripts/usr/local/sbin/fdo-dhcpd-edit
--- a/scripts/usr/local/sbin/fdo-dhcpd-edit
+++ b/scripts/usr/local/sbin/fdo-dhcpd-edit
@@ -27,10 +27,8 @@
 ##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
 SCRIPT_NAME=`basename ${0}`
-HOST_NAME="${1}"
-HOST_IP="${2}"
-NUM_MANDATORY_ARGS=2
-DNS_CACHE_SERVER_FOUND="no"
+NUM_MANDATORY_ARGS=0
+DHCPD_CONFIG_FILE="/usr/local/etc/dhcpd.conf"
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -59,11 +57,10 @@ usage ()
 	echo -e ""
 	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
 	echo -e ""
-	echo -e "${YELL}Description:${NRML} sample line 1"
-	echo -e "             sample line 2."
+	echo -e "${YELL}Description:${NRML} Quick way to edit and reload the dhcpd config file."
 	echo -e ""
-	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} hostname ip_address${NRML}"
-	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} site1.example.net 192.168.10.20${NRML}"
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} [--help]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME}${NRML}"
 	echo -e ""
 }
 
@@ -78,6 +75,9 @@ do
 		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
 		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
 		case ${OPTIONAL_ARG_NAME} in
+			--help)
+				usage
+				;;
 			*)
 				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
 				usage
@@ -100,10 +100,33 @@ then
 	exit 2
 fi
 
+if [ ! -f "${DHCPD_CONFIG_FILE}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The dhcpd config file '${DHCPD_CONFIG_FILE}'\ndoes not exist!\nAborting."
+	usage
+	exit 3
+fi
+
 
 ##### FUNCTIONS ################################################################
 
+question_yes_no ()
+{
 
+	LOOP=1
+
+	while [ ${LOOP} = 1 ]
+		do
+		echo -e "${LCYN}${1} (yes/no): ${NRML}\c"
+		read ANSWER
+		if [ "${ANSWER}" = "yes" ] || [ "${ANSWER}" = "no" ]
+		then
+			LOOP=0
+		fi
+		echo ""
+	done
+
+}
 
 ################################################################################
 
@@ -112,69 +135,18 @@ fi
 
 ERROR_COUNT=0
 
-# Iterate through all jails...
-for JAIL_NAME in `ls -1 /jls | cut -d/ -f1 | egrep -v "template"`
-do
-	# ...and if a bind server exists...
-	if [ -f "/jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf" ]
-	then
-		# ...determine if it's a caching server
-		cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^( )*forwarders {" > /dev/null 2>&1
-		if [ ${?} -eq 0 ] 
-		then
+# Open the dhcpd server config file in users preferred editor.
+${EDITOR} ${DHCPD_CONFIG_FILE}
 
-			DNS_CACHE_SERVER_FOUND=yes
-
-			# Now that we've found a caching server, let's see if the record already exists:
-			cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^zone \"${HOST_NAME}\"" > /dev/null 2>&1
-			if [ ${?} -eq 0 ]
-			then
-				echo -e "\n${ORNG}WARNING:${NRML} The record for hostname ${HOST_NAME} already exists!\n"
-				exit 2
-			fi
-
-			# Since it doesn't already exist, let's add a zone for our new hostname record:
-
-			# - Add zone entry in named.conf
-			echo "zone \"${HOST_NAME}\" { type master; file \"/usr/local/etc/namedb/master/${HOST_NAME}.db\"; };" >> /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf
-
-			# - Create the master zone file
-			DATE=`date "+%Y%m%d"`
-			echo "" > /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db
-			echo "\$TTL 3h" >> /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db
-			echo "@ SOA @ nobody.localhost. ${DATE}01 1d 12h 1w 3h ;" >> /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db
-			echo "                        ; Serial, Refresh, Retry, Expire, Neg. cache TTL" >> /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db
-			echo "" >> /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db
-			echo "        IN      NS      ${HOST_NAME}." >> /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db
-			echo "" >> /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db
-			echo "${HOST_NAME}.        A       ${HOST_IP}" >> /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db
-
-			# - Reload bind server
-			JAIL_ID_FILE=`ls -1 /var/run/jail_${JAIL_NAME}.id | head -1`
-			JAIL_ID=`cat ${JAIL_ID_FILE}`
-			echo -e "\n${YELL}Reloading the named service...${NRML}\n"
-			jexec ${JAIL_ID} service named reload > /dev/null 2>&1
-			if [ ${?} -ne 0 ]
-			then
-				echo -e "${LRED}WARNING:${NRML} Failed to reload named service in jail '${JAIL_NAME}'!\n"
-				exit 3
-			else
-				echo -e "${YELL}INFO:${NRML} Successfully updated bind9 DNS server in jail '${JAIL_NAME}'!\n"
-			fi
-		fi
-	fi
-done
-
-if [ "${DNS_CACHE_SERVER_FOUND}" = "no" ]
+question_yes_no "\nWould you like to restart the service to pick up any changes now?"
+if [ "${ANSWER}" = "yes" ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} No caching dns server found!\n"
-	exit 1
+	service isc-dhcpd restart
 fi
-
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 3
+	exit 4
 fi
 
 ################################################################################
