scripts: Big tidy up. All scripts host/jail execution support and tests added or made consistent.

diff --git a/scripts/usr/local/bin/fdo-script-template b/scripts/usr/local/bin/fdo-script-template
--- a/scripts/usr/local/bin/fdo-script-template
+++ b/scripts/usr/local/bin/fdo-script-template
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# Copyright (c) 20?? Developer Name <username@domain.org>.
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -98,6 +98,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -107,12 +121,13 @@ then
 	exit 2
 fi
 
-
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
+#test_if_host
+#
+#if [ "${IS_HOST}" = "no" ]
+#then
+#	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+#	exit 3
+#fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -123,7 +138,7 @@ ERROR_COUNT=0
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 3
+	exit 99
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-backupz-daily-report b/scripts/usr/local/sbin/fdo-backupz-daily-report
--- a/scripts/usr/local/sbin/fdo-backupz-daily-report
+++ b/scripts/usr/local/sbin/fdo-backupz-daily-report
@@ -1,30 +1,132 @@
 #!/bin/sh
 
-POOL=${1}
+# Copyright (c) 2016 Carlito Balotro <carl.balotro@gmail.com>.
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+POOL="${1}"
 SUBJECT='URGENT BACKUP SERVER ERROR'
 TO="TO_EMAIL_ADDRESSES"
 BCC="BCC_EMAIL_ADDRESSES"
 CC="CC_EMAIL_ADDRESSES"
-MESSAGE="/tmp/server-reports.txt"
+MESSAGE="/tmp/backupz-daily-reports.txt"
 HOST=$(hostname)
+NUM_MANDATORY_ARGS=1
+
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\n       Aborting.\n"
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
+
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
+
+##### MAIN EXECUTION THREAD ####################################################
 
 :> ${MESSAGE}
 
-if [ -f /backup/last-backup-error-${POOL}.inf ]
- then
-   echo "The backup didn't run successfully, please check the logs" >> ${MESSAGE} 
-   echo "===========================================================================" >> ${MESSAGE}
-   cat /backup/last-backup-error-${POOL}.inf >> ${MESSAGE}
-   mail -s "${SUBJECT} from $HOST" ${TO} < ${MESSAGE}
+if [ -f "/backup/last-backup-error-${POOL}.inf" ]
+then
+	echo "The backup didn't finish successfully, please check the logs" >> ${MESSAGE} 
+	echo "===========================================================================" >> ${MESSAGE}
+	cat /backup/last-backup-error-${POOL}.inf >> ${MESSAGE}
+	mail -s "${SUBJECT} from $HOST" ${TO} < ${MESSAGE}
 fi
 
-if  [ -f /backup/backup-${POOL}-running.inf ]
- then
-   echo "Backup is still running, please check the logs" >> ${MESSAGE} 
-   echo "===========================================================================" >> ${MESSAGE}
-   cat /backup/backup-${POOL}-running.inf >> ${MESSAGE}
-   mail -s "${SUBJECT} from ${HOST}" -b "${BCC}" -c "${CC}" ${TO} < ${MESSAGE}
+if  [ -f "/backup/backup-${POOL}-running.inf" ]
+then
+	echo "Backup is still running, please check the logs" >> ${MESSAGE} 
+	echo "===========================================================================" >> ${MESSAGE}
+	cat /backup/backup-${POOL}-running.inf >> ${MESSAGE}
+	mail -s "${SUBJECT} from ${HOST}" -b "${BCC}" -c "${CC}" ${TO} < ${MESSAGE}
 fi
 
 rm ${MESSAGE}
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-backupz-repair-state b/scripts/usr/local/sbin/fdo-backupz-repair-state
--- a/scripts/usr/local/sbin/fdo-backupz-repair-state
+++ b/scripts/usr/local/sbin/fdo-backupz-repair-state
@@ -95,6 +95,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -104,32 +118,40 @@ then
 	exit 2
 fi
 
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
 BACKUP_POOL_ATTRIBUTES=`zpool list -H | egrep "^${BACKUP_POOL}	" 2> /dev/null`
 if [ $? -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' does not appear to be imported.\n       Aborting.\n"
-	exit 3
+	exit 4
 fi
 
 BACKUP_POOL_HEALTH=`echo ${BACKUP_POOL_ATTRIBUTES} | awk '{print $9}'`
 if [ "${BACKUP_POOL_HEALTH}" != "ONLINE" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' appears to be unhealthy.\n       Aborting.\n"
-	exit 4
+	exit 5
 fi
 
 POOL_ATTRIBUTES=`zpool list -H | egrep "^${POOL}	" 2> /dev/null`
 if [ ${?} -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported.\n       Aborting.\n"
-	exit 5
+	exit 6
 fi
 
 POOL_HEALTH=`echo ${POOL_ATTRIBUTES} | awk '{print $9}'`
 if [ "${POOL_HEALTH}" != "ONLINE" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy.\n       Aborting.\n"
-	exit 6
+	exit 7
 fi
 
 BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
@@ -137,16 +159,14 @@ BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
 if [ ! -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf ] && [ ! -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Unable to find failed backup from '${POOL}' to '${BACKUP_POOL}'!\n       Aborting.\n"
-	exit 7
+	exit 8
 fi
 
 if [ -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ] && [ ${FORCE_MODE} = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} There apppers to be a backup running for '${POOL}'!\nConsider using the --force option.\n       Aborting.\n"
-	exit 8
+	exit 9
 fi
-
-################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -180,7 +200,7 @@ if [ "${LAST_FAILED_BACKUP_SNAPSHOT}" = "${LAST_SUCCESSFUL_BACKUP_SNAPSHOT}" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The last failed backup appears to be the same as the last"
 	echo -e "       successful backup! This should never happen!\n       Aborting.\n"
-	exit 9
+	exit 10
 fi
 
 # Now we remove the failed backup snapshots from both the production pool and the backup pool.
@@ -189,7 +209,7 @@ fdo-backupz-destroy-snapshot ${BACKUP_POOL} "@${LAST_FAILED_BACKUP_SNAPSHOT}"
 if [ ${?} -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Failed to destroy failed backupz snaphots from '${BACKUP_POOL}'!\n       Aborting.\n"
-	exit 10
+	exit 11
 fi
 
 echo -e "\n${YELL}Destroying failed backupz snapshots from the production pool...${NRML}\n"
@@ -197,7 +217,7 @@ fdo-backupz-destroy-snapshot ${POOL} "@${LAST_FAILED_BACKUP_SNAPSHOT}"
 if [ ${?} -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Failed to destroy failed backupz snaphots from '${POOL}'!\n       Aborting.\n"
-	exit 11
+	exit 12
 fi
 
 # After successfully destroying failed backup snapshots, let's remove the failed backup markers.
diff --git a/scripts/usr/local/sbin/fdo-backupz-thin-snapshots b/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
--- a/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
+++ b/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
@@ -114,60 +114,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
-BACKUP_POOL_ATTRIBUTES=`zpool list -H | egrep "^${BACKUP_POOL}	" 2> /dev/null`
-if [ $? -ne 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' does not appear to be imported.\n       Aborting.\n"
-	exit 3
-fi
-
-BACKUP_POOL_HEALTH=`echo ${BACKUP_POOL_ATTRIBUTES} | awk '{print $9}'`
-if [ "${BACKUP_POOL_HEALTH}" != "ONLINE" ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' appears to be unhealthy.\n       Aborting.\n"
-	exit 4
-fi
-
-POOL_ATTRIBUTES=`zpool list -H | egrep "^${POOL}	" 2> /dev/null`
-if [ ${?} -ne 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported.\n       Aborting.\n"
-	exit 5
-fi
-
-POOL_HEALTH=`echo ${POOL_ATTRIBUTES} | awk '{print $9}'`
-if [ "${POOL_HEALTH}" != "ONLINE" ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy.\n       Aborting.\n"
-	exit 6
-fi
-
-BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
-
-if [ -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The last backup from '${POOL}' to '${BACKUP_POOL}' failed!\n       Aborting.\n"
-	exit 7
-fi
-
-if [ -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} There apppers to be a backup running for '${POOL}'!\n       Aborting.\n"
-	exit 8
-fi
-
-################################################################################
-
-
 ##### FUNCTIONS ################################################################
 
 thin_snapshots_by_filesystem()
@@ -264,7 +210,76 @@ thin_snapshots_by_filesystem()
 
 }
 
-################################################################################
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
+
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
+BACKUP_POOL_ATTRIBUTES=`zpool list -H | egrep "^${BACKUP_POOL}	" 2> /dev/null`
+if [ $? -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' does not appear to be imported.\n       Aborting.\n"
+	exit 4
+fi
+
+BACKUP_POOL_HEALTH=`echo ${BACKUP_POOL_ATTRIBUTES} | awk '{print $9}'`
+if [ "${BACKUP_POOL_HEALTH}" != "ONLINE" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' appears to be unhealthy.\n       Aborting.\n"
+	exit 5
+fi
+
+POOL_ATTRIBUTES=`zpool list -H | egrep "^${POOL}	" 2> /dev/null`
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported.\n       Aborting.\n"
+	exit 6
+fi
+
+POOL_HEALTH=`echo ${POOL_ATTRIBUTES} | awk '{print $9}'`
+if [ "${POOL_HEALTH}" != "ONLINE" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy.\n       Aborting.\n"
+	exit 7
+fi
+
+BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
+
+if [ -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The last backup from '${POOL}' to '${BACKUP_POOL}' failed!\n       Aborting.\n"
+	exit 8
+fi
+
+if [ -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There apppers to be a backup running for '${POOL}'!\n       Aborting.\n"
+	exit 9
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
diff --git a/scripts/usr/local/sbin/fdo-dhcpd-edit b/scripts/usr/local/sbin/fdo-dhcpd-edit
--- a/scripts/usr/local/sbin/fdo-dhcpd-edit
+++ b/scripts/usr/local/sbin/fdo-dhcpd-edit
@@ -98,15 +98,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -176,7 +167,15 @@ get_jail_id_from_name ()
 
 }
 
-################################################################################
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -220,6 +219,7 @@ then
 	CMD_PREFIX="jexec ${JAIL_ID}"  
 fi
 
+# Test if the config file exists
 if [ ! -f "${CONFIG_FILE}" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The dhcpd config file '${CONFIG_FILE}' does not exist!\n       Aborting.\n"
diff --git a/scripts/usr/local/sbin/fdo-disable-sata-ncq b/scripts/usr/local/sbin/fdo-disable-sata-ncq
--- a/scripts/usr/local/sbin/fdo-disable-sata-ncq
+++ b/scripts/usr/local/sbin/fdo-disable-sata-ncq
@@ -88,6 +88,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -97,12 +111,13 @@ then
 	exit 2
 fi
 
+test_if_host
 
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -122,7 +137,7 @@ done
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 3
+	exit 4
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-dns_cache-add-hostname b/scripts/usr/local/sbin/fdo-dns_cache-add-hostname
--- a/scripts/usr/local/sbin/fdo-dns_cache-add-hostname
+++ b/scripts/usr/local/sbin/fdo-dns_cache-add-hostname
@@ -99,16 +99,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -187,12 +177,34 @@ test_valid_fqhn ()
 
 }
 
-################################################################################
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
 
 
-##### MAIN EXECUTION THREAD ####################################################
+##### SANITY TESTS #############################################################
 
-ERROR_COUNT=0
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
+
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
 
 # Check that the hostname is valid.
 test_valid_fqhn  "${HOST_NAME}"
@@ -202,7 +214,7 @@ then
 	echo -e "       It must only contain letters, numbers, periods and hyphens."
 	echo -e "       It must not begin or end with a hyphen or a period."
 	echo -e "       Aborting.\n"
-	exit 3
+	exit 4
 fi
 
 # Test if ip_address is valid
@@ -211,8 +223,13 @@ if [ "${VALID_INET_ADDRESS}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} IP address is invalid!"
 	echo -e "       Aborting.\n"
-	exit 4
+	exit 5
 fi
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
 
 # Iterate through all jails...
 for JAIL_NAME in `ls -1 /jls | cut -d/ -f1 | egrep -v "template"`
@@ -233,7 +250,7 @@ do
 			then
 				echo -e "\n${LRED}ERROR:${NRML} The record for hostname '${HOST_NAME}' already exists!"
 				echo -e "       Aborting.\n"
-				exit 5
+				exit 6
 			fi
 
 			# Since it does not already exist, let's add a zone for our new hostname record:
@@ -288,13 +305,13 @@ done
 if [ "${DNS_CACHE_SERVER_FOUND}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} No caching dns server found!\n       Aborting.\n"
-	exit 6
+	exit 7
 fi
 
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 7
+	exit 8
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-dns_cache-list-hostnames b/scripts/usr/local/sbin/fdo-dns_cache-list-hostnames
--- a/scripts/usr/local/sbin/fdo-dns_cache-list-hostnames
+++ b/scripts/usr/local/sbin/fdo-dns_cache-list-hostnames
@@ -97,6 +97,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -106,12 +120,13 @@ then
 	exit 2
 fi
 
+test_if_host
 
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -137,12 +152,12 @@ done
 
 if [ "${DNS_CACHE_SERVER_FOUND}" = "no" ]
 then
-	exit 3
+	exit 4
 fi
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 4
+	exit 5
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-file_server-check-shared-folder-quota b/scripts/usr/local/sbin/fdo-file_server-check-shared-folder-quota
--- a/scripts/usr/local/sbin/fdo-file_server-check-shared-folder-quota
+++ b/scripts/usr/local/sbin/fdo-file_server-check-shared-folder-quota
@@ -90,6 +90,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -99,19 +113,20 @@ then
 	exit 2
 fi
 
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
 zfs list ${WEBDAV_ROOT_FS}/${SITE_NAME}/shares/${SHARE_PATH} > /dev/null 2>&1
 if [ ${?} -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The referenced file_server share does not exist!\n       Aborting.\n"
-	exit 3
+	exit 4
 fi
-
-
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -124,7 +139,7 @@ zfs get quota ${WEBDAV_ROOT_FS}/${SITE_NAME}/shares/${SHARE_PATH}
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 4
+	exit 5
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-file_server-create-user-folder b/scripts/usr/local/sbin/fdo-file_server-create-user-folder
--- a/scripts/usr/local/sbin/fdo-file_server-create-user-folder
+++ b/scripts/usr/local/sbin/fdo-file_server-create-user-folder
@@ -94,6 +94,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -103,26 +117,27 @@ then
 	exit 2
 fi
 
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
 zfs list ${WEBDAV_ROOT_FS}/${SITE_NAME}/users/${USERNAME} > /dev/null 2>&1
 if [ ${?} -eq 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The referenced file_server user folder already exists!\n       Aborting.\n"
-	exit 3
+	exit 4
 fi
 
 # Check that we are not currently running a backupz operation.
 ps aux | grep "backupz"  | grep -v "grep backupz"
 if [ ${?} -eq 0 ]; then
 	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\n       Aborting.\n"
-	exit 3
+	exit 5
 fi
-
-
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -138,5 +153,5 @@ chown -R ${WEBDAV_UID}:${WEBDAV_GID} ${WEBDAV_ROOT_MOUNTPOINT}/${SITE_NAME}/user
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 4
+	exit 6
 fi
diff --git a/scripts/usr/local/sbin/fdo-file_server-edit b/scripts/usr/local/sbin/fdo-file_server-edit
--- a/scripts/usr/local/sbin/fdo-file_server-edit
+++ b/scripts/usr/local/sbin/fdo-file_server-edit
@@ -28,9 +28,10 @@
 
 SCRIPT_NAME=`basename ${0}`
 NUM_MANDATORY_ARGS=0
-WEBDAV_CONFIG_ROOT="/usr/local/etc/webdav-sites"
+CONFIG_ROOT="/usr/local/etc/webdav-sites"
 WEBDAV_SERVICE=apache22
-DIALOG_OUT_FILE="/tmp/fdo-file_server-edit.dialog.answer"
+RECIPE_NAME="file_server"
+DIALOG_OUT_FILE="/tmp/${SCRIPT_NAME}.dialog.answer"
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -98,23 +99,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
-if [ ! -e "${WEBDAV_CONFIG_ROOT}" ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The WebDAV config root '${WEBDAV_CONFIG_ROOT}'\ndoes not exist!\n       Aborting.\n"
-	usage
-	exit 3
-fi
-
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -135,20 +119,123 @@ question_yes_no ()
 
 }
 
-################################################################################
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+find_jails_from_recipe_name ()
+{
+	FIND_RECIPE_NAME="${1}"
+	FOUND_RECIPE_JAILS=""
+	for TEST_JAIL_NAME in `ls -1 /jls | cut -d/ -f1`
+	do
+		if [ -f "/jls/${TEST_JAIL_NAME}/.fdo-jail-recipe.inf" ]
+		then
+			TEST_RECIPE_NAME=`cat /jls/${TEST_JAIL_NAME}/.fdo-jail-recipe.inf`
+			if [ "${TEST_RECIPE_NAME}" = "${FIND_RECIPE_NAME}" ]
+			then
+				if [ "${FOUND_RECIPE_JAILS}" = "" ]
+				then
+					FOUND_RECIPE_JAILS="${TEST_JAIL_NAME}"
+				else
+					FOUND_RECIPE_JAILS="${FOUND_RECIPE_JAILS} ${TEST_JAIL_NAME}"
+				fi
+			fi
+		fi
+	done
+
+}
+
+get_jail_id_from_name ()
+{
+	# ${1} is jail name
+
+	JAIL_ID_FILE=`ls -1 /var/run/jail_${1}.id 2> /dev/null | head -1`
+	if [ "${JAIL_ID_FILE}" = "" ] 
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Could not identify jail id from jail name.\n"
+		JAIL_ID=-1
+		return 1
+	fi
+	JAIL_ID=`cat ${JAIL_ID_FILE}`
+
+}
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
+JAIL_NAME=""
+CMD_PREFIX=""
+
+test_if_host
+
+if [ "${IS_HOST}" = "yes" ]
+then
+	# Let's try to find the jail
+	find_jails_from_recipe_name ${RECIPE_NAME}
+	NUM_FOUND_JAILS=`echo ${FOUND_RECIPE_JAILS} | wc -w`
+	if [ ${NUM_FOUND_JAILS} -lt 1 ]
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Unable to find a '${RECIPE_NAME}' recipe jail!\n       Aborting.\n"
+		usage
+		exit 3
+	fi
+	if [ ${NUM_FOUND_JAILS} -lt 2 ]
+	then
+		JAIL_NAME=${FOUND_RECIPE_JAILS}
+	else
+		SELECT_JAIL_PROMPT="Select the DHCP server jail to edit:"
+		while [ "${JAIL_NAME}" = "" ]
+		do
+			dialog --no-items --no-cancel --menu "${SELECT_JAIL_PROMPT}" 12 40 10 ${FOUND_RECIPE_JAILS} 2> ${DIALOG_OUT_FILE}
+			JAIL_NAME_TEMP=`cat ${DIALOG_OUT_FILE}`
+			echo -e "\n"
+			question_yes_no "\nYou have selected '${JAIL_NAME_TEMP}' as the DHCP jail to edit.\nIs this correct?"
+			if [ "${ANSWER}" = "yes" ]
+			then
+				JAIL_NAME="${JAIL_NAME_TEMP}"
+			fi
+		done
+	fi
+	CONFIG_ROOT="/jls/${JAIL_NAME}${CONFIG_ROOT}"
+	get_jail_id_from_name ${JAIL_NAME}
+	CMD_PREFIX="jexec ${JAIL_ID}"  
+fi
+
+# Test if the config root exists
+if [ ! -e "${CONFIG_ROOT}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The WebDAV config root '${CONFIG_ROOT}' does not exist!\n       Aborting.\n"
+	usage
+	exit 4
+fi
+
 
 # Get site names from site config directory.
-SITES_AVAILABLE=`ls -1 ${WEBDAV_CONFIG_ROOT}/ | sort`
+SITES_AVAILABLE=`ls -1 ${CONFIG_ROOT}/ | sort`
 NUM_SITES_AVAILABLE=`echo ${SITES_AVAILABLE} | wc -w`
 if [ ${NUM_SITES_AVAILABLE} -lt 1 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} The WebDAV config root '${WEBDAV_CONFIG_ROOT}'\ndoes not contain any site configs!\n       Aborting.\n"
-	exit 4
+	echo -e "\n${LRED}ERROR:${NRML} The WebDAV config root '${CONFIG_ROOT}'\ndoes not contain any site configs!\n       Aborting.\n"
+	exit 5
 fi
 SITE=""
 if [ ${NUM_SITES_AVAILABLE} -lt 2 ]
@@ -168,22 +255,22 @@ do
 	fi
 done
 
-WEBDAV_CONFIG_FILE="${WEBDAV_CONFIG_ROOT}/${SITE}"
+CONFIG_FILE="${CONFIG_ROOT}/${SITE}"
 
 # Open the WebDAV server config file in users preferred editor.
-${EDITOR} ${WEBDAV_CONFIG_FILE}
+${EDITOR} ${CONFIG_FILE}
 
 question_yes_no "\nWould you like to reload the service to pick up any changes now?"
 if [ "${ANSWER}" = "yes" ]
 then
-	service ${WEBDAV_SERVICE} restart
+	${CMD_PREFIX} service ${WEBDAV_SERVICE} restart
 fi
 
 echo -e ""
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 5
+	exit 6
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-file_server-set-user-folder-quota b/scripts/usr/local/sbin/fdo-file_server-set-user-folder-quota
--- a/scripts/usr/local/sbin/fdo-file_server-set-user-folder-quota
+++ b/scripts/usr/local/sbin/fdo-file_server-set-user-folder-quota
@@ -91,6 +91,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -100,19 +114,20 @@ then
 	exit 2
 fi
 
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
 zfs list ${WEBDAV_ROOT_FS}/${SITE_NAME}/users/${USERNAME} > /dev/null 2>&1
 if [ ${?} -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The referenced file_server user folder does not exist!\n       Aborting.\n"
-	exit 3
+	exit 4
 fi
-
-
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -126,7 +141,7 @@ echo -e "\n${LGRN}User folder quota has been set to ${QUOTA} for the user ${USER
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 4
+	exit 5
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-hotdesk-add-user b/scripts/usr/local/sbin/fdo-hotdesk-add-user
--- a/scripts/usr/local/sbin/fdo-hotdesk-add-user
+++ b/scripts/usr/local/sbin/fdo-hotdesk-add-user
@@ -92,23 +92,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
-# Check that we are not currently running a backupz operation.
-ps aux | grep "backupz"  | grep -v "grep backupz"
-if [ ${?} -eq 0 ]; then
-	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\n       Aborting.\n"
-	exit 3
-fi
-
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -161,7 +144,41 @@ test_valid_integer ()
 
 }
 
-################################################################################
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
+
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
+# Check that we are not currently running a backupz operation.
+ps aux | grep "backupz"  | grep -v "grep backupz"
+if [ ${?} -eq 0 ]; then
+	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\n       Aborting.\n"
+	exit 4
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -223,7 +240,7 @@ echo -e "\n${LGRN}Operation complete!${NRML}\n"
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 4
+	exit 5
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-hotdesk-remove-user b/scripts/usr/local/sbin/fdo-hotdesk-remove-user
--- a/scripts/usr/local/sbin/fdo-hotdesk-remove-user
+++ b/scripts/usr/local/sbin/fdo-hotdesk-remove-user
@@ -99,6 +99,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -108,11 +122,19 @@ then
 	exit 2
 fi
 
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
 # Check that we are not currently running a backupz operation.
 ps aux | grep "backupz"  | grep -v "grep backupz"
 if [ ${?} -eq 0 ]; then
 	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\n       Aborting.\n"
-	exit 3
+	exit 4
 fi
 
 # Check that user exists.
@@ -121,16 +143,9 @@ if [ ${?} -ne 0 ]; then
 	echo -e "\n${LRED}ERROR:${NRML} User does not exists, please check username!\n       Aborting.\n"
 	if [ "${FORCE_MODE}" !=  "yes" ]
 	then
-		exit 4
+		exit 5
 	fi
 fi
-
-
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -145,7 +160,7 @@ then
 	echo -e "\n${LRED}ERROR:${NRML} Hotdesk user home directory not destroyed, please verify username!\n       Aborting.\n"
 	if [ "${FORCE_MODE}" !=  "yes" ]
 	then
-		exit 5
+		exit 6
 	fi
 else
 	echo -e "\n${YELL}Hotdesk user home folder destroyed.${NRML}\n"
@@ -172,7 +187,7 @@ echo "\n${LGRN}Operation complete!${NRML}\n"
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 6
+	exit 7
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-imap-manage-mailboxes b/scripts/usr/local/sbin/fdo-imap-manage-mailboxes
--- a/scripts/usr/local/sbin/fdo-imap-manage-mailboxes
+++ b/scripts/usr/local/sbin/fdo-imap-manage-mailboxes
@@ -31,6 +31,8 @@ NUM_MANDATORY_ARGS=0
 IMAP_MBOX_MGMNT_CMD=cyradm
 IMAP_MBOX_MGMNT_USER=cyrus
 IMAP_MBOX_MGMNT_HOST=localhost
+RECIPE_NAME="imap_server"
+DIALOG_OUT_FILE="/tmp/${SCRIPT_NAME}.dialog.answer"
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -98,23 +100,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
-which "${IMAP_MBOX_MGMNT_CMD}" > /dev/null 2>&1
-if [ ${?} -ne 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The IMAP server management command '${IMAP_MBOX_MGMNT_CMD}' does not exist!\n       Aborting.\n"
-	exit 3
-fi
-
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -135,18 +120,119 @@ question_yes_no ()
 
 }
 
-################################################################################
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+find_jails_from_recipe_name ()
+{
+	FIND_RECIPE_NAME="${1}"
+	FOUND_RECIPE_JAILS=""
+	for TEST_JAIL_NAME in `ls -1 /jls | cut -d/ -f1`
+	do
+		if [ -f "/jls/${TEST_JAIL_NAME}/.fdo-jail-recipe.inf" ]
+		then
+			TEST_RECIPE_NAME=`cat /jls/${TEST_JAIL_NAME}/.fdo-jail-recipe.inf`
+			if [ "${TEST_RECIPE_NAME}" = "${FIND_RECIPE_NAME}" ]
+			then
+				if [ "${FOUND_RECIPE_JAILS}" = "" ]
+				then
+					FOUND_RECIPE_JAILS="${TEST_JAIL_NAME}"
+				else
+					FOUND_RECIPE_JAILS="${FOUND_RECIPE_JAILS} ${TEST_JAIL_NAME}"
+				fi
+			fi
+		fi
+	done
+
+}
+
+get_jail_id_from_name ()
+{
+	# ${1} is jail name
+
+	JAIL_ID_FILE=`ls -1 /var/run/jail_${1}.id 2> /dev/null | head -1`
+	if [ "${JAIL_ID_FILE}" = "" ] 
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Could not identify jail id from jail name.\n"
+		JAIL_ID=-1
+		return 1
+	fi
+	JAIL_ID=`cat ${JAIL_ID_FILE}`
+
+}
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
+JAIL_NAME=""
+CMD_PREFIX=""
 
-${IMAP_MBOX_MGMNT_CMD} -user ${IMAP_MBOX_MGMNT_USER} ${IMAP_MBOX_MGMNT_HOST}
+test_if_host
+
+if [ "${IS_HOST}" = "yes" ]
+then
+	# Let's try to find the jail
+	find_jails_from_recipe_name ${RECIPE_NAME}
+	NUM_FOUND_JAILS=`echo ${FOUND_RECIPE_JAILS} | wc -w`
+	if [ ${NUM_FOUND_JAILS} -lt 1 ]
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Unable to find a '${RECIPE_NAME}' recipe jail!\n       Aborting.\n"
+		usage
+		exit 3
+	fi
+	if [ ${NUM_FOUND_JAILS} -lt 2 ]
+	then
+		JAIL_NAME=${FOUND_RECIPE_JAILS}
+	else
+		SELECT_JAIL_PROMPT="Select the IMAP server jail to edit:"
+		while [ "${JAIL_NAME}" = "" ]
+		do
+			dialog --no-items --no-cancel --menu "${SELECT_JAIL_PROMPT}" 12 40 10 ${FOUND_RECIPE_JAILS} 2> ${DIALOG_OUT_FILE}
+			JAIL_NAME_TEMP=`cat ${DIALOG_OUT_FILE}`
+			echo -e "\n"
+			question_yes_no "\nYou have selected '${JAIL_NAME_TEMP}' as the IMAP jail to edit.\nIs this correct?"
+			if [ "${ANSWER}" = "yes" ]
+			then
+				JAIL_NAME="${JAIL_NAME_TEMP}"
+			fi
+		done
+	fi
+	get_jail_id_from_name ${JAIL_NAME}
+	CMD_PREFIX="jexec ${JAIL_ID}"  
+fi
+
+# Test if the management command exists
+${CMD_PREFIX} which "${IMAP_MBOX_MGMNT_CMD}" > /dev/null 2>&1
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The IMAP management command '${IMAP_MBOX_MGMNT_CMD}' does not exist!\n       Aborting.\n"
+	exit 4
+fi
+
+${CMD_PREFIX} ${IMAP_MBOX_MGMNT_CMD} -user ${IMAP_MBOX_MGMNT_USER} ${IMAP_MBOX_MGMNT_HOST}
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 4
+	exit 5
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-ldap-edit b/scripts/usr/local/sbin/fdo-ldap-edit
--- a/scripts/usr/local/sbin/fdo-ldap-edit
+++ b/scripts/usr/local/sbin/fdo-ldap-edit
@@ -101,15 +101,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -179,7 +170,15 @@ get_jail_id_from_name ()
 
 }
 
-################################################################################
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -224,6 +223,7 @@ then
 	CMD_PREFIX="jexec ${JAIL_ID}"  
 fi
 
+# Test if the management command exists
 ${CMD_PREFIX} which "${LDAP_EDIT_CMD}" > /dev/null 2>&1
 if [ ${?} -ne 0 ]
 then
diff --git a/scripts/usr/local/sbin/fdo-pf-list-port-forward-rules b/scripts/usr/local/sbin/fdo-pf-list-port-forward-rules
--- a/scripts/usr/local/sbin/fdo-pf-list-port-forward-rules
+++ b/scripts/usr/local/sbin/fdo-pf-list-port-forward-rules
@@ -100,23 +100,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
-if [ ! -f ${PF_CONF_PATH} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The pf config file '${PF_CONF_PATH}' does not exist!\n       Aborting.\n"
-	usage
-	exit 3 
-fi
-
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -154,7 +137,41 @@ test_valid_rule_name ()
 
 }
 
-################################################################################
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
+
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
+if [ ! -f ${PF_CONF_PATH} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The pf config file '${PF_CONF_PATH}' does not exist!\n       Aborting.\n"
+	usage
+	exit 4
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -177,7 +194,7 @@ done
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 6
+	exit 5
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule b/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
--- a/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
+++ b/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
@@ -107,23 +107,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
-if [ ! -f ${PPP_CONF_PATH} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The ppp config file '${PPP_CONF_PATH}' does not exist!\n       Aborting.\n"
-	usage
-	exit 3 
-fi
-
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -228,7 +211,41 @@ test_valid_inet_address ()
 
 }
 
-################################################################################
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
+
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
+if [ ! -f ${PPP_CONF_PATH} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The ppp config file '${PPP_CONF_PATH}' does not exist!\n       Aborting.\n"
+	usage
+	exit 4
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -240,7 +257,7 @@ test_valid_rule_name "${RULE_NAME}"
 if [ "${VALID_RULE_NAME}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Rule name invalid!\n"
-	exit 4
+	exit 5
 fi
 
 # Test if rule_name already exists
@@ -248,7 +265,7 @@ cat ${PPP_CONF_PATH} | egrep "rule_name=${RULE_NAME}" > /dev/null 2>&1
 if [ ${?} -eq 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Rule name '${RULE_NAME}' is already in use!\n"
-	exit 5
+	exit 6
 fi
 
 # Test if local_ip_address is valid
@@ -256,7 +273,7 @@ test_valid_inet_address "${LOCAL_IP}"
 if [ "${VALID_INET_ADDRESS}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Local IP address is invalid!\n"
-	exit 6
+	exit 7
 fi
 
 # Test if tcp_ports is valid
@@ -264,7 +281,7 @@ test_valid_port_list "${TCP_PORTS}"
 if [ "${VALID_PORT_LIST}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} TCP port list ('tcp_ports') is invalid!\n"
-	exit 7
+	exit 8
 fi
 
 # Test if udp_ports is valid
@@ -272,14 +289,14 @@ test_valid_port_list "${UDP_PORTS}"
 if [ "${VALID_PORT_LIST}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} UDP port list ('udp_ports') is invalid!\n"
-	exit 8
+	exit 9
 fi
 
 # Test if both tcp_ports and udp_ports are 'none'
 if [ "${TCP_PORTS}" = "none" ] && [ "${UDP_PORTS}" = "none" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} No ports specified!\n"
-	exit 9
+	exit 10
 fi
 
 
@@ -330,7 +347,7 @@ fi
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 10
+	exit 11
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-ppp-remove-port-forward-rule b/scripts/usr/local/sbin/fdo-ppp-remove-port-forward-rule
--- a/scripts/usr/local/sbin/fdo-ppp-remove-port-forward-rule
+++ b/scripts/usr/local/sbin/fdo-ppp-remove-port-forward-rule
@@ -99,23 +99,6 @@ do
 done
 
 
-##### SANITY TESTS #############################################################
-
-if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
-	usage
-	exit 2
-fi
-
-if [ ! -f ${PPP_CONF_PATH} ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The ppp config file '${PPP_CONF_PATH}' does not exist!\n       Aborting.\n"
-	usage
-	exit 3 
-fi
-
-
 ##### FUNCTIONS ################################################################
 
 question_yes_no ()
@@ -153,7 +136,41 @@ test_valid_rule_name ()
 
 }
 
-################################################################################
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\n       Aborting.\n"
+	usage
+	exit 2
+fi
+
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
+if [ ! -f ${PPP_CONF_PATH} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The ppp config file '${PPP_CONF_PATH}' does not exist!\n       Aborting.\n"
+	usage
+	exit 4
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -165,7 +182,7 @@ test_valid_rule_name "${RULE_NAME}"
 if [ "${VALID_RULE_NAME}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Rule name invalid!\n"
-	exit 4
+	exit 5
 fi
 
 # Test if rule_name exists
@@ -173,7 +190,7 @@ cat ${PPP_CONF_PATH} | egrep "rule_name=${RULE_NAME}" > /dev/null 2>&1
 if [ ${?} -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Rule name '${RULE_NAME}' does not exist!\n"
-	exit 5
+	exit 6
 fi
 
 # Remove all lines mentioning the specified rule_name
@@ -200,7 +217,7 @@ fi
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 6
+	exit 7
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-sip-add-user b/scripts/usr/local/sbin/fdo-sip-add-user
--- a/scripts/usr/local/sbin/fdo-sip-add-user
+++ b/scripts/usr/local/sbin/fdo-sip-add-user
@@ -32,6 +32,8 @@ DOMAIN_NAME="${2}"
 NUM_MANDATORY_ARGS=2
 PASSWORD=""
 SIP_MGMNT_CMD=opensipsctl
+RECIPE_NAME="sip_server"
+DIALOG_OUT_FILE="/tmp/${SCRIPT_NAME}.dialog.answer"
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -100,6 +102,76 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+question_yes_no ()
+{
+
+	LOOP=1
+
+	while [ ${LOOP} = 1 ]
+		do
+		echo -e "${LCYN}${1} (yes/no): ${NRML}\c"
+		read ANSWER
+		if [ "${ANSWER}" = "yes" ] || [ "${ANSWER}" = "no" ]
+		then
+			LOOP=0
+		fi
+		echo ""
+	done
+
+}
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+find_jails_from_recipe_name ()
+{
+	FIND_RECIPE_NAME="${1}"
+	FOUND_RECIPE_JAILS=""
+	for TEST_JAIL_NAME in `ls -1 /jls | cut -d/ -f1`
+	do
+		if [ -f "/jls/${TEST_JAIL_NAME}/.fdo-jail-recipe.inf" ]
+		then
+			TEST_RECIPE_NAME=`cat /jls/${TEST_JAIL_NAME}/.fdo-jail-recipe.inf`
+			if [ "${TEST_RECIPE_NAME}" = "${FIND_RECIPE_NAME}" ]
+			then
+				if [ "${FOUND_RECIPE_JAILS}" = "" ]
+				then
+					FOUND_RECIPE_JAILS="${TEST_JAIL_NAME}"
+				else
+					FOUND_RECIPE_JAILS="${FOUND_RECIPE_JAILS} ${TEST_JAIL_NAME}"
+				fi
+			fi
+		fi
+	done
+
+}
+
+get_jail_id_from_name ()
+{
+	# ${1} is jail name
+
+	JAIL_ID_FILE=`ls -1 /var/run/jail_${1}.id 2> /dev/null | head -1`
+	if [ "${JAIL_ID_FILE}" = "" ] 
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Could not identify jail id from jail name.\n"
+		JAIL_ID=-1
+		return 1
+	fi
+	JAIL_ID=`cat ${JAIL_ID_FILE}`
+
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -109,24 +181,54 @@ then
 	exit 2
 fi
 
-which "${SIP_MGMNT_CMD}" > /dev/null 2>&1
-if [ ${?} -ne 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The SIP server management command '${SIP_MGMNT_CMD}' does not exist!\n       Aborting.\n"
-	exit 3
-fi
-
-
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
-
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
+JAIL_NAME=""
+CMD_PREFIX=""
+
+test_if_host
+
+if [ "${IS_HOST}" = "yes" ]
+then
+	# Let's try to find the jail
+	find_jails_from_recipe_name ${RECIPE_NAME}
+	NUM_FOUND_JAILS=`echo ${FOUND_RECIPE_JAILS} | wc -w`
+	if [ ${NUM_FOUND_JAILS} -lt 1 ]
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Unable to find a '${RECIPE_NAME}' recipe jail!\n       Aborting.\n"
+		usage
+		exit 3
+	fi
+	if [ ${NUM_FOUND_JAILS} -lt 2 ]
+	then
+		JAIL_NAME=${FOUND_RECIPE_JAILS}
+	else
+		SELECT_JAIL_PROMPT="Select the SIP server jail to edit:"
+		while [ "${JAIL_NAME}" = "" ]
+		do
+			dialog --no-items --no-cancel --menu "${SELECT_JAIL_PROMPT}" 12 40 10 ${FOUND_RECIPE_JAILS} 2> ${DIALOG_OUT_FILE}
+			JAIL_NAME_TEMP=`cat ${DIALOG_OUT_FILE}`
+			echo -e "\n"
+			question_yes_no "\nYou have selected '${JAIL_NAME_TEMP}' as the SIP jail to edit.\nIs this correct?"
+			if [ "${ANSWER}" = "yes" ]
+			then
+				JAIL_NAME="${JAIL_NAME_TEMP}"
+			fi
+		done
+	fi
+	get_jail_id_from_name ${JAIL_NAME}
+	CMD_PREFIX="jexec ${JAIL_ID}"  
+fi
+
+# Test if the management command exists
+${CMD_PREFIX} which "${SIP_MGMNT_CMD}" > /dev/null 2>&1
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The SIP management command '${SIP_MGMNT_CMD}' does not exist!\n       Aborting.\n"
+	exit 4
+fi
 
 # If password was not given as argument, prompt for it from user.
 while [ "${PASSWORD}" = "" ]
@@ -148,11 +250,11 @@ do
 done
 
 echo -e "\n${YELL}Adding SIP user...${NRML}\n"
-${SIP_MGMNT_CMD} add ${USERNAME} ${PASSWORD}
+${CMD_PREFIX} ${SIP_MGMNT_CMD} add ${USERNAME} ${PASSWORD}
 if [ ${?} -eq 0 ]
 then
 	echo -e "\n${YELL}Setting domain for SIP user...${NRML}\n"
-	${SIP_MGMNT_CMD} db exec "update subscriber set domain  = '${DOMAIN_NAME}' where username like '${USERNAME}'"
+	${CMD_PREFIX} ${SIP_MGMNT_CMD} db exec "update subscriber set domain  = '${DOMAIN_NAME}' where username like '${USERNAME}'"
 	if [ ${?} -eq 0 ]
 	then
 		echo -e "\n${LGRN}Operation completed!${NRML}\n"
@@ -165,7 +267,7 @@ fi
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 4
+	exit 5
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-storage-perf-test b/scripts/usr/local/sbin/fdo-storage-perf-test
--- a/scripts/usr/local/sbin/fdo-storage-perf-test
+++ b/scripts/usr/local/sbin/fdo-storage-perf-test
@@ -92,6 +92,20 @@ do
 done
 
 
+##### FUNCTIONS ################################################################
+
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+
 ##### SANITY TESTS #############################################################
 
 if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
@@ -101,26 +115,27 @@ then
 	exit 2
 fi
 
+test_if_host
+
+if [ "${IS_HOST}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
+	exit 3
+fi
+
 POOL_ATTRIBUTES=`zpool list -H | egrep "^${POOL}	" 2> /dev/null`
 if [ ${?} -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported.\n       Aborting.\n"
-	exit 3
+	exit 4
 fi
 
 POOL_HEALTH=`echo ${POOL_ATTRIBUTES} | awk '{print $9}'`
 if [ "${POOL_HEALTH}" != "ONLINE" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy.\n       Aborting.\n"
-	exit 4
+	exit 5
 fi
-
-
-##### FUNCTIONS ################################################################
-
-
-
-################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -137,7 +152,7 @@ echo -e ""
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 5
+	exit 6
 fi
 
 ################################################################################
