scripts: add check for root privileges on all super-user (sbin) scripts.

diff --git a/scripts/usr/local/sbin/fdo-imap-manage-mailboxes b/scripts/usr/local/sbin/fdo-imap-manage-mailboxes
--- a/scripts/usr/local/sbin/fdo-imap-manage-mailboxes
+++ b/scripts/usr/local/sbin/fdo-imap-manage-mailboxes
@@ -180,14 +180,22 @@ then
 	exit 1
 fi
 
+# Check we are running with root privileges.
+if [ `id -u` -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run with root (super-user) privileges!\n       Aborting.\n"
+	exit 1
+fi
+
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
-JAIL_NAME=""
-CMD_PREFIX=""
 
 test_if_host
+
+JAIL_NAME=""
+CMD_PREFIX=""
 
 if [ "${IS_HOST}" = "yes" ]
 then
diff --git a/scripts/usr/local/sbin/fdo-vms-list b/scripts/usr/local/sbin/fdo-vms-list
--- a/scripts/usr/local/sbin/fdo-vms-list
+++ b/scripts/usr/local/sbin/fdo-vms-list
@@ -218,8 +218,16 @@ then
 	exit 1
 fi
 
+# Check we are running with root privileges.
+if [ `id -u` -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run with root (super-user) privileges!\n       Aborting.\n"
+	exit 1
+fi
+
 # Check that this is run from the host, and not a jail.
 test_if_host
+
 if [ "${IS_HOST}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} This command must be run from the host!\n       Aborting.\n"
diff --git a/scripts/usr/local/sbin/jlogin b/scripts/usr/local/sbin/jlogin
--- a/scripts/usr/local/sbin/jlogin
+++ b/scripts/usr/local/sbin/jlogin
@@ -107,6 +107,13 @@ then
 	exit 1
 fi
 
+# Check we are running with root privileges.
+if [ `id -u` -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} This command must be run with root (super-user) privileges!\n       Aborting.\n"
+	exit 1
+fi
+
 
 ##### FUNCTIONS ################################################################
 
