Refactoring: more massive changes to scripts to bring them into line with shell script coding standards. Other improvements to scripts.

diff --git a/scripts/usr/local/sbin/fdo-dns_cache-remove-hostname b/scripts/usr/local/sbin/fdo-dns_cache-remove-hostname
--- a/scripts/usr/local/sbin/fdo-dns_cache-remove-hostname
+++ b/scripts/usr/local/sbin/fdo-dns_cache-remove-hostname
@@ -12,94 +12,158 @@
 #    notice, this list of conditions and the following disclaimer in the
 #    documentation and/or other materials provided with the distribution.
 #
-# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY 
-# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
-# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
-# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY 
-# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
-# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
-# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
-# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
-# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 
-SCRIPT_NAME=`basename $0`
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
+SCRIPT_NAME=`basename ${0}`
+HOST_NAME="${1}"
+NUM_MANDATORY_ARGS=1
+DNS_CACHE_SERVER_FOUND=no
+
+TERM="xterm"
 LRED="\033[1;31m"
 LGRN="\033[1;32m"
 LBLU="\033[1;34m"
 LCYN="\033[1;36m"
+CYAN="\033[0;36m"
 YELL="\033[1;33m"
 ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
 NRML="\033[0;00m"
 
 CARRIAGE_RETURN="
 "
 
-usage (){
-  echo -e ""
-  echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} hostname${NRML}"
-  echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} site1.example.net${NRML}"
-  echo -e ""
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Remove hostname zone from FDo dns_cache jail services on this host."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} hostname${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} site1.example.net${NRML}"
+	echo -e ""
 }
 
-if [ $# -ne 1 ]
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
 then
-  usage
-  exit 1
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
 
-HOST_NAME=${1}
-DNS_CACHE_SERVER_FOUND=no
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
 
 # Iterate through all jails...
 for JAIL_NAME in `ls -1 /jls | cut -d/ -f1 | egrep -v "template"`
 do
-  # ...and if a bind server exists...
-  if [ -f "/jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf" ]
-  then
-    # ...determine if it's a caching server
-    cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^( )*forwarders {" > /dev/null 2>&1
-    if [ ${?} -eq 0 ] 
-    then
+	# ...and if a bind server exists...
+	if [ -f "/jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf" ]
+	then
+		# ...determine if it's a caching server
+		cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^( )*forwarders {" > /dev/null 2>&1
+		if [ ${?} -eq 0 ] 
+		then
 
-      DNS_CACHE_SERVER_FOUND=yes
+			DNS_CACHE_SERVER_FOUND=yes
 
-      # Now that we've found a caching server, let's see if the record exists:
-      cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^zone \"${HOST_NAME}\"" > /dev/null 2>&1
-      if [ ${?} -ne 0 ]
-      then
-        echo -e "\n${ORNG}WARNING:${NRML} The record for hostname ${HOST_NAME} doesn't exist!\n"
-        exit 2
-      fi
+			# Now that we've found a caching server, let's see if the record exists:
+			cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^zone \"${HOST_NAME}\"" > /dev/null 2>&1
+			if [ ${?} -ne 0 ]
+			then
+				echo -e "\n${ORNG}WARNING:${NRML} The record for hostname ${HOST_NAME} doesn't exist!\n"
+				exit 3
+			fi
 
-      # Hostname record exists, so now let's remove the zone for the hostname record:
+			# Hostname record exists, so now let's remove the zone for the hostname record:
 
-      # - Remove zone entry from named.conf
-      sed -i "" "/^zone \"${HOST_NAME}\"/d" /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf
+			# - Remove zone entry from named.conf
+			sed -i "" "/^zone \"${HOST_NAME}\"/d" /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf
 
-      # - Remove the master zone file
-      rm /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db > /dev/null 2>&1
+			# - Remove the master zone file
+			rm /jls/${JAIL_NAME}/usr/local/etc/namedb/master/${HOST_NAME}.db > /dev/null 2>&1
 
-      # - Reload bind server
-      JAIL_ID_FILE=`ls -1 /var/run/jail_${JAIL_NAME}.id | head -1`
-      JAIL_ID=`cat ${JAIL_ID_FILE}`
-      echo -e "\n${YELL}Reloading the named service...${NRML}\n"
-      jexec ${JAIL_ID} service named reload > /dev/null 2>&1
-      if [ ${?} -ne 0 ]
-      then
-        echo -e "${LRED}WARNING:${NRML} Failed to reload named service in jail '${JAIL_NAME}'!\n"
-        exit 3
-      else
-        echo -e "${YELL}INFO:${NRML} Successfully updated bind9 DNS server in jail '${JAIL_NAME}'!\n"
-      fi
-    fi
-  fi
+			# - Reload bind server
+			JAIL_ID_FILE=`ls -1 /var/run/jail_${JAIL_NAME}.id | head -1`
+			JAIL_ID=`cat ${JAIL_ID_FILE}`
+			echo -e "\n${YELL}Reloading the named service...${NRML}\n"
+			jexec ${JAIL_ID} service named reload > /dev/null 2>&1
+			if [ ${?} -ne 0 ]
+			then
+				echo -e "${LRED}WARNING:${NRML} Failed to reload named service in jail '${JAIL_NAME}'!\n"
+				exit 4
+			else
+				echo -e "${YELL}INFO:${NRML} Successfully updated bind9 DNS server in jail '${JAIL_NAME}'!\n"
+			fi
+		fi
+	fi
 done
 
 if [ "${DNS_CACHE_SERVER_FOUND}" = "no" ]
 then  
-  echo -e "\n${LRED}ERROR:${NRML} No caching dns server found!\n"
-  exit 1
+	echo -e "\n${LRED}ERROR:${NRML} No caching dns server found!\n"
+	exit 5
 fi
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 6
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-hotdesk-add-user b/scripts/usr/local/sbin/fdo-hotdesk-add-user
--- a/scripts/usr/local/sbin/fdo-hotdesk-add-user
+++ b/scripts/usr/local/sbin/fdo-hotdesk-add-user
@@ -1,41 +1,129 @@
 #!/bin/sh
 
-# File name: fdo-hotdesk-add-user
-# Description: Shell script for adding hotdesk users
-# and adding their entry to /etc/exports 
-# and updating NIS (yp)
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-usage (){
-  echo ""
-  echo "Usage:   $0 user.name \"Display Name\""
-  echo "Example: $0 joe.bloggs \"Joe Bloggs\""
-  echo ""
-}
 
-if [ $# -ne 2 ]
-then
-  usage
-  exit 1
-fi
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
-USERNAME=$1
-DISPLAY_NAME=$2
+SCRIPT_NAME=`basename ${0}`
+USERNAME="{$1}"
+DISPLAY_NAME="${2}"
+NUM_MANDATORY_ARGS=2
 HOME_ZFS_NAME=`cat /usr/local/etc/fdo/hotdesk-home-zfs-name.conf`
 
-ps aux | grep "backupz"  | grep -v "grep backupz"
-if [ $? = 0 ]; then
-  echo ""
-  echo "ERROR: Backup is running, try again later!"
-  echo ""
-  exit 3
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Add a hotdesk user to a host configured for FDo NIS/NFS hotdesking."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} username display_name${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} joe.bloggs \"Joe Bloggs\"${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
 
+# Check that we are not currently running a backupz operation.
+ps aux | grep "backupz"  | grep -v "grep backupz"
+if [ ${?} -eq 0 ]; then
+	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\nAborting."
+	exit 3
+fi
+
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
 # Add new NIS user locally
-echo ""
+echo -e ""
 pw useradd -n ${USERNAME} -c "${DISPLAY_NAME}" -d /home/${USERNAME} -g users -s /bin/bash
-echo ""
+echo -e ""
 passwd ${USERNAME}
-echo ""
+echo -e ""
 
 # Create ZFS filesystem for home folder
 zfs create -o quota=50G ${HOME_ZFS_NAME}/${USERNAME}
@@ -45,16 +133,21 @@ chown -R ${USERNAME}:users /fdo-hotdesk-home/${USERNAME}
 
 # Add home folder to NFS exports
 echo "/fdo-hotdesk-home/${USERNAME} -maproot=root -network 192.168.10 -mask 255.255.0.0" >> /etc/exports
-echo ""
+echo -e ""
 service mountd reload
 
 # Add local user to NIS maps
 cd /var/yp
 cat /etc/master.passwd | egrep "^${USERNAME}:" >> master.passwd
 
-echo ""
+echo -e ""
 make
 
-echo ""
-echo "Operation complete!"
-echo ""
+echo -e "\n${LGRN}Operation complete!${NRML}\n"
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 4
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-hotdesk-remove-user b/scripts/usr/local/sbin/fdo-hotdesk-remove-user
--- a/scripts/usr/local/sbin/fdo-hotdesk-remove-user
+++ b/scripts/usr/local/sbin/fdo-hotdesk-remove-user
@@ -1,91 +1,178 @@
 #!/bin/sh
 
-# File name: fdo-hotdesk-remove-user 
-# Description: Shell script for removing hotdesk users
-# and removing their entry from /etc/exports
-# and updating NIS (yp)
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-usage (){
-  echo ""
-  echo "Usage:   $0 user.name"
-  echo "Example: $0 joe.bloggs"
-  echo ""
-  echo "Flags:   To ignore errors and force operation, prepend FORCE=yes to command."
-  echo "Example: FORCE=yes $0 joe.blogss"
-  echo ""
+
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+USERNAME="${1}"
+HOME_ZFS_NAME=`cat /usr/local/etc/fdo/hotdesk-home-zfs-name.conf`
+NUM_MANDATORY_ARGS=1
+FORCE_MODE="no"
+
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Remove a hotdesk user from a host configured for"
+	echo -e "             FDo NIS/NFS hotdesking."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} username [--force]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} joe.bloggs${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} joe.bloggs --force${NRML}"
+	echo -e ""
+	echo -e "${YELL}Options:${NRML}"
+	echo -e ""
+	echo -e "${YELL}--force  Ignore errors and force all removal steps.${NRML}"
+	echo -e ""
 }
 
-USERNAME=$1
-HOME_ZFS_NAME=`cat /usr/local/etc/fdo/hotdesk-home-zfs-name.conf`
 
-if [ $# -ne 1 ]; then
-  usage
-  exit 1
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--force)
+				FORCE_MODE-"yes"
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
 
-grep ${USERNAME} /etc/passwd > /dev/null
-if [ $? = 1 ]; then
-  echo ""
-  echo "ERROR: User does not exists, please check username!"
-  echo ""
-  if [ "${FORCE}" !=  "yes" ]
-  then
-    exit 2
-  fi
+# Check that we are not currently running a backupz operation.
+ps aux | grep "backupz"  | grep -v "grep backupz"
+if [ ${?} -eq 0 ]; then
+	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\nAborting."
+	exit 3
 fi
 
-ps aux | grep backupz  | grep -v "grep backupz"                                                                                                                 
-if [ $? = 0 ]; then                                                                                                                           
-  echo ""
-  echo "ERROR: Backup is running, try again later!"                                                                                                    
-  echo ""
-  exit 3
+# Check that user exists.
+grep -e "${USERNAME}" /etc/passwd > /dev/null
+if [ ${?} -ne 0 ]; then
+	echo -e "\n${LRED}ERROR:${NRML} User does not exists, please check username!\nAborting."
+	if [ "${FORCE_MODE}" !=  "yes" ]
+	then
+		exit 4
+	fi
 fi
 
-echo ""
-echo "Destroying the users' home filesystem..."
-echo ""
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Destroy the hotdesk users' home directory filesystem.
+echo -e "\n${YELL}Destroying the users' home filesystem...${NRML}\n"
 zfs destroy -r -p -f ${HOME_ZFS_NAME}/${USERNAME}
 if [ $? != 0 ]
 then
-  echo ""
-  echo "ERROR: Hotdesk user home folder not destroyed, please verify username!"
-  echo ""
-  if [ "${FORCE}" !=  "yes" ]
-  then
-    exit 4
-  fi
+	echo -e "\n${LRED}ERROR:${NRML} Hotdesk user home directory not destroyed, please verify username!\nAborting."
+	if [ "${FORCE_MODE}" !=  "yes" ]
+	then
+		exit 5
+	fi
 else
-  echo ""
-  echo "Hotdesk user home folder destroyed."
-  echo ""
+	echo -e "\n${YELL}Hotdesk user home folder destroyed.${NRML}\n"
 fi
 
 
-echo ""
-echo "Removing the user from the exports file..."
-echo ""
+echo -e "\n${YELL}Removing the user from the exports file...${NRML}\n"
 cp /etc/exports /etc/exports.previous
 sed "/${USERNAME} /d" /etc/exports > /etc/exports.next
 cat /etc/exports.next > /etc/exports
 
-echo ""
-echo "Restarting mountd..."
-echo ""
+echo -e "\n${YELL}Restarting mountd...${NRML}\n"
 service mountd reload
 
-echo ""
-echo "Removing the user from NIS..."
-echo ""
+echo "\n${YELL}Removing the user from NIS...${NRML}\n"
 cd /var/yp
 sed -i "" "/${USERNAME}/d" master.passwd
 make
 
-echo ""
-echo "Removing the user from system..."
-echo ""
+echo "\n${YELL}Removing the user from system...${NRML}\n"
 rmuser -y ${USERNAME}
 
-echo ""
-echo "Operation complete!"
-echo ""
+echo "\n${LGRN}Operation complete!${NRML}\n"
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 6
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-remote-desktops-stop-all b/scripts/usr/local/sbin/fdo-remote-desktops-stop-all
--- a/scripts/usr/local/sbin/fdo-remote-desktops-stop-all
+++ b/scripts/usr/local/sbin/fdo-remote-desktops-stop-all
@@ -1,10 +1,135 @@
 #!/bin/sh
 
-for i in `ls -1 /usr/local/etc/rc.d | cut -d* -f1 2> /dev/null`
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
+
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+NUM_MANDATORY_ARGS=0
+
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Stop all Remote Desktop instance services."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} [--help]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME}${NRML}"
+	echo -e ""
+	echo -e "${YELL}Options:${NRML}"
+	echo -e ""
+	echo -e "${YELL}--help  Display command usage.${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
 do
-  grep "VBoxHeadless -s" /usr/local/etc/rc.d/${i} > /dev/null 2>&1
-  if [ $? = 0 ] && [ "${i}" != "RemoteDesktop" ]
-  then
-    service ${i} stop
-  fi
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--help)
+				usage
+				exit
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
 done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
+fi
+
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Look inside all rc scripts in /usr/local/etc/rc.d for any that start VirtualBox RD instances, then stop them.
+for RC_SCRIPT in `ls -1 /usr/local/etc/rc.d | cut -d* -f1 2> /dev/null`
+do
+	grep "VBoxHeadless -s" /usr/local/etc/rc.d/${RC_SCRIPT} > /dev/null 2>&1
+	if [ ${?} = 0 ] && [ "${RC_SCRIPT}" != "RemoteDesktop" ]
+	then
+		service ${RC_SCRIPT} stop
+	fi
+done
+
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 3
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-scp-stress-test b/scripts/usr/local/sbin/fdo-scp-stress-test
--- a/scripts/usr/local/sbin/fdo-scp-stress-test
+++ b/scripts/usr/local/sbin/fdo-scp-stress-test
@@ -1,16 +1,151 @@
 #!/bin/sh
 
-USERNAME=${1}
-HOST=${2}
-LOCAL_DIR=${3}
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+LOCAL_DIR="${1}"
+REMOTE_USER="${2}"
+REMOTE_HOST="${3}"
+REMOTE_DIR="${4}"
+NUM_MANDATORY_ARGS=4
+REST_INTERVAL=20
+
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Stress test using scp to copy back and forth between two hosts."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} local_dir remote_user remote_host remote_dir [--interval=\"value\"]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} /tmp jimbob host1.example.net /tmp${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} ~ jane 192.168.10.3 ~ --interval=\"60\"${NRML}"
+	echo -e ""
+	echo -e "${YELL}Options:${NRML}"
+	echo -e ""
+	echo -e "${YELL}--interval  Rest interval [seconds] between scp (copy) operations.${NRML}"
+	echo -e ""
+	echo -e "${YELL}Note: Adding the local user/host ssh key to the remote user/host${NRML}"
+	echo -e "${YELL}      authorized_keys is recommended.${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--interval)
+				REST_INTERVAL="${OPTIONAL_ARG_VALUE}"
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
+fi
+
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Create payload file if it doesn't exist.
+if [ ! -f "${LOCAL_DIR}/100MB.file" ]
+then
+	echo -e "\n${YELL}Creating 100MB payload file at ${LOCAL_DIR}/100MB.file...${NRML}\n"
+	dd if=/dev/urandom of="${LOCAL_DIR}/100MB.file" bs=1M count=100
+fi
+
+# Loop infinetely, copying payload file back and forth between local and remote hosts.
 while [ 1 ]
 do
-  echo ""
-  echo "Start of loop"
-  echo ""
-  scp ${USERNAME}@${HOST}:~/100MB.file ${LOCAL_DIR} > /dev/null 2>&1
-  sleep 20
-  scp ${LOCAL_DIR}/100MB.file ${USERNAME}@192.168.10.1:~/ > /dev/null 2>&1
-  sleep 20
+	echo -e "\n\n${YELL}Start of stress test loop! (Ctrl-c to stop)${NRML}\n"
+	echo -e "\n${YELL}Copying 100MB file from local directory to remote directory...${NRML}\n"
+	scp "${LOCAL_DIR}/100MB.file" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/"
+	sleep ${REST_INTERVAL}
+	echo -e "\n${YELL}Copying 100MB file from remote directory to local directory...${NRML}\n"
+	scp "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/100MB.file" "${LOCAL_DIR}/"
+	sleep ${REST_INTERVAL}
 done
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 3
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-sip-add-user b/scripts/usr/local/sbin/fdo-sip-add-user
--- a/scripts/usr/local/sbin/fdo-sip-add-user
+++ b/scripts/usr/local/sbin/fdo-sip-add-user
@@ -1,17 +1,171 @@
 #!/bin/sh
 
-echo "Username:"
-read USERNAME
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-echo ""
-echo "Password:"
-read PASSWORD
 
-echo ""
-echo "Domain:"
-read  DOMAIN
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+USERNAME="${1}"
+DOMAIN_NAME="${2}"
+NUM_MANDATORY_ARGS=2
+PASSWORD=""
+SIP_MGMNT_CMD=opensipsctl
+
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Add a user to a FDo SIP jail service."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} username domain_name [--password=\"value\"]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} joe.bloggs example.net${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} jimbob example.net --password=\"letmein\"${NRML}"
+	echo -e ""
+	echo -e "${YELL}Options:${NRML}"
+	echo -e ""
+	echo -e "${YELL}--password  Specify a password, used for non-interactive / scripting.${NRML}"
+	echo -e "${YELL}            WARNING: the command may reveal password in history.${NRML}"
+	echo -e ""
+}
 
 
-opensipsctl add ${USERNAME} ${PASSWORD}
+##### PARSE ARGUMENTS ##########################################################
 
-opensipsctl db exec "update subscriber set domain  = '${DOMAIN}' where username like '${USERNAME}'"
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--password)
+				PASSWORD="${OPTIONAL_ARG_VALUE}"
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
+fi
+
+which "${SIP_MGMNT_CMD}" > /dev/null 2>&1
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The SIP server management command '${SIP_MGMNT_CMD}' does not exist!\nAborting."
+	exit 3
+fi
+
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# If password was not given as argument, prompt for it from user.
+while [ "${PASSWORD}" = "" ]
+do
+	echo -e "\n${LCYN}Enter password for the user: ${NRML}\c"
+	read PASSWORD_TEMP1
+	echo -e "${LCYN}Re-enter password          : ${NRML}\c"
+	read PASSWORD_TEMP2
+
+	if [ "${PASSWORD_TEMP1}" != "${PASSWORD_TEMP2}" ]
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Password mismatch, try again!\n"
+	elif [ "${PASSWORD_TEMP1}" = "" ]
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Password not entered, try again!\n"
+	else
+		PASSWORD=${PASSWORD_TEMP1}
+	fi
+done
+
+echo -e "\n${YELL}Adding SIP user...${NRML}\n"
+${SIP_MGMNT_CMD} add ${USERNAME} ${PASSWORD}
+if [ ${?} -eq 0 ]
+then
+	echo -e "\n${YELL}Setting domain for SIP user...${NRML}\n"
+	${SIP_MGMNT_CMD} db exec "update subscriber set domain  = '${DOMAIN_NAME}' where username like '${USERNAME}'"
+	if [ ${?} -eq 0 ]
+	then
+		echo -e "\n${LGRN}Operation completed!${NRML}\n"
+	else
+		ERROR_COUNT=$(( ${ERROR_COUNT} + 1 ))
+	fi
+else
+	ERROR_COUNT=$(( ${ERROR_COUNT} + 1 ))
+fi
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 4
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-storage-perf-test b/scripts/usr/local/sbin/fdo-storage-perf-test
--- a/scripts/usr/local/sbin/fdo-storage-perf-test
+++ b/scripts/usr/local/sbin/fdo-storage-perf-test
@@ -1,30 +1,143 @@
 #!/bin/sh
 
-if [ $# -ne 1 ]
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
+
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+POOL="${1}"
+NUM_MANDATORY_ARGS=1
+
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Perform a storage performance test on a specified ZFS pool."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} pool_name${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} backup${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--option1)
+				OPTION1="${OPTIONAL_ARG_VALUE}"
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
 then
-  echo ""
-  echo "Usage:   ${0} POOL_NAME"
-  echo "Example: ${0} data"
-  echo "Example: ${0} backup"
-  echo ""
-  exit 1
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
 
-POOL_NAME=$1
-
-zpool list ${POOL_NAME} > /dev/null 2>&1
-if [ $? -ne 0 ]
+POOL_ATTRIBUTES=`zpool list -H | egrep "^${POOL}	" 2> /dev/null`
+if [ ${?} -ne 0 ]
 then
-  echo ""
-  echo "Pool does not seem to exist, check the pool name."
-  echo ""
-  exit 2
+	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported."
+	exit 3
 fi
 
-POOL_MOUNTPOINT=`zfs get mountpoint backup | tail -n +2 | awk '{print $3}'`
-TEST_FILE=${POOL_MOUNTPOINT}/test.file
+POOL_HEALTH=`echo ${POOL_ATTRIBUTES} | awk '{print $9}'`
+if [ "${POOL_HEALTH}" != "ONLINE" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy."
+	exit 4
+fi
 
-echo ""
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+POOL_MOUNTPOINT=`zfs get -H mountpoint backup | awk '{print $3}'`
+TEST_FILE="${POOL_MOUNTPOINT}/test.file"
+
+echo -e ""
 time sh -c "dd if=/dev/urandom of=${TEST_FILE} bs=8k count=100000 && sync"
 rm ${TEST_FILE}
-echo ""
+echo -e ""
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 5
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/fdo-webdav-create-user-folder b/scripts/usr/local/sbin/fdo-webdav-create-user-folder
--- a/scripts/usr/local/sbin/fdo-webdav-create-user-folder
+++ b/scripts/usr/local/sbin/fdo-webdav-create-user-folder
@@ -1,33 +1,141 @@
 #!/bin/sh
 
-SHORT_ORG_NAME=$1
-USERID=$2
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-WEBDAV_ROOT_MOUNTPOINT=`cat /usr/local/etc/fdo/webdav_root_mountpoint.conf`
+
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+HUB_NAME="${1}"
+USERNAME="${2}"
+NUM_MANDATORY_ARGS=2
 WEBDAV_ROOT_FS=`cat /usr/local/etc/fdo/webdav_root_fs.conf`
+WEBDAV_ROOT_MOUNTPOINT=`cat /usr/local/etc/fdo/webdav_root_mountpoint.conf`
+WEBDAV_UID=`cat /usr/local/etc/fdo/webdav_userid.conf`
+WEBDAV_GID=`cat /usr/local/etc/fdo/webdav_groupid.conf`
 
-if [ $# -ne 2 ]
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Create a files user folder."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} hub_name username${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} acme-aus wiley.coyote${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
 then
-    echo ""
-    echo "Usage:   ${0} SHORT_ORG_NAME USERID"
-    echo "Example: ${0} ffs joe.blogs"
-    exit 1 
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
 
+zfs list ${WEBDAV_ROOT_FS}/${HUB_NAME}/users/${USERNAME} > /dev/null 2>&1
+if [ ${?} -eq 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The referenced files user folder already exists!\nAborting."
+	exit 3
+fi
+
+# Check that we are not currently running a backupz operation.
 ps aux | grep "backupz"  | grep -v "grep backupz"
-if [ $? -eq 0 ]
-then
-  echo ""
-  echo "ERROR: backupz is running, try again later!"
-  exit 2 
+if [ ${?} -eq 0 ]; then
+	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\nAborting."
+	exit 3
 fi
 
-zfs create -o casesensitivity=insensitive -o mountpoint=${WEBDAV_ROOT_MOUNTPOINT}/${SHORT_ORG_NAME}/users/${USERID} ${WEBDAV_ROOT_FS}/${SHORT_ORG_NAME}/users/${USERID}
 
-zfs set quota=5G data/dav/${SHORT_ORG_NAME}/users/${USERID}
+##### FUNCTIONS ################################################################
 
-chown -R 81:81 ${WEBDAV_ROOT_MOUNTPOINT}/${SHORT_ORG_NAME}/users/${USERID}
 
-echo ""
-echo "Successfully created the user folder for ${USERID}!"
 
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Create the ZFS filesystem of the files user folder.
+zfs create -o casesensitivity=insensitive -o mountpoint=${WEBDAV_ROOT_MOUNTPOINT}/${HUB_NAME}/users/${USERNAME} ${WEBDAV_ROOT_FS}/${HUB_NAME}/users/${USERNAME}
+
+# Change ownership of the files user folder mountpoint.
+chown -R ${WEBDAV_UID}:${WEBDAV_GID} ${WEBDAV_ROOT_MOUNTPOINT}/${HUB_NAME}/users/${USERNAME}
+
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 4
+fi
diff --git a/scripts/usr/local/sbin/fdo-webdav-edit b/scripts/usr/local/sbin/fdo-webdav-edit
--- a/scripts/usr/local/sbin/fdo-webdav-edit
+++ b/scripts/usr/local/sbin/fdo-webdav-edit
@@ -1,3 +1,189 @@
 #!/bin/sh
 
-vi /usr/local/etc/apache22/extra/httpd-vhosts.conf
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
+
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
+
+SCRIPT_NAME=`basename ${0}`
+NUM_MANDATORY_ARGS=0
+WEBDAV_CONFIG_ROOT="/usr/local/etc/webdav-sites"
+WEBDAV_SERVICE=apache24
+DIALOG_OUT_FILE="/tmp/fdo-webdav-edit.dialog.answer"
+
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
+
+CARRIAGE_RETURN="
+"
+
+##### COMMAND USAGE INFO #######################################################
+
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
+
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Quick way to edit and reload a webdav service config file."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} [--help]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME}${NRML}"
+	echo -e ""
+	echo -e "${YELL}Options:${NRML}"
+	echo -e ""
+	echo -e "${YELL}--help    Display command usage.${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--help)
+				usage
+				exit
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
+fi
+
+if [ ! -e "${WEBDAV_CONFIG_ROOT}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The webdav config root '${WEBDAV_CONFIG_ROOT}'\ndoes not exist!\nAborting."
+	usage
+	exit 3
+fi
+
+
+##### FUNCTIONS ################################################################
+
+question_yes_no ()
+{
+
+	LOOP=1
+
+	while [ ${LOOP} = 1 ]
+		do
+		echo -e "${LCYN}${1} (yes/no): ${NRML}\c"
+		read ANSWER
+		if [ "${ANSWER}" = "yes" ] || [ "${ANSWER}" = "no" ]
+		then
+			LOOP=0
+		fi
+		echo ""
+	done
+
+}
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# Get site names from site config directory.
+SITES_AVAILABLE=`ls -1 ${WEBDAV_CONFIG_ROOT}/ | sort`
+NUM_SITES_AVAILABLE=`echo ${SITES_AVAILABLE} | wc -w`
+if [ ${NUM_SITES_AVAILABLE} -lt 1 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The webdav config root '${WEBDAV_CONFIG_ROOT}'\ndoes not contain any site configs!\nAborting."
+	exit 4
+fi
+SITE=""
+if [ ${NUM_SITES_AVAILABLE} -lt 2 ]
+then
+	SITE="${SITES_AVAILABLE}"
+fi
+# If more than one site, prompt user to select a site from available site config files.
+while [ "${SITE}" = "" ]
+do
+	dialog --no-cancel --no-items --menu "Select a site:" 12 60 10 ${SITES_AVAILABLE} 2> ${DIALOG_OUT_FILE}
+	SITE_TEMP=`cat ${DIALOG_OUT_FILE}`
+	echo -e "\n\n"
+	question_yes_no "You have selected '${SITE_TEMP}' as the site to edit.\nIs this correct?"
+	if [ "${ANSWER}" = "yes" ]
+	then
+		SITE="${SITE_TEMP}"
+	fi
+done
+
+WEBDAV_CONFIG_FILE="${WEBDAV_CONFIG_ROOT}/${SITE}"
+
+# Open the webdav server config file in users preferred editor.
+${EDITOR} ${WEBDAV_CONFIG_FILE}
+
+question_yes_no "\nWould you like to reload the service to pick up any changes now?"
+if [ "${ANSWER}" = "yes" ]
+then
+	service ${WEBDAV_SERVICE} restart
+fi
+
+echo -e ""
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 5
+fi
+
+################################################################################
diff --git a/scripts/usr/local/sbin/jlogin b/scripts/usr/local/sbin/jlogin
--- a/scripts/usr/local/sbin/jlogin
+++ b/scripts/usr/local/sbin/jlogin
@@ -1,25 +1,157 @@
 #!/bin/sh
 
-[ -z "$1" ] && echo "No jail specified." && exit 1;
-[ -z "$2" ] && loginShell="/usr/local/bin/bash" || loginShell="$2"
+# Copyright (c) 2016 Euan Thoms <euan@potensol.com>.
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions
+# are met:
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-jName=$1;
 
-jIdFile=`ls -1 /var/run/jail_*.id | grep jail_${jName} | head -1`
+##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
-if [ "${jIdFile}" = "" ]; then echo "No jail found matching '${jName}'." ; exit 1; fi
+SCRIPT_NAME=`basename ${0}`
+JAIL_NAME="${1}"
+NUM_MANDATORY_ARGS=1
+LOGIN_SHELL="/usr/local/bin/bash"
 
-jId=`cat ${jIdFile}`
+TERM="xterm"
+LRED="\033[1;31m"
+LGRN="\033[1;32m"
+LBLU="\033[1;34m"
+LCYN="\033[1;36m"
+CYAN="\033[0;36m"
+YELL="\033[1;33m"
+ORNG="\033[0;33m"
+GREY="\033[0;37m"
+DGRY="\033[1;30m"
+NRML="\033[0;00m"
 
-jRealName=`echo ${jIdFile} | sed "s|^/var/run/jail_||" | sed "s|.id||"`
+CARRIAGE_RETURN="
+"
 
-[ -z "${jId}" ] && echo "No such jail name ${jName}!" && exit 1;
+##### COMMAND USAGE INFO #######################################################
 
-echo "Logging in to ${jRealName}"
+usage ()
+{
+	if [ "${NO_DISPLAY_USAGE}" = "yes" ]
+	then
+		return 1
+	fi
 
-if [ "$loginShell" = "/usr/local/bin/bash" ]
+	echo -e ""
+	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
+	echo -e ""
+	echo -e "${YELL}Description:${NRML} Login to a shell inside a jail."
+	echo -e ""
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} jail_name [--shell=\"value\"]${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} ldap${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} files --shell=\"/bin/csh\"${NRML}"
+	echo -e ""
+	echo -e "${YELL}Options:${NRML}"
+	echo -e ""
+	echo -e "${YELL}--shell  Specify the login shell (full path).${NRML}"
+	echo -e ""
+}
+
+
+##### PARSE ARGUMENTS ##########################################################
+
+ARG_INDEX=1
+for ARG in "${@}"
+do
+	if [ ${ARG_INDEX} -gt ${NUM_MANDATORY_ARGS} ]
+	then
+		OPTIONAL_ARG_NAME=`echo ${ARG} | cut -d= -f1`
+		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
+		case ${OPTIONAL_ARG_NAME} in
+			--shell)
+				LOGIN_SHELL="${OPTIONAL_ARG_VALUE}"
+				;;
+			*)
+				echo -e "\n${LRED}ERROR:${NRML} Invalid argument!\nAborting."
+				usage
+				exit 1
+				;;
+		esac
+	fi
+
+	ARG_INDEX=$(( ${ARG_INDEX} + 1 ))
+
+done
+
+
+##### SANITY TESTS #############################################################
+
+if [ ${#} -lt ${NUM_MANDATORY_ARGS} ]
 then
-  jexec ${jId} ${loginShell} -l
-else
-  jexec ${jId} ${loginShell}
+	echo -e "\n${LRED}ERROR:${NRML} Incorrect number of arguments!\nAborting."
+	usage
+	exit 2
 fi
+
+
+##### FUNCTIONS ################################################################
+
+
+
+################################################################################
+
+
+##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
+
+# start here
+JID_FILE=`ls -1 /var/run/jail_*.id | grep jail_${JAIL_NAME} | head -1`
+
+if [ "${JID_FILE}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} No jail found matching '${JAIL_NAME}'!\nAborting."
+	usage
+	exit 3
+fi
+
+JID=`cat ${JID_FILE}`
+
+if [ "${JID}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} No jid found in '${JID_FILE}'!\nAborting."
+	usage
+	exit 4
+fi
+
+REAL_JAIL_NAME=`echo ${JID_FILE} | sed "s|^/var/run/jail_||" | sed "s|.id||"`
+
+
+echo -e "\n${YELL}Logging in to ${REAL_JAIL_NAME}...${NRML}\n"
+
+if [ "${LOGIN_SHELL}" = "/usr/local/bin/bash" ]
+then
+  jexec ${JID} ${LOGIN_SHELL} -l
+else
+  jexec ${JID} ${LOGIN_SHELL}
+fi
+
+if [ ${ERROR_COUNT} -gt 0 ]
+then
+	exit 5
+fi
+
+################################################################################
