scripts: fdo-dns_cache-*; add extra argument validity tests, improve scripting style consistency.

diff --git a/scripts/usr/local/sbin/fdo-dns_cache-add-hostname b/scripts/usr/local/sbin/fdo-dns_cache-add-hostname
--- a/scripts/usr/local/sbin/fdo-dns_cache-add-hostname
+++ b/scripts/usr/local/sbin/fdo-dns_cache-add-hostname
@@ -125,12 +125,94 @@ question_yes_no ()
 	done
 }
 
+test_valid_inet_address ()
+{
+
+	TEST_CASE="${1}"
+
+	VALID_INET_ADDRESS="yes"
+
+	if [ "${TEST_CASE}" = "" ]
+	then
+		VALID_INET_ADDRESS="no"
+		return 1
+	fi
+
+	IS_SYNTAX_OK=`echo "${TEST_CASE}" | sed "s/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}$//" | wc -L`
+	if [ ${IS_SYNTAX_OK}  -ne 0 ]
+	then
+		VALID_INET_ADDRESS="no"
+		return 2
+	fi
+
+	NO_ZEROS_IN_FRONT=`echo "${TEST_CASE}" | sed "s/\.0[0-9]//" | sed "s/^0//"`
+	if [ "${NO_ZEROS_IN_FRONT}" != "${TEST_CASE}" ]
+	then
+		VALID_INET_ADDRESS="no"
+		return 3
+	fi
+
+	ONE=`echo "${TEST_CASE}" | cut -d. -f1`
+	TWO=`echo "${TEST_CASE}" | cut -d. -f2`
+	THREE=`echo "${TEST_CASE}" | cut -d. -f3`
+	FOUR=`echo "${TEST_CASE}" | cut -d. -f4`
+
+	if [ ${ONE} -gt 255 ] || [ ${TWO} -gt 255 ] || [ ${THREE} -gt 255 ] || [ ${FOUR} -gt 255 ]
+	then
+		VALID_INET_ADDRESS="no"
+		return 4
+	fi
+
+}
+
+test_valid_fqhn ()
+{
+
+	TEST_CASE="${1}"
+
+	VALID_FQHN="yes"
+
+	if [ "${TEST_CASE}" = "" ]
+	then
+		VALID_FQHN="no"
+		return 1
+	fi
+
+	IS_SYNTAX_OK=`echo "${TEST_CASE}" | sed -r "s/^((([a-zA-Z0-9]+[\-])*[a-zA-Z0-9]+)+\.)+[a-zA-Z0-9]+//" | wc -L`
+	if [ ${IS_SYNTAX_OK}  -ne 0 ]
+	then
+		VALID_FQHN="no"
+		return 2
+	fi
+
+}
+
 ################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
+
+# Check that the hostname is valid.
+test_valid_fqhn  "${HOST_NAME}"
+if [ "${VALID_FQHN}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The hostname '${HOST_NAME}' is invalid!"
+	echo -e "       It must only contain letters, numbers, periods and hyphens."
+	echo -e "       It must not begin or end with a hyphen or a period."
+	echo -e "       Aborting.\n"
+	exit 3
+fi
+
+# Test if ip_address is valid
+test_valid_inet_address "${HOST_IP}"
+if [ "${VALID_INET_ADDRESS}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} IP address is invalid!"
+	echo -e "       Aborting.\n"
+	exit 4
+fi
 
 # Iterate through all jails...
 for JAIL_NAME in `ls -1 /jls | cut -d/ -f1 | egrep -v "template"`
@@ -149,11 +231,12 @@ do
 			cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^zone \"${HOST_NAME}\"" > /dev/null 2>&1
 			if [ ${?} -eq 0 ]
 			then
-				echo -e "\n${ORNG}WARNING:${NRML} The record for hostname ${HOST_NAME} already exists!\n"
-				exit 3
+				echo -e "\n${LRED}ERROR:${NRML} The record for hostname '${HOST_NAME}' already exists!"
+				echo -e "       Aborting.\n"
+				exit 5
 			fi
 
-			# Since it doesn't already exist, let's add a zone for our new hostname record:
+			# Since it does not already exist, let's add a zone for our new hostname record:
 
 			# - Add zone entry in named.conf
 			echo "zone \"${HOST_NAME}\" { type master; file \"/usr/local/etc/namedb/master/${HOST_NAME}.db\"; };" >> /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf
@@ -176,11 +259,12 @@ do
 			jexec ${JAIL_ID} service named reload > /dev/null 2>&1
 			if [ ${?} -ne 0 ]
 			then
-				echo -e "${LRED}WARNING:${NRML} Failed to reload named service in jail '${JAIL_NAME}'!\n"
-				exit 4
+				echo -e "\n${ORNG}WARNING:${NRML} Failed to reload named service in jail '${JAIL_NAME}'!\n"
 			else
 				echo -e "${YELL}INFO:${NRML} Successfully updated bind9 DNS server in jail '${JAIL_NAME}'!\n"
 			fi
+
+			# Update configuration in the local repo and if interactive mode then push to remote repo
 			if [ "${IS_INTERACTIVE}" = "no" ]
 			then
 				echo -e "\n${FDO_SERVER_SCRIPT} update-config /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf ...\n"
@@ -204,13 +288,13 @@ done
 if [ "${DNS_CACHE_SERVER_FOUND}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} No caching dns server found!\n       Aborting.\n"
-	exit 5
+	exit 6
 fi
 
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 6
+	exit 7
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-dns_cache-remove-hostname b/scripts/usr/local/sbin/fdo-dns_cache-remove-hostname
--- a/scripts/usr/local/sbin/fdo-dns_cache-remove-hostname
+++ b/scripts/usr/local/sbin/fdo-dns_cache-remove-hostname
@@ -124,12 +124,45 @@ question_yes_no ()
 	done
 }
 
+test_valid_fqhn ()
+{
+
+	TEST_CASE="${1}"
+
+	VALID_FQHN="yes"
+
+	if [ "${TEST_CASE}" = "" ]
+	then
+		VALID_FQHN="no"
+		return 1
+	fi
+
+	IS_SYNTAX_OK=`echo "${TEST_CASE}" | sed -r "s/^((([a-zA-Z0-9]+[\-])*[a-zA-Z0-9]+)+\.)+[a-zA-Z0-9]+//" | wc -L`
+	if [ ${IS_SYNTAX_OK}  -ne 0 ]
+	then
+		VALID_FQHN="no"
+		return 2
+	fi
+
+}
+
 ################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
+
+# Check that the hostname is valid.
+test_valid_fqhn  "${HOST_NAME}"
+if [ "${VALID_FQHN}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The hostname '${HOST_NAME}' is invalid!"
+	echo -e "       It must only contain letters, numbers, periods and hyphens."
+	echo -e "       It must not begin or end with a hyphen or a period."
+	echo -e "       Aborting.\n"
+	exit 3
+fi
 
 # Iterate through all jails...
 for JAIL_NAME in `ls -1 /jls | cut -d/ -f1 | egrep -v "template"`
@@ -148,8 +181,9 @@ do
 			cat /jls/${JAIL_NAME}/usr/local/etc/namedb/named.conf | egrep "^zone \"${HOST_NAME}\"" > /dev/null 2>&1
 			if [ ${?} -ne 0 ]
 			then
-				echo -e "\n${ORNG}WARNING:${NRML} The record for hostname ${HOST_NAME} doesn't exist!\n"
-				exit 3
+				echo -e "\n${LRED}ERROR:${NRML} The record for hostname ${HOST_NAME} does not exist!"
+				echo -e "       Aborting.\n"
+				exit 4
 			fi
 
 			# Hostname record exists, so now let's remove the zone for the hostname record:
@@ -167,8 +201,7 @@ do
 			jexec ${JAIL_ID} service named reload > /dev/null 2>&1
 			if [ ${?} -ne 0 ]
 			then
-				echo -e "${LRED}WARNING:${NRML} Failed to reload named service in jail '${JAIL_NAME}'!\n"
-				exit 4
+				echo -e "\n${ORNG}WARNING:${NRML} Failed to reload named service in jail '${JAIL_NAME}'!\n"
 			else
 				echo -e "${YELL}INFO:${NRML} Successfully updated bind9 DNS server in jail '${JAIL_NAME}'!\n"
 			fi
