script 'fdo-ldap-edit': add support for running from the host or within jail.

diff --git a/scripts/usr/local/sbin/fdo-ldap-edit b/scripts/usr/local/sbin/fdo-ldap-edit
--- a/scripts/usr/local/sbin/fdo-ldap-edit
+++ b/scripts/usr/local/sbin/fdo-ldap-edit
@@ -32,6 +32,9 @@ LDAP_EDIT_CMD=ldapvi
 LDAP_SERVER_HOST=localhost
 LDAP_MGR_DN_LOOKUP_FILE="/usr/local/etc/fdo/ldap-manager-dn.conf"
 LDAP_MGR_DN=`cat "${LDAP_MGR_DN_LOOKUP_FILE}"`
+CONFIG_FILE="/usr/local/etc/openldap/slapd.conf"
+RECIPE_NAME="ldap_provider"
+DIALOG_OUT_FILE="/tmp/${SCRIPT_NAME}.dialog.answer"
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -108,17 +111,10 @@ then
 	exit 2
 fi
 
-which "${LDAP_EDIT_CMD}" > /dev/null 2>&1
-if [ ${?} -ne 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The LDAP edit command '${LDAP_EDIT_CMD}' does not exist!\n       Aborting.\n"
-	exit 3
-fi
-
 if [ "${LDAP_MGR_DN}" = "" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The LDAP manager DN specified in the lookup file\n'${LDAP_MGR_DN_LOOKUP_FILE}' is not valid!\n       Aborting.\n"
-	exit 4
+	exit 3
 fi
 
 ##### FUNCTIONS ################################################################
@@ -141,18 +137,111 @@ question_yes_no ()
 
 }
 
+test_if_host ()
+{
+	procstat 0 > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		IS_HOST=yes
+	else
+		IS_HOST=no
+	fi
+}
+
+find_jails_from_recipe_name ()
+{
+	FIND_RECIPE_NAME="${1}"
+	FOUND_RECIPE_JAILS=""
+	for TEST_JAIL_NAME in `ls -1 /jls | cut -d/ -f1`
+	do
+		if [ -f "/jls/${TEST_JAIL_NAME}/.fdo-jail-recipe.inf" ]
+		then
+			TEST_RECIPE_NAME=`cat /jls/${TEST_JAIL_NAME}/.fdo-jail-recipe.inf`
+			if [ "${TEST_RECIPE_NAME}" = "${FIND_RECIPE_NAME}" ]
+			then
+				if [ "${FOUND_RECIPE_JAILS}" = "" ]
+				then
+					FOUND_RECIPE_JAILS="${TEST_JAIL_NAME}"
+				else
+					FOUND_RECIPE_JAILS="${FOUND_RECIPE_JAILS} ${TEST_JAIL_NAME}"
+				fi
+			fi
+		fi
+	done
+
+}
+
+get_jail_id_from_name ()
+{
+	# ${1} is jail name
+
+	JAIL_ID_FILE=`ls -1 /var/run/jail_${1}.id 2> /dev/null | head -1`
+	if [ "${JAIL_ID_FILE}" = "" ] 
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Could not identify jail id from jail name.\n"
+		JAIL_ID=-1
+		return 1
+	fi
+	JAIL_ID=`cat ${JAIL_ID_FILE}`
+
+}
+
 ################################################################################
 
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
+JAIL_NAME=""
+CMD_PREFIX=""
 
-${LDAP_EDIT_CMD} -Z -h ${LDAP_SERVER_HOST} -D "${LDAP_MGR_DN}"
+test_if_host
+
+if [ "${IS_HOST}" = "yes" ]
+then
+	# Let's try to find the jail
+	find_jails_from_recipe_name ${RECIPE_NAME}
+	NUM_FOUND_JAILS=`echo ${FOUND_RECIPE_JAILS} | wc -w`
+	if [ ${NUM_FOUND_JAILS} -lt 1 ]
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Unable to find a '${RECIPE_NAME}' recipe jail!\n       Aborting.\n"
+		usage
+		exit 4
+	fi
+	if [ ${NUM_FOUND_JAILS} -lt 2 ]
+	then
+		JAIL_NAME=${FOUND_RECIPE_JAILS}
+	else
+		SELECT_JAIL_PROMPT="Select the LDAP provider jail to edit:"
+		while [ "${JAIL_NAME}" = "" ]
+		do
+			dialog --no-items --no-cancel --menu "${SELECT_JAIL_PROMPT}" 12 40 10 ${FOUND_RECIPE_JAILS} 2> ${DIALOG_OUT_FILE}
+			JAIL_NAME_TEMP=`cat ${DIALOG_OUT_FILE}`
+			echo -e "\n"
+			question_yes_no "\nYou have selected '${JAIL_NAME_TEMP}' as the LDAP provider jail to edit.\nIs this correct?"
+			if [ "${ANSWER}" = "yes" ]
+			then
+				JAIL_NAME="${JAIL_NAME_TEMP}"
+			fi
+		done
+	fi
+	CONFIG_FILE="/jls/${JAIL_NAME}${CONFIG_FILE}"
+	get_jail_id_from_name ${JAIL_NAME}
+	CMD_PREFIX="jexec ${JAIL_ID}"  
+fi
+
+${CMD_PREFIX} which "${LDAP_EDIT_CMD}" > /dev/null 2>&1
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The LDAP edit command '${LDAP_EDIT_CMD}' does not exist!\n       Aborting.\n"
+	exit 5
+fi
+
+${CMD_PREFIX} ${LDAP_EDIT_CMD} -Z -h ${LDAP_SERVER_HOST} -D "${LDAP_MGR_DN}"
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 5
+	exit 6
 fi
 
 ################################################################################
