script 'fdo-sshfs-add-connection': move check for unsaved registered host config files to better placement.

diff --git a/scripts/usr/local/sbin/fdo-sshfs-add-connection b/scripts/usr/local/sbin/fdo-sshfs-add-connection
--- a/scripts/usr/local/sbin/fdo-sshfs-add-connection
+++ b/scripts/usr/local/sbin/fdo-sshfs-add-connection
@@ -369,17 +369,6 @@ then
 	exit 1
 fi
 
-# Check for unsaved registered host config files.
-echo -e "\n${YELL}Now we need to check if there are any unsaved changes to this hosts registered\nconfig files...${NRML}\n"
-${FDO_SERVER_SCRIPT} check-configs --script > /dev/null 2>&1
-if [ ${?} -gt 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} One or more host config files are not updated in the repo."
-	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} check-configs${NRML}' subcommand to see what's out-of-date."
-	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} update-config${NRML}' subcommannd to keep the repo up-to-date.\n       Aborting.\n"
-	exit 1
-fi
-
 # Check that the host.conf file exists.
 if [ ! -e "${HOST_CONF_PATH}" ]
 then
@@ -420,6 +409,17 @@ if [ ${?} -ne 0 ] || [ "${TEST_UCL}" = "null" ] || [ "${TEST_UCL}" = "" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} Failed to access the config file '${SSHFS_DAEMON_CONF_PATH}'!\n       Aborting.\n"
 	exit 2
+fi
+
+# Check for unsaved registered host config files.
+echo -e "\n${YELL}Now we need to check if there are any unsaved changes to this hosts registered\nconfig files...${NRML}\n"
+${FDO_SERVER_SCRIPT} check-configs --script > /dev/null 2>&1
+if [ ${?} -gt 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} One or more host config files are not updated in the repo."
+	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} check-configs${NRML}' subcommand to see what's out-of-date."
+	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} update-config${NRML}' subcommannd to keep the repo up-to-date.\n       Aborting.\n"
+	exit 1
 fi
 
 # Check that the remote_user is valid.
