scripts 'fdo-file_server-check|set-user|shared-folder-quota': fix premature santity test by putting it after required variable loading.

diff --git a/scripts/usr/local/sbin/fdo-file_server-check-shared-folder-quota b/scripts/usr/local/sbin/fdo-file_server-check-shared-folder-quota
--- a/scripts/usr/local/sbin/fdo-file_server-check-shared-folder-quota
+++ b/scripts/usr/local/sbin/fdo-file_server-check-shared-folder-quota
@@ -153,13 +153,6 @@ then
 	exit 1
 fi
 
-zfs list ${WEBDAV_ROOT_FS}/${SITE_NAME}/shares/${SHARE_PATH} > /dev/null 2>&1
-if [ ${?} -ne 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The referenced file_server share does not exist!\n       Aborting.\n"
-	exit 1
-fi
-
 
 ##### MAIN EXECUTION THREAD ####################################################
 
@@ -192,6 +185,14 @@ ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 if [ "${WEBDAV_ROOT_FS}" = "" ] || [ "${WEBDAV_ROOT_FS}" = "null" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The WebDAV root filesystem specified in the config file\n       '${RECIPE_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+# Check if the shared folder filesystem exists.
+zfs list ${WEBDAV_ROOT_FS}/${SITE_NAME}/shares/${SHARE_PATH} > /dev/null 2>&1
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The referenced file_server share does not exist!\n       Aborting.\n"
 	exit 1
 fi
 
diff --git a/scripts/usr/local/sbin/fdo-file_server-set-user-folder-quota b/scripts/usr/local/sbin/fdo-file_server-set-user-folder-quota
--- a/scripts/usr/local/sbin/fdo-file_server-set-user-folder-quota
+++ b/scripts/usr/local/sbin/fdo-file_server-set-user-folder-quota
@@ -154,13 +154,6 @@ then
 	exit 1
 fi
 
-zfs list ${WEBDAV_ROOT_FS}/${SITE_NAME}/users/${USERNAME} > /dev/null 2>&1
-if [ ${?} -ne 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The referenced file_server user folder does not exist!\n       Aborting.\n"
-	exit 1
-fi
-
 
 ##### MAIN EXECUTION THREAD ####################################################
 
@@ -196,7 +189,15 @@ then
 	exit 1
 fi
 
-# Display the quota of the ZFS filesystem of the file_server user folder.
+# Check if the user folder filesystem exists.
+zfs list ${WEBDAV_ROOT_FS}/${SITE_NAME}/users/${USERNAME} > /dev/null 2>&1
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The referenced file_server user folder does not exist!\n       Aborting.\n"
+	exit 1
+fi
+
+# Set the quota of the ZFS filesystem of the file_server user folder.
 zfs set quota=${QUOTA} ${WEBDAV_ROOT_FS}/${SITE_NAME}/users/${USERNAME}
 ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
