scripts 'fdo-pf|ppp-add|remove-port-forward-rule': Add extra failure tests, make robust and ask to reload service.

diff --git a/scripts/usr/local/sbin/fdo-pf-add-port-forward-rule b/scripts/usr/local/sbin/fdo-pf-add-port-forward-rule
--- a/scripts/usr/local/sbin/fdo-pf-add-port-forward-rule
+++ b/scripts/usr/local/sbin/fdo-pf-add-port-forward-rule
@@ -109,7 +109,7 @@ done
 
 ##### FUNCTIONS ################################################################
 
-# source readee function
+# source readee function.
 . /usr/local/bin/fdo-readee
 
 question_yes_no ()
@@ -250,7 +250,7 @@ then
 	exit 1
 fi
 
-# Test if rule_name is valid
+# Test if rule_name is valid.
 test_valid_rule_name "${RULE_NAME}"
 if [ "${VALID_RULE_NAME}" = "no" ]
 then
@@ -258,7 +258,7 @@ then
 	exit 1
 fi
 
-# Test if rule_name already exists
+# Test if rule_name already exists.
 cat ${PF_CONF_PATH} | egrep "${RULE_NAME}_ip =" > /dev/null 2>&1
 if [ ${?} -eq 0 ]
 then
@@ -266,7 +266,7 @@ then
 	exit 1
 fi
 
-# Test if local_ip_address is valid
+# Test if local_ip_address is valid.
 test_valid_inet_address "${LOCAL_IP}"
 if [ "${VALID_INET_ADDRESS}" = "no" ]
 then
@@ -274,7 +274,7 @@ then
 	exit 1
 fi
 
-# Test if tcp_ports is valid
+# Test if tcp_ports is valid.
 test_valid_port_list "${TCP_PORTS}"
 if [ "${VALID_PORT_LIST}" = "no" ]
 then
@@ -282,7 +282,7 @@ then
 	exit 1
 fi
 
-# Test if udp_ports is valid
+# Test if udp_ports is valid.
 test_valid_port_list "${UDP_PORTS}"
 if [ "${VALID_PORT_LIST}" = "no" ]
 then
@@ -290,7 +290,7 @@ then
 	exit 1
 fi
 
-# Test if both tcp_ports and udp_ports are 'none'
+# Test if both tcp_ports and udp_ports are 'none'.
 if [ "${TCP_PORTS}" = "none" ] && [ "${UDP_PORTS}" = "none" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} No ports specified!\n"
@@ -302,7 +302,7 @@ fi
 
 ERROR_COUNT=0
 
-# Prepare macro and rule definitions as variables
+# Prepare macro and rule definitions as variables.
 IP_MACRO_DEF="\\${CARRIAGE_RETURN}${RULE_NAME}_ip = \"${LOCAL_IP}\""
 if [ "${TCP_PORTS}" = "none" ]
 then
@@ -319,34 +319,57 @@ else
 	UDP_RULES_DEF="\\${CARRIAGE_RETURN}rdr on \$ext_if proto udp from any to any port \$${RULE_NAME}_udp_ports -> \$${RULE_NAME}_ip"
 fi
 
-# Add new port foward rule macros to pf config file
-sed -i "" "s|\(^[#]* PORT FORWARD RULES MACROS [#]*\)|\1\\${CARRIAGE_RETURN}${IP_MACRO_DEF}${TCP_PORTS_MACRO_DEF}${UDP_PORTS_MACRO_DEF}|" ${PF_CONF_PATH}
+# Make a temporary backup of pf.conf in case problem occur whilst making changes.
+cp "${PF_CONF_PATH}" "/tmp/${SCRIPT_NAME}.conf-backup.tmp"
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Unable to make a backup copy of:\n       ${ORNG}${PF_CONF_PATH}${NRML}\n       Aborting.\n"
+	exit 2
+fi
 
-# Add new TCP port foward rules to pf config file
+# Add new port foward rule macros to pf config file.
+sed -i "" "s|\(^[#]* PORT FORWARD RULES MACROS [#]*\)|\1\\${CARRIAGE_RETURN}${IP_MACRO_DEF}${TCP_PORTS_MACRO_DEF}${UDP_PORTS_MACRO_DEF}|" ${PF_CONF_PATH}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+# Add new TCP port foward rules to pf config file.
 if [ "${TCP_PORTS}" != "none" ]
 then
 	sed -i "" "s|\(^[#]* PORT FORWARD TCP RULES [#]*\)|\1\\${CARRIAGE_RETURN}${TCP_RULES_DEF}|" ${PF_CONF_PATH}
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 fi
 
-# Add new UDP port foward rules to pf config file
+# Add new UDP port foward rules to pf config file.
 if [ "${UDP_PORTS}" != "none" ]
 then
 	sed -i "" "s|\(^[#]* PORT FORWARD UDP RULES [#]*\)|\1\\${CARRIAGE_RETURN}${UDP_RULES_DEF}|" ${PF_CONF_PATH}
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+fi
+
+# If any error during string replacements changes, restore healthy config and exit with error.
+if [ ${ERROR_COUNT} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} An unxepected error occured whilst making changes to:\n       ${ORNG}${PF_CONF_PATH}${NRML}\n       Aborting.\n"
+	mv "/tmp/${SCRIPT_NAME}.conf-backup.tmp" "${PF_CONF_PATH}"
+	exit 2
+else
+	rm "/tmp/${SCRIPT_NAME}.conf-backup.tmp"
 fi
 
 if [ "${IS_REPO_CONF}" = "no" ]
 then
-	# Update configuration in the local repo and if interactive mode then push to remote repo
+	# Update configuration in the local repo and if interactive mode then push to remote repo.
 	if [ "${IS_INTERACTIVE}" = "no" ]
 	then
 		echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH} ...\n"
 		CHANGE_MESSAGE="add port forwarding rule '${RULE_NAME}' to pf config" GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH}
+		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	else
 		question_yes_no "\nWould you like to update the repo with the config changes? (RECOMMENDED)"
 		if [ "${ANSWER}" = "yes" ]
 		then
 			echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH} ...\n"
 			CHANGE_MESSAGE="add port forwarding rule '${RULE_NAME}' to pf config" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH}
+			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 		fi
 	fi
 fi
@@ -356,6 +379,22 @@ echo -e ""
 if [ ${ERROR_COUNT} -gt 0 ]
 then
 	exit 2
+fi
+
+if [ "${IS_INTERACTIVE}" = "yes" ]
+then
+	question_yes_no "\nWould you like to reload the pf service for changes to take effect?"
+	if [ "${ANSWER}" = "yes" ]
+	then
+		service pf reload > /dev/null
+		if [ ${?} -eq 0 ]
+		then
+			echo -e "\n${LGRN}Successfully reloaded pf service!${NRML}\n"
+		else
+			echo -e "\n${LRED}Reload of pf service returned an error!${NRML}\n"
+			exit 2
+		fi
+	fi
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-pf-remove-port-forward-rule b/scripts/usr/local/sbin/fdo-pf-remove-port-forward-rule
--- a/scripts/usr/local/sbin/fdo-pf-remove-port-forward-rule
+++ b/scripts/usr/local/sbin/fdo-pf-remove-port-forward-rule
@@ -101,7 +101,7 @@ done
 
 ##### FUNCTIONS ################################################################
 
-# source readee function
+# source readee function.
 . /usr/local/bin/fdo-readee
 
 question_yes_no ()
@@ -180,7 +180,7 @@ fi
 
 ERROR_COUNT=0
 
-# Test if rule_name is valid
+# Test if rule_name is valid.
 test_valid_rule_name "${RULE_NAME}"
 if [ "${VALID_RULE_NAME}" = "no" ]
 then
@@ -188,7 +188,7 @@ then
 	exit 1
 fi
 
-# Test if rule_name exists
+# Test if rule_name exists.
 cat ${PF_CONF_PATH} | egrep "${RULE_NAME}_ip =" > /dev/null 2>&1
 if [ ${?} -ne 0 ]
 then
@@ -196,25 +196,47 @@ then
 	exit 1
 fi
 
-# Remove all lines mentioning the specified rule_name
-sed -i "" "/${RULE_NAME}_ip/d" ${PF_CONF_PATH}
-sed -i "" "/${RULE_NAME}_tcp_ports/d" ${PF_CONF_PATH}
-sed -i "" "/${RULE_NAME}_udp_ports/d" ${PF_CONF_PATH}
+# Make a temporary backup of pf.conf in case problem occur whilst making changes.
+cp "${PF_CONF_PATH}" "/tmp/${SCRIPT_NAME}.conf-backup.tmp"
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Unable to make a backup copy of:\n       ${ORNG}${PF_CONF_PATH}${NRML}\n       Aborting.\n"
+	exit 2
+fi
 
+# Remove all lines mentioning the specified rule_name.
+sed -i "" "/${RULE_NAME}_ip/d" ${PF_CONF_PATH}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+sed -i "" "/${RULE_NAME}_tcp_ports/d" ${PF_CONF_PATH}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+sed -i "" "/${RULE_NAME}_udp_ports/d" ${PF_CONF_PATH}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+# If any error during string replacements changes, restore healthy config and exit with error.
+if [ ${ERROR_COUNT} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} An unxepected error occured whilst making changes to:\n       ${ORNG}${PF_CONF_PATH}${NRML}\n       Aborting.\n"
+	mv "/tmp/${SCRIPT_NAME}.conf-backup.tmp" "${PF_CONF_PATH}"
+	exit 2
+else
+	rm "/tmp/${SCRIPT_NAME}.conf-backup.tmp"
+fi
 
 if [ "${IS_REPO_CONF}" = "no" ]
 then
-	# Update configuration in the local repo and if interactive mode then push to remote repo
+	# Update configuration in the local repo and if interactive mode then push to remote repo.
 	if [ "${IS_INTERACTIVE}" = "no" ]
 	then
 		echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH} ...\n"
 		CHANGE_MESSAGE="remove port forwarding rule '${RULE_NAME}' from pf config" GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH}
+		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	else
 		question_yes_no "\nWould you like to update the repo with the config changes? (RECOMMENDED)"
 		if [ "${ANSWER}" = "yes" ]
 		then
 			echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH} ...\n"
 			CHANGE_MESSAGE="remove port forwarding rule '${RULE_NAME}' from pf config" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PF_CONF_PATH}
+			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 		fi
 	fi
 fi
@@ -224,6 +246,22 @@ echo -e ""
 if [ ${ERROR_COUNT} -gt 0 ]
 then
 	exit 2
+fi
+
+if [ "${IS_INTERACTIVE}" = "yes" ]
+then
+	question_yes_no "\nWould you like to reload the pf service for changes to take effect?"
+	if [ "${ANSWER}" = "yes" ]
+	then
+		service pf reload > /dev/null
+		if [ ${?} -eq 0 ]
+		then
+			echo -e "\n${LGRN}Successfully reloaded pf service!${NRML}\n"
+		else
+			echo -e "\n${LRED}Reload of pf service returned an error!${NRML}\n"
+			exit 2
+		fi
+	fi
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule b/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
--- a/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
+++ b/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
@@ -109,7 +109,7 @@ done
 
 ##### FUNCTIONS ################################################################
 
-# source readee function
+# source readee function.
 . /usr/local/bin/fdo-readee
 
 question_yes_no ()
@@ -255,7 +255,7 @@ fi
 
 ERROR_COUNT=0
 
-# Test if rule_name is valid
+# Test if rule_name is valid.
 test_valid_rule_name "${RULE_NAME}"
 if [ "${VALID_RULE_NAME}" = "no" ]
 then
@@ -263,7 +263,7 @@ then
 	exit 1
 fi
 
-# Test if rule_name already exists
+# Test if rule_name already exists.
 cat ${PPP_CONF_PATH} | egrep "rule_name=${RULE_NAME}" > /dev/null 2>&1
 if [ ${?} -eq 0 ]
 then
@@ -271,7 +271,7 @@ then
 	exit 1
 fi
 
-# Test if local_ip_address is valid
+# Test if local_ip_address is valid.
 test_valid_inet_address "${LOCAL_IP}"
 if [ "${VALID_INET_ADDRESS}" = "no" ]
 then
@@ -279,7 +279,7 @@ then
 	exit 1
 fi
 
-# Test if tcp_ports is valid
+# Test if tcp_ports is valid.
 test_valid_port_list "${TCP_PORTS}"
 if [ "${VALID_PORT_LIST}" = "no" ]
 then
@@ -287,7 +287,7 @@ then
 	exit 1
 fi
 
-# Test if udp_ports is valid
+# Test if udp_ports is valid.
 test_valid_port_list "${UDP_PORTS}"
 if [ "${VALID_PORT_LIST}" = "no" ]
 then
@@ -295,7 +295,7 @@ then
 	exit 1
 fi
 
-# Test if both tcp_ports and udp_ports are 'none'
+# Test if both tcp_ports and udp_ports are 'none'.
 if [ "${TCP_PORTS}" = "none" ] && [ "${UDP_PORTS}" = "none" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} No ports specified!\n"
@@ -303,47 +303,69 @@ then
 fi
 
 
-# Set IFS (internal field seperator) to comma, same as port seperator
+# Make a temporary backup of ppp.conf in case problem occur whilst making changes.
+cp "${PPP_CONF_PATH}" "/tmp/${SCRIPT_NAME}.conf-backup.tmp"
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Unable to make a backup copy of:\n       ${ORNG}${PPP_CONF_PATH}${NRML}\n       Aborting.\n"
+	exit 2
+fi
+
+# Set IFS (internal field seperator) to comma, same as port seperator.
 EXISTING_IFS=${IFS}
 IFS=","
 
-# Add new TCP port forward rules to ppp config file
+# Add new TCP port forward rules to ppp config file.
 for TCP_PORT_VALUE in ${TCP_PORTS}
 do
 	if [ "${TCP_PORT_VALUE}" != "none" ]
 	then
 		PORT_VALUE=`echo ${TCP_PORT_VALUE} | sed "s|:|-|"`
 		sed -i "" "s|\(^ ## NAT port forward rules .*\)|\1\\${CARRIAGE_RETURN} nat port tcp ${LOCAL_IP}:${PORT_VALUE} ${PORT_VALUE}                # Port Forwarding (TCP); rule_name=${RULE_NAME}|" ${PPP_CONF_PATH}
+		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	fi
 done
 
-# Add new UDP port forward rules to ppp config file
+# Add new UDP port forward rules to ppp config file.
 for UDP_PORT_VALUE in ${UDP_PORTS}
 do
 	if [ "${UDP_PORT_VALUE}" != "none" ]
 	then
 		PORT_VALUE=`echo ${UDP_PORT_VALUE} | sed "s|:|-|"`
 		sed -i "" "s|\(^ ## NAT port forward rules .*\)|\1\\${CARRIAGE_RETURN} nat port udp ${LOCAL_IP}:${PORT_VALUE} ${PORT_VALUE}                # Port Forwarding (UDP); rule_name=${RULE_NAME}|" ${PPP_CONF_PATH}
+		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	fi
 done
 
-# Set IFS back to what it was before
+# Set IFS back to what it was before.
 IFS=${EXISTING_IFS}
+
+# If any error during string replacements changes, restore healthy config and exit with error.
+if [ ${ERROR_COUNT} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} An unxepected error occured whilst making changes to:\n       ${ORNG}${PPP_CONF_PATH}${NRML}\n       Aborting.\n"
+	mv "/tmp/${SCRIPT_NAME}.conf-backup.tmp" "${PPP_CONF_PATH}"
+	exit 2
+else
+	rm "/tmp/${SCRIPT_NAME}.conf-backup.tmp"
+fi
 
 
 if [ "${IS_REPO_CONF}" = "no" ]
 then
-	# Update configuration in the local repo and if interactive mode then push to remote repo
+	# Update configuration in the local repo and if interactive mode then push to remote repo.
 	if [ "${IS_INTERACTIVE}" = "no" ]
 	then
 		echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PPP_CONF_PATH} ...\n"
 		CHANGE_MESSAGE="add port forwarding rule '${RULE_NAME}' to ppp config" GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PPP_CONF_PATH}
+		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	else
 		question_yes_no "\nWould you like to update the repo with the config changes? (RECOMMENDED)"
 		if [ "${ANSWER}" = "yes" ]
 		then
 			echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PPP_CONF_PATH} ...\n"
 			CHANGE_MESSAGE="add port forwarding rule '${RULE_NAME}' to ppp config" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PPP_CONF_PATH}
+			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 		fi
 	fi
 fi
@@ -353,6 +375,22 @@ echo -e ""
 if [ ${ERROR_COUNT} -gt 0 ]
 then
 	exit 2
+fi
+
+if [ "${IS_INTERACTIVE}" = "yes" ]
+then
+	question_yes_no "\nWould you like to restart the ppp service for changes to take effect?"
+	if [ "${ANSWER}" = "yes" ]
+	then
+		service ppp restart > /dev/null
+		if [ ${?} -eq 0 ]
+		then
+			echo -e "\n${LGRN}Successfully restarted ppp service!${NRML}\n"
+		else
+			echo -e "\n${LRED}Restart of ppp service returned an error!${NRML}\n"
+			exit 2
+		fi
+	fi
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-ppp-remove-port-forward-rule b/scripts/usr/local/sbin/fdo-ppp-remove-port-forward-rule
--- a/scripts/usr/local/sbin/fdo-ppp-remove-port-forward-rule
+++ b/scripts/usr/local/sbin/fdo-ppp-remove-port-forward-rule
@@ -101,7 +101,7 @@ done
 
 ##### FUNCTIONS ################################################################
 
-# source readee function
+# source readee function.
 . /usr/local/bin/fdo-readee
 
 question_yes_no ()
@@ -180,7 +180,7 @@ fi
 
 ERROR_COUNT=0
 
-# Test if rule_name is valid
+# Test if rule_name is valid.
 test_valid_rule_name "${RULE_NAME}"
 if [ "${VALID_RULE_NAME}" = "no" ]
 then
@@ -188,7 +188,7 @@ then
 	exit 1
 fi
 
-# Test if rule_name exists
+# Test if rule_name exists.
 cat ${PPP_CONF_PATH} | egrep "rule_name=${RULE_NAME}" > /dev/null 2>&1
 if [ ${?} -ne 0 ]
 then
@@ -196,24 +196,46 @@ then
 	exit 1
 fi
 
-# Remove all lines mentioning the specified rule_name
+# Make a temporary backup of ppp.conf in case problem occur whilst making changes.
+cp "${PPP_CONF_PATH}" "/tmp/${SCRIPT_NAME}.conf-backup.tmp"
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Unable to make a backup copy of:\n       ${ORNG}${PPP_CONF_PATH}${NRML}\n       Aborting.\n"
+	exit 2
+fi
+
+# Remove all lines mentioning the specified rule_name.
 sed -i "" "/^ nat port tcp .*rule_name=${RULE_NAME}.*/d" ${PPP_CONF_PATH}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 sed -i "" "/^ nat port udp .*rule_name=${RULE_NAME}.*/d" ${PPP_CONF_PATH}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+# If any error during string replacements changes, restore healthy config and exit with error.
+if [ ${ERROR_COUNT} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} An unxepected error occured whilst making changes to:\n       ${ORNG}${PPP_CONF_PATH}${NRML}\n       Aborting.\n"
+	mv "/tmp/${SCRIPT_NAME}.conf-backup.tmp" "${PPP_CONF_PATH}"
+	exit 2
+else
+	rm "/tmp/${SCRIPT_NAME}.conf-backup.tmp"
+fi
 
 
 if [ "${IS_REPO_CONF}" = "no" ]
 then
-	# Update configuration in the local repo and if interactive mode then push to remote repo
+	# Update configuration in the local repo and if interactive mode then push to remote repo.
 	if [ "${IS_INTERACTIVE}" = "no" ]
 	then
 		echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PPP_CONF_PATH} ...\n"
 		CHANGE_MESSAGE="remove port forwarding rule '${RULE_NAME}' from ppp config" GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PPP_CONF_PATH}
+		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	else
 		question_yes_no "\nWould you like to update the repo with the config changes? (RECOMMENDED)"
 		if [ "${ANSWER}" = "yes" ]
 		then
 			echo -e "\n${FDO_SERVER_SCRIPT} update-config ${PPP_CONF_PATH} ...\n"
 			CHANGE_MESSAGE="remove port forwarding rule '${RULE_NAME}' from ppp config" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config ${PPP_CONF_PATH}
+			ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 		fi
 	fi
 fi
@@ -223,6 +245,22 @@ echo -e ""
 if [ ${ERROR_COUNT} -gt 0 ]
 then
 	exit 2
+fi
+
+if [ "${IS_INTERACTIVE}" = "yes" ]
+then
+	question_yes_no "\nWould you like to restart the ppp service for changes to take effect?"
+	if [ "${ANSWER}" = "yes" ]
+	then
+		service ppp restart > /dev/null
+		if [ ${?} -eq 0 ]
+		then
+			echo -e "\n${LGRN}Successfully restarted ppp service!${NRML}\n"
+		else
+			echo -e "\n${LRED}Restart of ppp service returned an error!${NRML}\n"
+			exit 2
+		fi
+	fi
 fi
 
 ################################################################################
