Huge changes: move all fdo configuration and state to UCL.

diff --git a/scripts/usr/local/sbin/fdo-backupz-repair-state b/scripts/usr/local/sbin/fdo-backupz-repair-state
--- a/scripts/usr/local/sbin/fdo-backupz-repair-state
+++ b/scripts/usr/local/sbin/fdo-backupz-repair-state
@@ -27,10 +27,17 @@
 ##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
 SCRIPT_NAME=`basename ${0}`
-POOL=${1}
-BACKUP_POOL=${2}
+FILESYSTEM="${1}"
+BACKUP_POOL="${2}"
 NUM_MANDATORY_ARGS=2
 FORCE_MODE="no"
+ERROR_ID="null"
+ERROR_DATASET="null"
+UCL_CMD="/usr/local/bin/uclcmd"
+FDO_CONFIG_ROOT=${FDO_CONFIG_ROOT:-"/usr/local/etc/fdo"}
+HOST_CONF_PATH=${HOST_CONF_PATH:-"${FDO_CONFIG_ROOT}/host.conf"}
+SYSTEM_STATE_ROOT=${SYSTEM_STATE_ROOT:-"/var/db"}
+STATE_PATH=${STATE_PATH:-"${SYSTEM_STATE_ROOT}/fdo-backupz.state"}
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -59,13 +66,13 @@ usage ()
 	echo -e ""
 	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
 	echo -e ""
-	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} pool backup_pool [--force]${NRML}"
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} filesystem backup_pool [--force]${NRML}"
 	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup${NRML}"
 	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup --force${NRML}"
 	echo -e ""
 	echo -e "${YELL}Options:${NRML}"
 	echo -e ""
-	echo -e "${YELL}--force  Ignore warnings / is_running marker and force operation.${NRML}"
+	echo -e "${YELL}--force  Ignore warnings / running state marker and force the operation.${NRML}"
 }
 
 
@@ -96,6 +103,27 @@ done
 
 
 ##### FUNCTIONS ################################################################
+
+# source readee function
+. /usr/local/bin/fdo-readee
+
+question_yes_no ()
+{
+
+	LOOP=1
+
+	while [ ${LOOP} = 1 ]
+		do
+		echo -e "${LCYN}${1}${NRML}"
+		readee -p "${LCYN}(yes/no): ${NRML}" ANSWER
+		if [ "${ANSWER}" = "yes" ] || [ "${ANSWER}" = "no" ]
+		then
+			LOOP=0
+		fi
+		echo ""
+	done
+
+}
 
 test_if_host ()
 {
@@ -133,74 +161,208 @@ then
 	exit 1
 fi
 
-BACKUP_POOL_HEALTH=`zpool get -H health ${BACKUP_POOL} | awk '{print $3}' 2> /dev/null`
+BACKUP_POOL_HEALTH=`zpool get -H -o value health ${BACKUP_POOL} 2> /dev/null`
 if [ "${BACKUP_POOL_HEALTH}" != "ONLINE" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' appears to be unhealthy.\n       Aborting.\n"
 	exit 1
 fi
 
-POOL_ATTRIBUTES=`zpool get -H all ${POOL} 2> /dev/null`
+zfs list -H -o name "${FILESYSTEM}" > /dev/null 2>&1
 if [ ${?} -ne 0 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported.\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} The source filesystem '${FILESYSTEM}' does not appear to exist.\n       Aborting.\n"
 	exit 1
 fi
 
-POOL_HEALTH=`zpool get -H health ${POOL} | awk '{print $3}' 2> /dev/null`
-if [ "${POOL_HEALTH}" != "ONLINE" ]
+FILESYSTEM_POOL=`echo "${FILESYSTEM}" | cut -d"/" -f1`
+
+FILESYSTEM_POOL_ATTRIBUTES=`zpool get -H all ${FILESYSTEM_POOL} 2> /dev/null`
+if [ ${?} -ne 0 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy.\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} The source filesystem pool '${FILESYSTEM_POOL}' does not appear to be imported.\n       Aborting.\n"
 	exit 1
 fi
 
-pgrep -fl "fdo-backupz-repair-state" > /dev/null 2>&1
+FILESYSTEM_POOL_HEALTH=`zpool get -H -o value health ${FILESYSTEM_POOL} 2> /dev/null`
+if [ "${FILESYSTEM_POOL_HEALTH}" != "ONLINE" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The source filesystem pool '${FILESYSTEM_POOL}' appears to be unhealthy.\n       Aborting.\n"
+	exit 1
+fi
+
+if [ ! -e "${HOST_CONF_PATH}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The host config file \n       '${ORNG}${HOST_CONF_PATH}${NRML}'\n       appears to be missing.\n       Aborting.\n"
+	exit 1
+fi
+
+BACKUP_POOL_ROOT_PATH=`zfs list -H -o mountpoint ${BACKUP_POOL}`
+TEST_BACKUP_POOL=`df -t zfs ${BACKUP_POOL_ROOT_PATH} | tail -1 | awk '{print $1}'`
+if [ "${TEST_BACKUP_POOL}" != "${BACKUP_POOL}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' does not appear to be mounted!\n       Aborting.\n"
+	exit 1
+fi
+
+CURRENT_JOB_STATE=`${UCL_CMD} get -f ${STATE_PATH} -q .pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_state 2> /dev/null`
+if [ "${CURRENT_JOB_STATE}" = "completed" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The current backup from '${FILESYSTEM}' to '${BACKUP_POOL}' completed!\n       Aborting.\n"
+	exit 1
+elif [ "${CURRENT_JOB_STATE}" = "running" ] && [ "${FORCE_MODE}" = "no" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backup job running for '${FILESYSTEM}'!\n       Consider using --force option.\n       Aborting.\n"
+	exit 1
+elif [ "${CURRENT_JOB_STATE}" = "repairing" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a repair job running for '${FILESYSTEM}'!\n       Aborting.\n"
+	exit 1
+elif [ "${CURRENT_JOB_STATE}" = "thinning" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a thin-snapshots job running for '${FILESYSTEM}'!\n       Aborting.\n"
+	exit 1
+elif [ "${CURRENT_JOB_STATE}" != "failed" ] && [ "${CURRENT_JOB_STATE}" != "running" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There does not appear to be a failed or running job for '${FILESYSTEM}'!\n       Aborting.\n"
+	exit 1
+fi
+
+# Check that we are not currently running a backupz operation.
+pgrep -fl "fdo-backupz " > /dev/null 2>&1
 if [ ${?} -eq 0 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} There appears to be another backup repair operation running!\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backupz operation running!\n       Aborting.\n"
 	exit 1
 fi
 
-pgrep -fl "fdo-backupz-thin-snapshots" > /dev/null 2>&1
+# Check that we are not currently running a backupz thin-snapshots operation.
+pgrep -fl "fdo-backupz-thin-snapshots " > /dev/null 2>&1
 if [ ${?} -eq 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} There appears to be a thin-snapshots operation running!\n       Aborting.\n"
 	exit 1
 fi
 
-BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
-
-if [ ! -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf ] && [ ! -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Unable to find failed backup from '${POOL}' to '${BACKUP_POOL}'!\n       Aborting.\n"
-	exit 1
-fi
-
-if [ -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ] && [ ${FORCE_MODE} = "no" ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backup running for '${POOL}'!\nConsider using the --force option.\n       Aborting.\n"
-	exit 1
-fi
-
 
 ##### MAIN EXECUTION THREAD ####################################################
 
-# Get the last successful backup snapshot suffix.
-LAST_SUCCESSFUL_BACKUP_SNAPSHOT=`cat ${BACKUP_POOL_ROOT_PATH}/last-successful-backupz-${POOL}@${BACKUP_POOL}.inf`
+ERROR_COUNT=0
 
-# Get the last failed backup snapshot suffix.
-if [ -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf ]
+# Create log filesystem if log directory doesn't already exist.
+if [ ! -d "${BACKUP_POOL_ROOT_PATH}/log" ]
 then
-	LAST_FAILED_BACKUP_SNAPSHOT=`head -1 ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf | awk '{print $3}'`
+	zfs create -o mountpoint="${BACKUP_POOL_ROOT_PATH}/log" -o compression=on "${BACKUP_POOL}/log"
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+fi
+
+# Get current (failed / running) backup job name from backupz state file.
+CURRENT_JOB=`${UCL_CMD} get -f ${STATE_PATH} -q ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.current_job_name" 2> /dev/null`
+if [ ${?} -ne 0 ] || [ "${CURRENT_JOB}" = "null" ] || [ "${CURRENT_JOB}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be no failed or running job for '${FILESYSTEM}'!\n       Aborting.\n"
+	exit 2
+fi
+
+# Create temp files and log file path variables.
+FILESYSTEM_FLAT=`echo "${FILESYSTEM}" | sed "s|/|__|g"`
+LOG_FILE_PATH="${BACKUP_POOL_ROOT_PATH}/log/repair-backupz-state.${CURRENT_JOB}.${FILESYSTEM_FLAT}@${BACKUP_POOL}.log"
+
+# Get previously completed backupz job name from backupz state file.
+COMPLETED_JOB=`${UCL_CMD} get -f ${STATE_PATH} -q ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.completed_job_name" 2> /dev/null`
+if [ ${?} -ne 0 ] || [ "${COMPLETED_JOB}" = "null" ] || [ "${COMPLETED_JOB}" = "" ]
+then
+	COMPLETED_JOB="no-previous-job-completed"
+	echo -e "\n${YELL}No previously completed job for this backup!${NRML}"
 else
-	LAST_FAILED_BACKUP_SNAPSHOT=`cat ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf`
+	echo -e "\n${YELL}Previous completed backup job:${NRML} ${COMPLETED_JOB}"
+fi
+
+# If current backupz job state is 'failed', get and display error details.
+if [ "${CURRENT_JOB_STATE}" = "failed" ]
+then
+	CURRENT_JOB_ERROR_ID=`${UCL_CMD} get -f ${STATE_PATH} -q ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_error_id" 2> /dev/null`
+	CURRENT_JOB_ERROR_DATASET=`${UCL_CMD} get -f ${STATE_PATH} -q ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_error_dataset" 2> /dev/null`
+
+	echo -e "\n${YELL}The current backupz job was marked as '${NRML}failed${YELL}' with the following details:${NRML}\n"
+	echo -e "        Error ID: ${CURRENT_JOB_ERROR_ID}\n        Dataset: ${CURRENT_JOB_ERROR_DATASET}\n"
+else
+	echo -e "\n${ORNG}WARNING:${NRML} The previous backupz job never completed or failed. It MAY STILL be running!\n" 
+fi
+
+# Just in case the failed backupz job is actually the last completed backup job (should not happen).
+if [ "${COMPLETED_JOB}" = "${CURRENT_JOB}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The 'current' backupz job appears to be the same as the previously"
+	echo -e "       'completed' backupz job! This should never happen!\n       Aborting.\n"
+	exit 2
+fi
+
+# Allow the user to see a simulation of what destructive steps the repair will do.
+question_yes_no "\nWould you like to see a simulation of the destructive steps to be taken?"
+if [ "${ANSWER}" = "yes" ]
+then
+	echo -e "\n${YELL}   --- BACKUPZ STATE REPAIR SIMULATION ---   ${NRML}\n"
+
+	fdo-backupz-destroy-snapshot "${BACKUP_POOL}" "${FILESYSTEM_FLAT}.*@${CURRENT_JOB}" --simulate
+
+	fdo-backupz-destroy-snapshot "${FILESYSTEM_POOL}" "${FILESYSTEM}.*@${CURRENT_JOB}" --simulate
+
+	if [ "${COMPLETED_JOB}" = "no-previous-job-completed" ]
+	then
+		fdo-backupz-destroy-filesystem "${BACKUP_POOL}" "${BACKUP_POOL}/${FILESYSTEM_FLAT}$" --recursive --simulate
+	fi
+
+	echo -e "\n${YELL}   --- END OF SIMULATION ---   ${NRML}\n"
+fi
+
+# Confirm whether to proceed with repair job.
+question_yes_no "\nAre you sure you want to proceed to repair the backup for the following?\n\
+        filesystem='${FILESYSTEM}'\n        backup pool='${BACKUP_POOL}'\n        job name='${CURRENT_JOB}'"
+if [ "${ANSWER}" = "no" ]
+then
+	echo -e "\n${YELL}Repair job cancelled by user!${NRML}\n"
+	exit 0
+fi
+
+echo -e "Beginning repair of backupz state for filesystem '${FILESYSTEM}'.\n" >> ${LOG_FILE_PATH}
+echo -e "Current job state: ${CURRENT_JOB_STATE}" >> ${LOG_FILE_PATH}
+echo -e "Previous completed job: ${COMPLETED_JOB}" >> ${LOG_FILE_PATH}
+echo -e "Current running / failed job: ${CURRENT_JOB}" >> ${LOG_FILE_PATH}
+echo -e "Failed job error id: ${CURRENT_JOB_ERROR_ID}" >> ${LOG_FILE_PATH}
+echo -e "Failed job error dataset: ${CURRENT_JOB_ERROR_DATASET}" >> ${LOG_FILE_PATH}
+echo -e "Force mode used: ${FORCE_MODE}\n" >> ${LOG_FILE_PATH}
+
+# Wait for backupz state to be unlocked.
+while [ -f ${STATE_PATH}.lock ]
+do
+	echo -e "\n${YELL}Waiting for backupz state lock file to be unlocked...${NRML}\n"
+	sleep 2
+done
+
+# Make a lock file recovery copy of the existing backupz state file.
+# We won't release this lock until the repair job is complete or exited, due to it's dangerous nature.
+touch ${STATE_PATH}
+cp ${STATE_PATH} ${STATE_PATH}.lock
+
+# Set the job state to 'repairing' for this job.
+${UCL_CMD} set -f ${STATE_PATH} ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_state" "repairing"
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+# If we hit any errors so far, let's not proceed and revert backupz state file.
+if [ ${ERROR_COUNT} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There was an unexpected error preparing the repair job!\n       Aborting.\n"
+	mv ${STATE_PATH}.lock ${STATE_PATH}
+	echo -e "\nERROR: There was an unexpected error preparing the repair job!\n       Aborting." >> ${LOG_FILE_PATH}
+	exit 2
 fi
 
 # If in force mode, kill any running backupz processes.
 if [ "${FORCE_MODE}" = "yes" ]
 then
 	echo -e "\n${YELL}   --- FORCE MODE ---   ${NRML}\n"
-	BACKUPZ_PID=`ps ax | egrep "backupz " | egrep "${POOL} ${BACKUP_POOL}" | awk '{print $1}'`
+	BACKUPZ_PID=`pgrep -fl "fdo-backupz ${FILESYSTEM} ${BACKUP_POOL}" | awk '{print $1}'`
 	if [ "${BACKUPZ_PID}" != "" ]
 	then
 		echo -e "\n${YELL}Killing running backupz processes...${NRML}\n"
@@ -209,34 +371,71 @@ then
 	fi
 fi
 
-# Just in case last failed backup is actually the last successful backup (should not happen).
-if [ "${LAST_FAILED_BACKUP_SNAPSHOT}" = "${LAST_SUCCESSFUL_BACKUP_SNAPSHOT}" ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} The last failed backup appears to be the same as the last"
-	echo -e "       successful backup! This should never happen!\n       Aborting.\n"
-	exit 2
-fi
-
-# Now we remove the failed backup snapshots from both the production pool and the backup pool.
-echo -e "\n${YELL}Destroying failed backupz snapshots from the backup pool...${NRML}\n"
-fdo-backupz-destroy-snapshot ${BACKUP_POOL} "@${LAST_FAILED_BACKUP_SNAPSHOT}"
+# Now we remove the failed backupz snapshots from the backup pool.
+echo -e "\n${YELL}Destroying failed backupz job snapshots from the backup pool...${NRML}"
+fdo-backupz-destroy-snapshot "${BACKUP_POOL}" "${FILESYSTEM_FLAT}.*@${CURRENT_JOB}" --simulate | sed "/--- SIMULATION MODE ---/d" >> ${LOG_FILE_PATH}
+fdo-backupz-destroy-snapshot "${BACKUP_POOL}" "${FILESYSTEM_FLAT}.*@${CURRENT_JOB}"
 if [ ${?} -ne 0 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} Failed to destroy failed backupz snaphots from '${BACKUP_POOL}'!\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} Failed to destroy failed job snaphots from '${BACKUP_POOL}'!\n       Aborting.\n"
+	mv ${STATE_PATH}.lock ${STATE_PATH}
+	echo -e "\nERROR: Failed to destroy failed job snaphots from '${BACKUP_POOL}'!\n       Aborting." >> ${LOG_FILE_PATH}
 	exit 2
 fi
 
-echo -e "\n${YELL}Destroying failed backupz snapshots from the production pool...${NRML}\n"
-fdo-backupz-destroy-snapshot ${POOL} "@${LAST_FAILED_BACKUP_SNAPSHOT}"
+# Now we remove the failed backupz snapshots from the source (filesystem) pool.
+echo -e "\n${YELL}Destroying failed backupz job snapshots from the source (filesystem) pool...${NRML}"
+fdo-backupz-destroy-snapshot "${FILESYSTEM_POOL}" "${FILESYSTEM}.*@${CURRENT_JOB}" --simulate | sed "/--- SIMULATION MODE ---/d" >> ${LOG_FILE_PATH}
+fdo-backupz-destroy-snapshot "${FILESYSTEM_POOL}" "${FILESYSTEM}.*@${CURRENT_JOB}"
 if [ ${?} -ne 0 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} Failed to destroy failed backupz snaphots from '${POOL}'!\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} Failed to destroy failed job snaphots from '${FILESYSTEM_POOL}'!\n       Aborting.\n"
+	mv ${STATE_PATH}.lock ${STATE_PATH}
+	echo -e "\nERROR: Failed to destroy failed job snaphots from '${FILESYSTEM_POOL}'!\n       Aborting." >> ${LOG_FILE_PATH}
 	exit 2
 fi
 
-# After successfully destroying failed backup snapshots, let's remove the failed backup markers.
-rm -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf 2> /dev/null
-rm -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-${POOL}-running.inf 2> /dev/null
-rm -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf
+# If there was no previous completed job, we need to clean up the empty filesystems.
+if [ "${COMPLETED_JOB}" = "no-previous-job-completed" ]
+then
+	echo -e "\n${YELL}Cleaning up stale filesystems on backup pool...${NRML}"
+	fdo-backupz-destroy-filesystem "${BACKUP_POOL}" "${BACKUP_POOL}/${FILESYSTEM_FLAT}$" --recursive --simulate >> ${LOG_FILE_PATH}
+	fdo-backupz-destroy-filesystem "${BACKUP_POOL}" "${BACKUP_POOL}/${FILESYSTEM_FLAT}$" --recursive
+	if [ ${?} -ne 0 ]
+	then
+		echo -e "\n${LRED}ERROR:${NRML} Failed to destroy stale filesystems from '${BACKUP_POOL}'!\n       Aborting.\n"
+		mv ${STATE_PATH}.lock ${STATE_PATH}
+		echo -e "\nERROR: Failed to destroy stale filesystems from '${BACKUP_POOL}'!\n       Aborting." >> ${LOG_FILE_PATH}
+		exit 2
+	fi
+fi
+
+# If we get here, we can ASSUME the backupz repair job has completed successfully, and set state variables accordingly.
+echo -e "\n${YELL}Setting backupz state variables to previous completed backup state...${NRML}\n"
+echo -e "\nSetting backupz state variables to previous completed backup state..." >> ${LOG_FILE_PATH}
+
+if [ "${COMPLETED_JOB}" = "no-previous-job-completed" ]
+then
+	# Set the job state to 'null' for this filesystem.
+	${UCL_CMD} set -f ${STATE_PATH} ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_state" "null"
+else
+	# Set the job state to 'completed' for this filesystem.
+	${UCL_CMD} set -f ${STATE_PATH} ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_state" "completed"
+fi
+
+# Set the current job name to 'null' for this filesystem.
+${UCL_CMD} set -f ${STATE_PATH} ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.current_job_name" "null"
+
+# Set the current job error id to 'null' for this filesystem.
+${UCL_CMD} set -f ${STATE_PATH} ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_error_id" "null"
+
+# Set the current job error dataset to 'null' for this filesystem.
+${UCL_CMD} set -f ${STATE_PATH} ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_error_dataset" "null"
+
+# ASSUME that repair was successful, so let's remove the state lock and proceed.
+rm ${STATE_PATH}.lock
+
+echo -e "\nBackupz repair state for filesystem '${FILESYSTEM}' finished." >> ${LOG_FILE_PATH}
+echo -e "\n${LGRN}Backupz repair state for filesystem '${NRML}${FILESYSTEM}${LGRN}' finished!${NRML}\n"
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-backupz-thin-snapshots b/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
--- a/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
+++ b/scripts/usr/local/sbin/fdo-backupz-thin-snapshots
@@ -27,16 +27,21 @@
 ##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
 SCRIPT_NAME=`basename ${0}`
-POOL=${1}
-BACKUP_POOL=${2}
-OFFSET_DAYS=${3}
-INTERVAL_DAYS=${4}
+FILESYSTEM="${1}"
+BACKUP_POOL="${2}"
+OFFSET_DAYS="${3}"
+INTERVAL_DAYS="${4}"
 NUM_MANDATORY_ARGS=4
-FILESYSTEM_FILTER=""
+FILTER=""
 SIMULATION_MODE="no"
 NOW=`date +%s`
 NOW_DATE_TIME=`date +%Y-%m-%d_%H-%M`
 DAY_IN_SECS=86400
+UCL_CMD="/usr/local/bin/uclcmd"
+FDO_CONFIG_ROOT=${FDO_CONFIG_ROOT:-"/usr/local/etc/fdo"}
+HOST_CONF_PATH=${HOST_CONF_PATH:-"${FDO_CONFIG_ROOT}/host.conf"}
+SYSTEM_STATE_ROOT=${SYSTEM_STATE_ROOT:-"/var/db"}
+STATE_PATH=${STATE_PATH:-"${SYSTEM_STATE_ROOT}/fdo-backupz.state"}
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -65,13 +70,13 @@ usage ()
 	echo -e ""
 	echo -e "${LCYN}    ---- ${SCRIPT_NAME} command usage ----${NRML}"
 	echo -e ""
-	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} pool backup_pool offset interval [--simulate]${NRML}"
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} filesystem backup_pool offset interval [--simulate]${NRML}"
 	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup 28 7${NRML}"
-	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup 28 7 --simulate${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data/somedb backup 28 7 --simulate${NRML}"
 	echo -e ""
-	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} pool backup_pool offset interval [--filter=\"filesystem_filter\"] [--simulate]${NRML}"
+	echo -e "${YELL}Usage:   ${LGRN}${SCRIPT_NAME} filesystem backup_pool offset interval [--filter=\"filesystem_filter\"] [--simulate]${NRML}"
 	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup 28 7 --filter=\"/users\"${NRML}"
-	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data backup 28 7 --filter=\"/users\" --simulate${NRML}"
+	echo -e "${NRML}Example: ${LBLU}${SCRIPT_NAME} data/somedb backup 28 7 --filter=\"/users\" --simulate${NRML}"
 	echo -e ""
 	echo -e "${GREY}Note   :  offset and interval are in number of days.${NRML}"
 	echo -e ""
@@ -96,7 +101,7 @@ do
 		OPTIONAL_ARG_VALUE=`echo ${ARG} | cut -d= -f2`
 		case ${OPTIONAL_ARG_NAME} in
 			--filter)
-				FILESYSTEM_FILTER="${OPTIONAL_ARG_VALUE}"
+				FILTER="${OPTIONAL_ARG_VALUE}"
 				;;
 			--simulate)
 				SIMULATION_MODE="yes"
@@ -119,95 +124,121 @@ done
 thin_snapshots_by_filesystem()
 {
 
-	FILESYSTEM=${1}
+	FS_TO_THIN="${1}"
 
-	SNAPSHOTS=`zfs list -r -d 1 -H -t snapshot -o name ${FILESYSTEM}`
+	# Prepare a UCL temp file to use it's arrays feature, since posix shell doesn't have one.
+	:> "${TEMPDATA_PATH}"
+	uclcmd set -f "${TEMPDATA_PATH}" -t object . "snapshot_names=[]; snapshot_timestamps=[]; snapshot_actions=[]; projections=[];"
 
+	# Get a list of snapshots for this specific filesystem.
+	SNAPSHOTS=`zfs list -r -d 1 -H -t snapshot -o name ${FS_TO_THIN}`
 	EARLIEST_TIMESTAMP=${NOW}
 	i=0
+
+	# Populate a set of arrays with snapshot details to manage which snapshots to keep or destroy.
 	for SNAPSHOT in ${SNAPSHOTS}
 	do
-		SNAPSHOT_NAMES[${i}]=${SNAPSHOT}
-		SNAPSHOT_TIMESTAMPS[${i}]=`echo ${SNAPSHOT} | sed 's|^.*@||' | xargs date -j -f "%Y-%m-%d_%H-%M" -- +%s`
-		SNAPSHOT_ACTION[${i}]="keep"
+		SNAPSHOT_TIMESTAMP=`echo ${SNAPSHOT} | sed 's|^.*@||' | xargs date -j -f "%Y-%m-%d_%H-%M" -- +%s`
+		uclcmd set -f "${TEMPDATA_PATH}" .snapshot_names.${i} "${SNAPSHOT}"
+		uclcmd set -f "${TEMPDATA_PATH}" .snapshot_timestamps.${i} "${SNAPSHOT_TIMESTAMP}"
+		uclcmd set -f "${TEMPDATA_PATH}" .snapshot_actions.${i} "keep"
 
-		if [ ${SNAPSHOT_TIMESTAMPS[${i}]} -lt ${EARLIEST_TIMESTAMP} ]
+		if [ ${SNAPSHOT_TIMESTAMP} -lt ${EARLIEST_TIMESTAMP} ]
 		then
-			EARLIEST_TIMESTAMP=${SNAPSHOT_TIMESTAMPS[${i}]}
+			EARLIEST_TIMESTAMP=${SNAPSHOT_TIMESTAMP}
 		fi
 		i=$(( ${i} + 1 ))
 	done
 
-	NUM_SNAPSHOTS=${#SNAPSHOT_NAMES[@]}
-
 	FIRST_PROJECTION=$(( ${NOW} - ${OFFSET} ))
 
-	PROJECTIONS[0]=${FIRST_PROJECTION}
+	uclcmd set -f "${TEMPDATA_PATH}" .projections.0 ${FIRST_PROJECTION}
 
 	NEXT_PROJECTION=${FIRST_PROJECTION}
 
+	# Populate an array (list) of projected timestamps that we want to keep.
 	j=1
 	while [ ${NEXT_PROJECTION} -gt ${EARLIEST_TIMESTAMP} ]
 	do
 		NEXT_PROJECTION=$(( ${NEXT_PROJECTION} - ${INTERVAL} ))
-		PROJECTIONS[${j}]=${NEXT_PROJECTION}
+		uclcmd set -f "${TEMPDATA_PATH}" .projections.${j} ${NEXT_PROJECTION}
 		j=$(( ${j} + 1 ))
 	done
 
-	# Add one more projection at the end (UNIX epoch +1) so we don't get out of index error
-	PROJECTIONS[${j}]=1
+	# Add one more projection at the end (UNIX epoch +1) so we don't get out of index error.
+	uclcmd set -f "${TEMPDATA_PATH}" .projections.${j} 1
 
-	# Ensure that the latest 2 snapshot are always kept
+	# For completeness of log output to reflect what snapshots were kept.
+	SNAPSHOT_NAME=`uclcmd get -f "${TEMPDATA_PATH}" -q .snapshot_names.$(( ${i} - 1 ))`
+	echo "${SNAPSHOT_NAME} -> keep" >> ${LOG_FILE_PATH}
+
+	# Ensure that the latest 2 snapshots are always kept.
 	i=$(( ${i} - 2 ))
 
+	LAST_SNAPSHOT_KEPT=${i}
 	j=0
 
-	while [ ${i} -ge 0 ]
+	# Main algorithm for determining which snapshots to keep and which are safe to destroy.
+	# The interval and offset determines the projections and we try to keep snapshots as 
+	# close to the projections as possible. We stay conservative with regards to destroying
+	# snapshots. It's better to have an extra few snapshots than lose one we didn't expect to.
+	while [ ${i} -gt 0 ]
 	do
-		if [ ${SNAPSHOT_TIMESTAMPS[${i}]} -lt ${FIRST_PROJECTION} ]
+
+		SNAPSHOT_TIMESTAMP=`uclcmd get -f "${TEMPDATA_PATH}" -q .snapshot_timestamps.${i}`
+		SNAPSHOT_NAME=`uclcmd get -f "${TEMPDATA_PATH}" -q .snapshot_names.${i}`
+		if [ ${SNAPSHOT_TIMESTAMP} -lt ${FIRST_PROJECTION} ]
 		then
 
-			NEXT_SNAPSHOT=${SNAPSHOT_TIMESTAMPS[$(( ${i} - 1 ))]}
-			LAST_KEPT_TO_NEXT_DELTA=$(( ${SNAPSHOT_TIMESTAMPS[${LAST_SNAPSHOT_KEPT}]} - ${NEXT_SNAPSHOT} ))
+			NEXT_SNAPSHOT=`uclcmd get -f "${TEMPDATA_PATH}" -q .snapshot_timestamps.$(( ${i} - 1 ))`
+			LAST_SNAPSHOT_KEPT_TIMESTAMP=`uclcmd get -f "${TEMPDATA_PATH}" -q .snapshot_timestamps.${LAST_SNAPSHOT_KEPT}`
+			LAST_KEPT_TO_NEXT_DELTA=$(( ${LAST_SNAPSHOT_KEPT_TIMESTAMP} - ${NEXT_SNAPSHOT} ))
+			PROJECTION=`uclcmd get -f "${TEMPDATA_PATH}" -q .projections.${j}`
 
-			if [ ${SNAPSHOT_TIMESTAMPS[${i}]} -gt ${PROJECTIONS[${j}]} ] && [ ${i} -gt 0 ] && [ "${SNAPSHOT_NAMES[${i}]}" != "${LAST_SUCCESSFUL_BACKUP_SNAPSHOT}" ]
+			if [ ${SNAPSHOT_TIMESTAMP} -gt ${PROJECTION} ] && [ ${i} -gt 0 ] && [ "${SNAPSHOT_NAME}" != "${CURRENT_JOB}" ]
 			then
-				if [ ${NEXT_SNAPSHOT} -gt ${PROJECTIONS[$(( ${j} + 1 ))]} ] && [ ${LAST_KEPT_TO_NEXT_DELTA} -lt $(( ${INTERVAL} + ${DAY_IN_SECS} )) ]
+				NEXT_PROJECTION=`uclcmd get -f "${TEMPDATA_PATH}" -q .projections.$(( ${j} + 1 ))`
+				if [ ${NEXT_SNAPSHOT} -gt ${NEXT_PROJECTION} ] && [ ${LAST_KEPT_TO_NEXT_DELTA} -lt $(( ${INTERVAL} + ${DAY_IN_SECS} )) ]
 				then
-					SNAPSHOT_ACTION[${i}]="destroy"
+					uclcmd set -f "${TEMPDATA_PATH}" .snapshot_actions.${i} "destroy"
 				fi
 			else
 				NEXT_PROJECTION=0
 				while [ ${NEXT_PROJECTION} -eq 0 ] || [ ${NEXT_PROJECTION} -gt ${NEXT_SNAPSHOT_PLUS_INTERVAL} ]
 				do
-					NEXT_PROJECTION=${PROJECTIONS[$(( ${j} + 1 ))]}
+					NEXT_PROJECTION=`uclcmd get -f "${TEMPDATA_PATH}" -q .projections.$(( ${j} + 1 ))`
 					NEXT_SNAPSHOT_PLUS_INTERVAL=$(( ${NEXT_SNAPSHOT} + ${INTERVAL} ))
 					j=$(( ${j} + 1 ))
 				done
-				SNAPSHOT_ACTION[${i}]="keep"
+				uclcmd set -f "${TEMPDATA_PATH}" .snapshot_actions.${i} "keep"
 				LAST_SNAPSHOT_KEPT=${i}
 			fi
 		fi
 
-		if [ ${SIMULATION_MODE} = "yes" ]
-		then
-			echo "${SNAPSHOT_NAMES[${i}]} -> ${SNAPSHOT_ACTION[${i}]}" >> ${BACKUP_POOL_ROOT_PATH}/log/simulate.thin-snapshots.${POOL}@${BACKUP_POOL}.${NOW_DATE_TIME}.log
-		else
-			echo "${SNAPSHOT_NAMES[${i}]} -> ${SNAPSHOT_ACTION[${i}]}" >> ${BACKUP_POOL_ROOT_PATH}/log/thin-snapshots.${POOL}@${BACKUP_POOL}.${NOW_DATE_TIME}.log
-		fi
+		SNAPSHOT_ACTION=`uclcmd get -f "${TEMPDATA_PATH}" -q .snapshot_actions.${i}`
+		echo "${SNAPSHOT_NAME} -> ${SNAPSHOT_ACTION}" >> ${LOG_FILE_PATH}
 
-		if [ "${SNAPSHOT_ACTION[${i}]}" = "destroy" ]
+		if [ "${SNAPSHOT_ACTION}" = "destroy" ]
 		then
 			if [ ${SIMULATION_MODE} = "yes" ]
 			then
-				echo -e "${LBLU}zfs destroy ${SNAPSHOT_NAMES[${i}]}${NRML}"
+				echo -e "${LBLU}zfs destroy ${SNAPSHOT_NAME}${NRML}"
 			else
-				zfs destroy ${SNAPSHOT_NAMES[${i}]}
+				LAST_ERROR_COUNT=${ERROR_COUNT}
+				zfs destroy ${SNAPSHOT_NAME}
+				ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+				if [ ${ERROR_COUNT} -gt ${LAST_ERROR_COUNT} ]
+				then
+					echo -e "\nERROR: Failed to destroy snapshot '${SNAPSHOT_NAME}'!\n" >> ${LOG_FILE_PATH}
+				fi
 			fi
 		fi
 		i=$(( ${i} - 1 ))
 	done
 
+	# For completeness of log output to reflect what snapshots were kept.
+	SNAPSHOT_NAME=`uclcmd get -f "${TEMPDATA_PATH}" -q .snapshot_names.${i}`
+	echo "${SNAPSHOT_NAME} -> keep" >> ${LOG_FILE_PATH}
 }
 
 test_if_host ()
@@ -246,57 +277,85 @@ then
 	exit 1
 fi
 
-BACKUP_POOL_HEALTH=`zpool get -H health ${BACKUP_POOL} | awk '{print $3}' 2> /dev/null`
+BACKUP_POOL_HEALTH=`zpool get -H -o value health ${BACKUP_POOL} 2> /dev/null`
 if [ "${BACKUP_POOL_HEALTH}" != "ONLINE" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' appears to be unhealthy.\n       Aborting.\n"
 	exit 1
 fi
 
-POOL_ATTRIBUTES=`zpool get -H all ${POOL} 2> /dev/null`
+zfs list -H -o name "${FILESYSTEM}" > /dev/null 2>&1
 if [ ${?} -ne 0 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported.\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} The source filesystem '${FILESYSTEM}' does not appear to exist.\n       Aborting.\n"
 	exit 1
 fi
 
-POOL_HEALTH=`zpool get -H health ${POOL} | awk '{print $3}' 2> /dev/null`
-if [ "${POOL_HEALTH}" != "ONLINE" ]
+FILESYSTEM_POOL=`echo "${FILESYSTEM}" | cut -d"/" -f1`
+
+FILESYSTEM_POOL_ATTRIBUTES=`zpool get -H all ${FILESYSTEM_POOL} 2> /dev/null`
+if [ ${?} -ne 0 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy.\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} The source filesystem pool '${FILESYSTEM_POOL}' does not appear to be imported.\n       Aborting.\n"
 	exit 1
 fi
 
-BACKUP_POOL_ROOT_PATH=`zfs list -H ${BACKUP_POOL} | awk '{print $5}'`
-
-if [ -f ${BACKUP_POOL_ROOT_PATH}/last-backupz-error-${POOL}@${BACKUP_POOL}.inf ]
+FILESYSTEM_POOL_HEALTH=`zpool get -H -o value health ${FILESYSTEM_POOL} 2> /dev/null`
+if [ "${FILESYSTEM_POOL_HEALTH}" != "ONLINE" ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} The last backup from '${POOL}' to '${BACKUP_POOL}' failed!\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} The source filesystem pool '${FILESYSTEM_POOL}' appears to be unhealthy.\n       Aborting.\n"
 	exit 1
 fi
 
-if [ -f ${BACKUP_POOL_ROOT_PATH}/backupz-${POOL}-running.inf ]
+if [ ! -e "${HOST_CONF_PATH}" ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backup running for '${POOL}'!\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} The host config file \n       '${ORNG}${HOST_CONF_PATH}${NRML}'\n       appears to be missing.\n       Aborting.\n"
 	exit 1
 fi
 
-pgrep -fl "fdo-backupz-repair-state" > /dev/null 2>&1
+BACKUP_POOL_ROOT_PATH=`zfs list -H -o mountpoint ${BACKUP_POOL}`
+TEST_BACKUP_POOL=`df -t zfs ${BACKUP_POOL_ROOT_PATH} | tail -1 | awk '{print $1}'`
+if [ "${TEST_BACKUP_POOL}" != "${BACKUP_POOL}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The backup pool '${BACKUP_POOL}' does not appear to be mounted!\n       Aborting.\n"
+	exit 1
+fi
+
+CURRENT_JOB_STATE=`${UCL_CMD} get -f ${STATE_PATH} -q .pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_state 2> /dev/null`
+if [ "${CURRENT_JOB_STATE}" = "failed" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a failed job for '${FILESYSTEM}'!\n       Aborting.\n"
+	exit 1
+elif [ "${CURRENT_JOB_STATE}" = "running" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backup job running for '${FILESYSTEM}'!\n       Aborting.\n"
+	exit 1
+elif [ "${CURRENT_JOB_STATE}" = "repairing" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a repair job running for '${FILESYSTEM}'!\n       Aborting.\n"
+	exit 1
+elif [ "${CURRENT_JOB_STATE}" = "thinning" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a thin-snapshots job running for '${FILESYSTEM}'!\n       Aborting.\n"
+	exit 1
+elif [ "${CURRENT_JOB_STATE}" != "completed" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The backupz job for '${FILESYSTEM}' is not in 'completed' state!\n       Aborting.\n"
+	exit 1
+fi
+
+# Check that we are not currently running a repair backupz state operation.
+pgrep -fl "fdo-backupz-repair-state " > /dev/null 2>&1
 if [ ${?} -eq 0 ]
 then
-	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backup repair operation running!\n       Aborting.\n"
-	exit 1
-fi
-
-pgrep -fl "fdo-backupz-thin-snapshots" > /dev/null 2>&1
-if [ ${?} -eq 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} There appears to be another thin-snapshots operation running!\n       Aborting.\n"
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backupz repair operation running!\n       Aborting.\n"
 	exit 1
 fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
+
+ERROR_COUNT=0
 
 # Global dynamic variable declarations
 OFFSET=$(( ${OFFSET_DAYS} * ${DAY_IN_SECS} ))
@@ -306,28 +365,106 @@ INTERVAL=$(( ${INTERVAL_DAYS} * ${DAY_IN_SECS} ))
 if [ ! -d ${BACKUP_POOL_ROOT_PATH}/log ]
 then
 	zfs create -o mountpoint=/${BACKUP_POOL_ROOT_PATH}/log -o compression=on ${BACKUP_POOL}/log
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 fi
 
-# Get the last successful backup snaphot name
-LAST_SUCCESSFUL_BACKUP_SNAPSHOT=`cat ${BACKUP_POOL_ROOT_PATH}/last-successful-backupz-${POOL}@${BACKUP_POOL}.inf`
+# Create temp files and log file path variables.
+FILESYSTEM_FLAT=`echo "${FILESYSTEM}" | sed "s|/|__|g"`
+LOG_FILE_PATH="${BACKUP_POOL_ROOT_PATH}/log/thin-snapshots.${NOW_DATE_TIME}.${FILESYSTEM_FLAT}@${BACKUP_POOL}.log"
+TEMPDATA_PATH="/tmp/fdo-backupz-thin-snapshots.${NOW_DATE_TIME}.${FILESYSTEM_FLAT}@${BACKUP_POOL}.tempdata"
 
+# Get previously completed backupz job name from backupz state file.
+COMPLETED_JOB=`${UCL_CMD} get -f ${STATE_PATH} -q ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.completed_job_name" 2> /dev/null`
+if [ ${?} -ne 0 ] || [ "${COMPLETED_JOB}" = "null" ] || [ "${COMPLETED_JOB}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be no completed backupz job for this filesystem!\n       Aborting.\n"
+	exit 1
+fi
+
+echo -e "Beginning thin-snapshots for filesystem '${FILESYSTEM}'.\n" >> ${LOG_FILE_PATH}
+echo -e "Previous completed job: ${COMPLETED_JOB}" >> ${LOG_FILE_PATH}
+echo -e "Filesystem filter: ${FILTER}" >> ${LOG_FILE_PATH}
+echo -e "Simulation mode: ${SIMULATION_MODE}" >> ${LOG_FILE_PATH}
+echo -e "Offset (days): ${OFFSET_DAYS}" >> ${LOG_FILE_PATH}
+echo -e "Interval (days): ${INTERVAL_DAYS}\n" >> ${LOG_FILE_PATH}
+
+# Wait for backupz state to be unlocked.
+while [ -f ${STATE_PATH}.lock ]
+do
+	echo -e "\n${YELL}Waiting for backupz state lock file to be unlocked...${NRML}\n"
+	sleep 2
+done
+
+# Make a lock file recovery copy of the existing backupz state file.
+# We won't release this lock until the repair job is complete or exited, due to it's dangerous nature.
+touch ${STATE_PATH}
+cp ${STATE_PATH} ${STATE_PATH}.lock
+
+# Set the job state to 'thinning' for this job.
+${UCL_CMD} set -f ${STATE_PATH} ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_state" "thinning"
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+# If we hit any errors so far, let's not proceed and revert backupz state file.
+if [ ${ERROR_COUNT} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There was an unexpected error preparing the thin-snapshots job!\n       Aborting.\n"
+	mv ${STATE_PATH}.lock ${STATE_PATH}
+	echo -e "\nERROR: There was an unexpected error preparing the thin-snapshots job!\n       Aborting." >> ${LOG_FILE_PATH}
+	exit 2
+fi
+
+# ASSUME that preparation was successful, so let's remove the state lock and proceed.
+rm ${STATE_PATH}.lock
+
+# Display simulation mode in use if it is.
 if [ "${SIMULATION_MODE}" = "yes" ]
 then
 	echo -e "\n${YELL}   --- SIMULATION MODE ---   ${NRML}\n"
+	echo -e "\n   --- SIMULATION MODE ---   \n" >> ${LOG_FILE_PATH}
 fi
 
-
-if [ "${FILESYSTEM_FILTER}" != "" ]
+# Recursively run the thinning function on the target filesystem and all it decendants.
+if [ "${FILTER}" != "" ]
 then
-	for FILESYSTEM in `zfs list -H -t filesystem -o name -r ${BACKUP_POOL}/${POOL} | egrep "${FILESYSTEM_FILTER}"`
+	for FS_NAME in `zfs list -H -t filesystem -o name -r ${BACKUP_POOL}/${FILESYSTEM_FLAT} | egrep "${FILTER}"`
 	do
-		thin_snapshots_by_filesystem ${FILESYSTEM}
+		echo -e "\n${YELL}Thinning snapshots for filesystem '${NRML}${FS_NAME}${YELL}'...${NRML}"
+		echo -e "\nThinning snapshots for filesystem '${FS_NAME}'..." >> ${LOG_FILE_PATH}
+		thin_snapshots_by_filesystem ${FS_NAME}
 	done
 else
-	for FILESYSTEM in `zfs list -H -t filesystem -o name -r ${BACKUP_POOL}/${POOL}`
+	for FS_NAME in `zfs list -H -t filesystem -o name -r ${BACKUP_POOL}/${FILESYSTEM_FLAT}`
 	do
-		thin_snapshots_by_filesystem ${FILESYSTEM}
+		echo -e "\n${YELL}Thinning snapshots for filesystem '${NRML}${FS_NAME}${YELL}'...${NRML}"
+		echo -e "\nThinning snapshots for filesystem '${FS_NAME}'..." >> ${LOG_FILE_PATH}
+		thin_snapshots_by_filesystem ${FS_NAME}
 	done
 fi
+
+# Remove the temporary, arrays data file.
+rm ${TEMPDATA_PATH}
+
+# If we get here, we can ASSUME the thin-snapshots job has completed successfully, and set state variables accordingly.
+echo -e "\n${YELL}Setting backupz state variables to previous completed backup state...${NRML}\n"
+echo -e "\nSetting backupz state variables to previous completed backup state..." >> ${LOG_FILE_PATH}
+
+# Wait for backupz state to be unlocked.
+while [ -f ${STATE_PATH}.lock ]
+do
+	echo -e "\n${YELL}Waiting for backupz state lock file to be unlocked...${NRML}\n"
+	sleep 2
+done
+
+# Lock the backupz state with a lock file copy.
+cp ${STATE_PATH} ${STATE_PATH}.lock
+
+# Set the job state to 'completed' for this filesystem.
+${UCL_CMD} set -f ${STATE_PATH} ".pools.${BACKUP_POOL}.filesystems.${FILESYSTEM}.job_state" "completed"
+
+# ASSUME that thin-snapshots was successful, so let's remove the state lock and proceed.
+rm ${STATE_PATH}.lock
+
+echo -e "\nBackupz thin-snapshots for filesystem '${FILESYSTEM}' finished." >> ${LOG_FILE_PATH}
+echo -e "\n${LGRN}Backupz thin-snapshots state for filesystem '${NRML}${FILESYSTEM}${LGRN}' finished!${NRML}\n"
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-file_server-check-user-folder-quota b/scripts/usr/local/sbin/fdo-file_server-check-user-folder-quota
--- a/scripts/usr/local/sbin/fdo-file_server-check-user-folder-quota
+++ b/scripts/usr/local/sbin/fdo-file_server-check-user-folder-quota
@@ -30,7 +30,10 @@ SCRIPT_NAME=`basename ${0}`
 SITE_NAME="${1}"
 USERNAME="${2}"
 NUM_MANDATORY_ARGS=2
-WEBDAV_ROOT_FS=`cat /usr/local/etc/fdo/webdav_root_fs.conf`
+RECIPE_NAME="file_server"
+UCL_CMD="/usr/local/bin/uclcmd"
+FDO_CONFIG_ROOT=${FDO_CONFIG_ROOT:-"/usr/local/etc/fdo"}
+RECIPE_CONF_PATH=${RECIPE_CONF_PATH:-"${FDO_CONFIG_ROOT}/recipe.conf"}
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -103,6 +106,28 @@ test_if_host ()
 	fi
 }
 
+find_jails_from_recipe_name ()
+{
+	FIND_RECIPE_NAME="${1}"
+	FOUND_RECIPE_JAILS=""
+	for TEST_JAIL_NAME in `ls -1 /jls | cut -d/ -f1`
+	do
+		if [ -f "/jls/${TEST_JAIL_NAME}${RECIPE_CONF_PATH}" ]
+		then
+			TEST_RECIPE_NAME=`${UCL_CMD} get -f /jls/${TEST_JAIL_NAME}${RECIPE_CONF_PATH} -q .general.jail_recipe`
+			if [ "${TEST_RECIPE_NAME}" = "${FIND_RECIPE_NAME}" ]
+			then
+				if [ "${FOUND_RECIPE_JAILS}" = "" ]
+				then
+					FOUND_RECIPE_JAILS="${TEST_JAIL_NAME}"
+				else
+					FOUND_RECIPE_JAILS="${FOUND_RECIPE_JAILS} ${TEST_JAIL_NAME}"
+				fi
+			fi
+		fi
+	done
+}
+
 
 ##### SANITY TESTS #############################################################
 
@@ -133,9 +158,39 @@ fi
 
 ERROR_COUNT=0
 
+# Let's try to find the jail
+find_jails_from_recipe_name ${RECIPE_NAME}
+NUM_FOUND_JAILS=`echo ${FOUND_RECIPE_JAILS} | wc -w`
+if [ ${NUM_FOUND_JAILS} -lt 1 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Unable to find a '${RECIPE_NAME}' recipe jail!\n       Aborting.\n"
+	usage
+	exit 1
+fi
+if [ ${NUM_FOUND_JAILS} -lt 2 ]
+then
+	JAIL_NAME=${FOUND_RECIPE_JAILS}
+else
+	echo -e "\n${ORNG}WARNING:${NRML} More than one '${RECIPE_NAME}' recipe jail was found!\         Using the first found recipe jail config.\n"
+	JAIL_NAME=`echo ${FOUND_RECIPE_JAILS} | cut -d" " -f1`
+fi
+
+# Prefix the recipe.conf path with the jail path.
+RECIPE_CONF_PATH="/jls/${JAIL_NAME}${RECIPE_CONF_PATH}"
+
+# Get the webdav root filesystem name from the file_server recipe config file.
+WEBDAV_ROOT_FS=`${UCL_CMD} get -f ${RECIPE_CONF_PATH} -q .webdav.root_filesystem`
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+if [ "${WEBDAV_ROOT_FS}" = "" ] || [ "${WEBDAV_ROOT_FS}" = "null" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The WebDAV root filesystem specified in the config file\n       '${RECIPE_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
 # Display the quota of the ZFS filesystem of the file_server user folder.
 zfs get quota ${WEBDAV_ROOT_FS}/${SITE_NAME}/users/${USERNAME}
-
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
diff --git a/scripts/usr/local/sbin/fdo-file_server-create-user-folder b/scripts/usr/local/sbin/fdo-file_server-create-user-folder
--- a/scripts/usr/local/sbin/fdo-file_server-create-user-folder
+++ b/scripts/usr/local/sbin/fdo-file_server-create-user-folder
@@ -30,11 +30,10 @@ SCRIPT_NAME=`basename ${0}`
 SITE_NAME="${1}"
 USERNAME="${2}"
 NUM_MANDATORY_ARGS=2
-WEBDAV_ROOT_FS=`cat /usr/local/etc/fdo/webdav_root_fs.conf`
-WEBDAV_ROOT_MOUNTPOINT=`cat /usr/local/etc/fdo/webdav_root_mountpoint.conf`
-WEBDAV_UID=`cat /usr/local/etc/fdo/webdav_userid.conf`
-WEBDAV_GID=`cat /usr/local/etc/fdo/webdav_groupid.conf`
-USER_FOLDER_QUOTA=`cat /usr/local/etc/fdo/file_server-default-user-folder-quota.conf`
+RECIPE_NAME="file_server"
+UCL_CMD="/usr/local/bin/uclcmd"
+FDO_CONFIG_ROOT=${FDO_CONFIG_ROOT:-"/usr/local/etc/fdo"}
+RECIPE_CONF_PATH=${RECIPE_CONF_PATH:-"${FDO_CONFIG_ROOT}/recipe.conf"}
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -107,6 +106,28 @@ test_if_host ()
 	fi
 }
 
+find_jails_from_recipe_name ()
+{
+	FIND_RECIPE_NAME="${1}"
+	FOUND_RECIPE_JAILS=""
+	for TEST_JAIL_NAME in `ls -1 /jls | cut -d/ -f1`
+	do
+		if [ -f "/jls/${TEST_JAIL_NAME}${RECIPE_CONF_PATH}" ]
+		then
+			TEST_RECIPE_NAME=`${UCL_CMD} get -f /jls/${TEST_JAIL_NAME}${RECIPE_CONF_PATH} -q .general.jail_recipe`
+			if [ "${TEST_RECIPE_NAME}" = "${FIND_RECIPE_NAME}" ]
+			then
+				if [ "${FOUND_RECIPE_JAILS}" = "" ]
+				then
+					FOUND_RECIPE_JAILS="${TEST_JAIL_NAME}"
+				else
+					FOUND_RECIPE_JAILS="${FOUND_RECIPE_JAILS} ${TEST_JAIL_NAME}"
+				fi
+			fi
+		fi
+	done
+}
+
 
 ##### SANITY TESTS #############################################################
 
@@ -144,11 +165,83 @@ fi
 
 ERROR_COUNT=0
 
+# Let's try to find the jail
+find_jails_from_recipe_name ${RECIPE_NAME}
+NUM_FOUND_JAILS=`echo ${FOUND_RECIPE_JAILS} | wc -w`
+if [ ${NUM_FOUND_JAILS} -lt 1 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Unable to find a '${RECIPE_NAME}' recipe jail!\n       Aborting.\n"
+	usage
+	exit 1
+fi
+if [ ${NUM_FOUND_JAILS} -lt 2 ]
+then
+	JAIL_NAME=${FOUND_RECIPE_JAILS}
+else
+	echo -e "\n${ORNG}WARNING:${NRML} More than one '${RECIPE_NAME}' recipe jail was found!\         Using the first found recipe jail config.\n"
+	JAIL_NAME=`echo ${FOUND_RECIPE_JAILS} | cut -d" " -f1`
+fi
+
+# Prefix the recipe.conf path with the jail path.
+RECIPE_CONF_PATH="/jls/${JAIL_NAME}${RECIPE_CONF_PATH}"
+
+# Get the webdav root filesystem name from the file_server recipe config file.
+WEBDAV_ROOT_FS=`${UCL_CMD} get -f ${RECIPE_CONF_PATH} -q .webdav.root_filesystem`
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+if [ "${WEBDAV_ROOT_FS}" = "" ] || [ "${WEBDAV_ROOT_FS}" = "null" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The WebDAV root filesystem specified in the config file\n       '${RECIPE_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+# Get the webdav root mountpoint from the file_server recipe config file.
+WEBDAV_ROOT_MOUNTPOINT=`${UCL_CMD} get -f ${RECIPE_CONF_PATH} -q .webdav.root_mountpoint`
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+if [ "${WEBDAV_ROOT_MOUNTPOINT}" = "" ] || [ "${WEBDAV_ROOT_MOUNTPOINT}" = "null" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The WebDAV root mountpoint specified in the config file\n       '${RECIPE_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+# Get the webdav user id (UID) from the file_server recipe config file.
+WEBDAV_UID=`${UCL_CMD} get -f ${RECIPE_CONF_PATH} -q .webdav.userid`
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+if [ "${WEBDAV_UID}" = "" ] || [ "${WEBDAV_UID}" = "null" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The WebDAV userid specified in the config file\n       '${RECIPE_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+# Get the webdav group id (GID) from the file_server recipe config file.
+WEBDAV_GID=`${UCL_CMD} get -f ${RECIPE_CONF_PATH} -q .webdav.groupid`
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+if [ "${WEBDAV_GID}" = "" ] || [ "${WEBDAV_GID}" = "null" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The WebDAV groupid specified in the config file\n       '${RECIPE_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+# Get the default user folder quota from the file_server recipe config file.
+USER_FOLDER_QUOTA=`${UCL_CMD} get -f ${RECIPE_CONF_PATH} -q .general.default_user_folder_quota`
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+if [ "${USER_FOLDER_QUOTA}" = "" ] || [ "${USER_FOLDER_QUOTA}" = "null" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The default user folder quota specified in the config file\n       '${RECIPE_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
 # Create the ZFS filesystem of the file_server user folder.
 zfs create -o quota=${USER_FOLDER_QUOTA} -o casesensitivity=insensitive -o mountpoint=${WEBDAV_ROOT_MOUNTPOINT}/${SITE_NAME}/users/${USERNAME} ${WEBDAV_ROOT_FS}/${SITE_NAME}/users/${USERNAME}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
 # Change ownership of the file_server user folder mountpoint.
 chown -R ${WEBDAV_UID}:${WEBDAV_GID} ${WEBDAV_ROOT_MOUNTPOINT}/${SITE_NAME}/users/${USERNAME}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
 
 if [ ${ERROR_COUNT} -gt 0 ]
diff --git a/scripts/usr/local/sbin/fdo-hotdesk-add-user b/scripts/usr/local/sbin/fdo-hotdesk-add-user
--- a/scripts/usr/local/sbin/fdo-hotdesk-add-user
+++ b/scripts/usr/local/sbin/fdo-hotdesk-add-user
@@ -31,25 +31,9 @@ USERNAME="${1}"
 DISPLAY_NAME="${2}"
 NUM_MANDATORY_ARGS=2
 UCL_CMD="/usr/local/bin/uclcmd"
-FDO_CONFIG_ROOT="/usr/local/etc/fdo"
-HOME_ZFS_NAME=`cat ${FDO_CONFIG_ROOT}/hotdesk-home-zfs-name.conf`
-DEFAULT_LAN_SUBNET_B="10.0"
-CONFIG_LAN_NET_IFACE=`${UCL_CMD} get -f ${HOST_CONF_PATH} -q .network.interface.lan.id`
-if [ ${?} -ne 0 ] || [ "${CONFIG_LAN_NET_IFACE}" = "null" ] || [ "${CONFIG_LAN_NET_IFACE}" = "" ]
-then
-    SET_LAN_SUBNET_B="${DEFAULT_LAN_SUBNET_B}"
-else
-    DETECTED_LAN_SUBNET_B=`ifconfig ${CONFIG_LAN_NET_IFACE} | grep "inet.*netmask 0xffff0000" | awk '{print $2}' | sort | head -1 | cut -d. -f1,2`
-    if [ "${DETECTED_LAN_SUBNET_B}" = "" ]
-    then
-        SET_LAN_SUBNET_B="${DEFAULT_LAN_SUBNET_B}"
-    else
-        SET_LAN_SUBNET_B="${DETECTED_LAN_SUBNET_B}"
-    fi
-fi
-FDO_LAN_SUBNET_B=${FDO_LAN_SUBNET_B:-"${SET_LAN_SUBNET_B}"}
-NFS_SUBNET_C=${NFS_SUBNET_C:-"${FDO_LAN_SUBNET_B}.40"}
-NFS_SUBNET_MASK=${NFS_SUBNET_MASK:-"255.255.255.0"}
+FDO_CONFIG_ROOT=${FDO_CONFIG_ROOT:-"/usr/local/etc/fdo"}
+HOST_CONF_PATH=${HOST_CONF_PATH:-"${FDO_CONFIG_ROOT}/host.conf"}
+HOTDESK_CONF_PATH=${HOTDESK_CONF_PATH:-"${FDO_CONFIG_ROOT}/hotdesk.conf"}
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -194,9 +178,18 @@ then
 fi
 
 # Check that we are not currently running a backupz operation.
-ps aux | grep "backupz"  | grep -v "grep backupz"
-if [ ${?} -eq 0 ]; then
-	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\n       Aborting.\n"
+pgrep -fl "fdo-backupz " > /dev/null 2>&1
+if [ ${?} -eq 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backupz operation running!\n       Aborting.\n"
+	exit 1
+fi
+
+# Check that we are not currently running a repair backupz state operation.
+pgrep -fl "fdo-backupz-repair-state " > /dev/null 2>&1
+if [ ${?} -eq 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backupz repair operation running!\n       Aborting.\n"
 	exit 1
 fi
 
@@ -204,6 +197,43 @@ fi
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
+
+# Get hotdesk users' home folder  root filesystem from config files.
+HOME_POOL=`${UCL_CMD} get -f ${HOST_CONF_PATH} -q .storage.hotdesk_pool`
+if [ ${?} -ne 0 ] || [ "${HOST_POOL}" = "null" ] || [ "${HOST_POOL}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The Hotdesk home pool specified in the config file\n       '${HOST_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+HOME_FS=`${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .general.root_filesystem`
+if [ ${?} -ne 0 ] || [ "${HOTDESK_POOL}" = "null" ] || [ "${HOTDESK_POOL}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The Hotdesk home root filesystem specified in the config file\n       '${HOTDESK_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+HOME_ZFS_NAME="${HOME_POOL}/${HOME_FS}"
+
+# Determine the NFS subnet and subnet mask.
+DEFAULT_LAN_SUBNET_B="10.0"
+CONFIG_LAN_NET_IFACE=`${UCL_CMD} get -f ${HOST_CONF_PATH} -q .network.interface.lan.id`
+if [ ${?} -ne 0 ] || [ "${CONFIG_LAN_NET_IFACE}" = "null" ] || [ "${CONFIG_LAN_NET_IFACE}" = "" ]
+then
+	echo -e "\n${ORNG}WARNING:${NRML} Unable to retrieve the LAN network interface identifier in the config file '${HOST_CONF_PATH}'!\n"
+    SET_LAN_SUBNET_B="${DEFAULT_LAN_SUBNET_B}"
+else
+    DETECTED_LAN_SUBNET_B=`ifconfig ${CONFIG_LAN_NET_IFACE} | grep "inet.*netmask 0xffff0000" | awk '{print $2}' | sort | head -1 | cut -d. -f1,2`
+    if [ "${DETECTED_LAN_SUBNET_B}" = "" ]
+    then
+        SET_LAN_SUBNET_B="${DEFAULT_LAN_SUBNET_B}"
+    else
+        SET_LAN_SUBNET_B="${DETECTED_LAN_SUBNET_B}"
+    fi
+fi
+FDO_LAN_SUBNET_B=${FDO_LAN_SUBNET_B:-"${SET_LAN_SUBNET_B}"}
+NFS_SUBNET_C=${NFS_SUBNET_C:-"${FDO_LAN_SUBNET_B}.40"}
+NFS_SUBNET_MASK=${NFS_SUBNET_MASK:-"255.255.255.0"}
 
 # Add new NIS user locally
 question_yes_no "\nWould you like to specify the UID of the new user?"
diff --git a/scripts/usr/local/sbin/fdo-hotdesk-remove-user b/scripts/usr/local/sbin/fdo-hotdesk-remove-user
--- a/scripts/usr/local/sbin/fdo-hotdesk-remove-user
+++ b/scripts/usr/local/sbin/fdo-hotdesk-remove-user
@@ -28,7 +28,9 @@
 
 SCRIPT_NAME=`basename ${0}`
 USERNAME="${1}"
-HOME_ZFS_NAME=`cat /usr/local/etc/fdo/hotdesk-home-zfs-name.conf`
+FDO_CONFIG_ROOT=${FDO_CONFIG_ROOT:-"/usr/local/etc/fdo"}
+HOST_CONF_PATH=${HOST_CONF_PATH:-"${FDO_CONFIG_ROOT}/host.conf"}
+HOTDESK_CONF_PATH=${HOTDESK_CONF_PATH:-"${FDO_CONFIG_ROOT}/hotdesk.conf"}
 NUM_MANDATORY_ARGS=1
 FORCE_MODE="no"
 DEFAULT_BACKUP_POOL="backup"
@@ -154,6 +156,23 @@ fi
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
+
+# Get hotdesk users' home folder  root filesystem from config files.
+HOME_POOL=`${UCL_CMD} get -f ${HOST_CONF_PATH} -q .storage.hotdesk_pool`
+if [ ${?} -ne 0 ] || [ "${HOST_POOL}" = "null" ] || [ "${HOST_POOL}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The Hotdesk home pool specified in the config file\n       '${HOST_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+HOME_FS=`${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .general.root_filesystem`
+if [ ${?} -ne 0 ] || [ "${HOTDESK_POOL}" = "null" ] || [ "${HOTDESK_POOL}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The Hotdesk home root filesystem specified in the config file\n       '${HOTDESK_CONF_PATH}'\n       is not valid! Aborting.\n"
+	exit 1
+fi
+
+HOME_ZFS_NAME="${HOME_POOL}/${HOME_FS}"
 
 # Destroy the hotdesk users' home directory filesystem.
 echo -e "\n${YELL}Destroying the users' home filesystem...${NRML}\n"
