script 'fdo-sshfs-add-connection': Add sanity test for existence of sshfsd_shares.conf. Various other fixes.

diff --git a/scripts/usr/local/sbin/fdo-sshfs-add-connection b/scripts/usr/local/sbin/fdo-sshfs-add-connection
--- a/scripts/usr/local/sbin/fdo-sshfs-add-connection
+++ b/scripts/usr/local/sbin/fdo-sshfs-add-connection
@@ -256,6 +256,13 @@ then
 	exit 3
 fi
 
+if [ ! -f ${SSHFSD_CONF_PATH} ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The sshfs daemon config file '${SSHFSD_CONF_PATH}' does not exist!\n       Aborting.\n"
+	usage
+	exit 4
+fi
+
 # Test that the remote user is valid
 TEST=`echo "${REMOTE_USER}" | sed "s/^[a-zA-Z0-9._-]\{3,\}$//" | wc -w`
 if [ ${TEST} -ne 0 ]
@@ -263,7 +270,7 @@ then
 	echo -e "\n${LRED}ERROR:${NRML} The remote user '${REMOTE_USER}' is invalid!"
 	echo -e "       It must only contain letters, numbers, hyphens, underscores and periods "
 	echo -e "       with a minumum of 3 characters.\n"
-	exit 4
+	exit 5
 fi
 
 # Test that the remote host is valid.
@@ -276,12 +283,12 @@ then
 	echo -e "       It must only contain letters, numbers, periods and hyphens."
 	echo -e "       It must not begin or end with a hyphen or a period."
 	echo -e "       Aborting.\n"
-	exit 5
+	exit 6
 fi
 
 # TODO: Test that the remote_path and local_path are valid. Considering that
 # UNIX paths can contain just about any character, this may not be practical.
-# Use exit codes 6 and 7.
+# Use exit codes 7 and 8.
 
 
 test_valid_integer "${REMOTE_PORT}" 1 65535
@@ -290,7 +297,7 @@ then
 	echo -e "\n${LRED}ERROR:${NRML} The port number '${REMOTE_PORT}' is invalid!"
 	echo -e "       It must be a number between 1 and 65535."
 	echo -e "       Aborting.\n"
-	exit 8
+	exit 9
 fi
 
 ##### MAIN EXECUTION THREAD ####################################################
@@ -304,7 +311,7 @@ then
 	echo -e "\n${LRED}ERROR:${NRML} A connection already exists with the local path;"
 	echo -e "       '${LOCAL_PATH}'"
 	echo -e "       Aborting.\n"
-	exit 9
+	exit 10
 fi
 
 # Check if the local_path is a valid directory
@@ -313,7 +320,7 @@ then
 	echo -e "\n${LRED}ERROR:${NRML} Cannot find the local path;"
 	echo -e "       '${LOCAL_PATH}'"
 	echo -e "       Aborting.\n"
-	exit 10
+	exit 11
 fi
 
 # Warn if the local_path is not empty
@@ -322,42 +329,47 @@ if [ ${TEST} -gt 0 ]
 then
 	echo -e "\n${ORNG}WARNING:${NRML} The following local path is not empty;"
 	echo -e "         '${LOCAL_PATH}'\n"
-	question_yes_no "Would you like to continue regardless of the mount state?"
+	question_yes_no "Would you like to continue regardless of the mountpoint state?"
 	if [ "${ANSWER}" = "no" ]
 	then
-		exit 11
+		exit 12
 	fi
 fi
 
-# Ask if we should create an ssh key and copy it the remote users' authorized keys
+# Ask if we should create an ssh key and copy it to the remote users' authorized keys
 # for an unattended login.
 question_yes_no "\nUNATTENDED LOGIN: Would you like to use an SSH key to authenticate as the remote user?"
 if [ "${ANSWER}" = "yes" ]
 then
 	# Flatten the local_path so we can use it in a file name
 	LOCAL_PATH_FLAT=`echo ${LOCAL_PATH} | sed "s/\//_/g"`
+	SSHFSD_KEY="${SSHFSD_KEY_PREFIX}${LOCAL_PATH_FLAT}"
 	echo -e ""
 	# Generate an SSH key and store it in a programatically accessible place
-	ssh-keygen -q -f "${SSHFSD_KEY_PREFIX}${LOCAL_PATH_FLAT}" -N ""	
+	ssh-keygen -q -f "${SSHFSD_KEY}" -N ""
 	if [ ${?} -ne 0 ]
 	then
 		echo -e "\n${LRED}ERROR:${NRML} A problem occured generating the SSH key file;"
-		echo -e "       '${SSHFSD_KEY_PREFIX}${LOCAL_PATH_FLAT}'"
+		echo -e "       '${SSHFSD_KEY}'"
 		echo -e "       Aborting.\n"
-		exit 12
+		rm ${SSHFSD_KEY}
+		rm ${SSHFSD_KEY}.pub
+		exit 13
 	fi
 
 	echo -e "\n${YELL}SSH key generated!${NRML}"
 	echo -e "\n${YELL}Next we need to copy it to the remote users' authorized_keys file.\nEnter the remote users password when prompted.${NRML}\n"
 
 	# Copy the SSH key to the remote users' authorized keys file (~/.ssh/authorized_keys)
-	ssh-copy-id -p "${REMOTE_PORT}" -i "${SSHFSD_KEY_PREFIX}${LOCAL_PATH_FLAT}" "${REMOTE_USER}@${REMOTE_HOST}"
+	ssh-copy-id -p "${REMOTE_PORT}" -i "${SSHFSD_KEY}" "${REMOTE_USER}@${REMOTE_HOST}"
 	if [ ${?} -ne 0 ]
 	then
 		echo -e "\n${LRED}ERROR:${NRML} A problem occured copying the SSH key file to the remote user/host;"
 		echo -e "       '${REMOTE_USER}@${REMOTE_HOST}'"
 		echo -e "       Aborting.\n"
-		exit 13
+		rm ${SSHFSD_KEY}
+		rm ${SSHFSD_KEY}.pub
+		exit 14
 	fi
 
 fi
@@ -383,7 +395,7 @@ echo -e ""
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 14
+	exit 15
 fi
 
 ################################################################################
