Scripts: improved sanity tests for 'fdo-backupz-destroy-snapshot' and 'fdo-backupz-destroy-filesystem'.

diff --git a/scripts/usr/local/sbin/fdo-backupz-destroy-filesystem b/scripts/usr/local/sbin/fdo-backupz-destroy-filesystem
--- a/scripts/usr/local/sbin/fdo-backupz-destroy-filesystem
+++ b/scripts/usr/local/sbin/fdo-backupz-destroy-filesystem
@@ -27,8 +27,8 @@
 ##### GLOBAL STATIC VARIABLE DECLARATIONS ######################################
 
 SCRIPT_NAME=`basename ${0}`
-POOL=${1}
-FILESYSTEM_PATTERN=${2}
+POOL="${1}"
+FILESYSTEM_PATTERN="${2}"
 NUM_MANDATORY_ARGS=2
 RECURSE=""
 SIMULATION_MODE="no"
@@ -112,6 +112,19 @@ then
 	exit 2
 fi
 
+POOL_ATTRIBUTES=`zpool list -H | egrep "^${POOL}  " 2> /dev/null`
+if [ $? -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported."
+	exit 3
+fi
+
+POOL_HEALTH=`echo ${POOL_ATTRIBUTES} | awk '{print $9}'`
+if [ "${POOL_HEALTH}" != "ONLINE" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy."
+	exit 4
+fi
 
 ##### MAIN EXECUTION THREAD ####################################################
 
@@ -141,7 +154,7 @@ fi
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 3
+	exit 5
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-backupz-destroy-snapshot b/scripts/usr/local/sbin/fdo-backupz-destroy-snapshot
--- a/scripts/usr/local/sbin/fdo-backupz-destroy-snapshot
+++ b/scripts/usr/local/sbin/fdo-backupz-destroy-snapshot
@@ -108,6 +108,19 @@ then
 	exit 2
 fi
 
+POOL_ATTRIBUTES=`zpool list -H | egrep "^${POOL}  " 2> /dev/null`
+if [ $? -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' does not appear to be imported."
+	exit 3
+fi
+
+POOL_HEALTH=`echo ${POOL_ATTRIBUTES} | awk '{print $9}'`
+if [ "${POOL_HEALTH}" != "ONLINE" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The pool '${POOL}' appears to be unhealthy."
+	exit 4
+fi
 
 ##### MAIN EXECUTION THREAD ####################################################
 
@@ -137,7 +150,7 @@ fi
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 3
+	exit 5
 fi
 
 ################################################################################
