Hotdesk subsystem scripts: various improvements to adding, removing and listing hotdesk users.

diff --git a/scripts/usr/local/sbin/fdo-hotdesk-add-user b/scripts/usr/local/sbin/fdo-hotdesk-add-user
--- a/scripts/usr/local/sbin/fdo-hotdesk-add-user
+++ b/scripts/usr/local/sbin/fdo-hotdesk-add-user
@@ -38,6 +38,8 @@ HOTDESK_CONF_PATH=${HOTDESK_CONF_PATH:-"${FDO_CONFIG_ROOT}/hotdesk.conf"}
 IS_INTERACTIVE="yes"
 USER_UID=${USER_UID:-""}
 USER_PASSWORD=${USER_PASSWORD:-""}
+HOTDESK_UID_MIN=5001
+HOTDESK_UID_MAX=9999
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -554,7 +556,7 @@ backup_file ${HOTDESK_CONF_PATH} ${SCRIPT_NAME}
 ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
 # Add new NIS user locally.
-if [ "${IS_INTERACTIVE}" = "yes" ]
+if [ "${IS_INTERACTIVE}" = "yes" ] && [ "${USER_UID}" = "" ]
 then
 	question_yes_no "\nWould you like to specify the UID of the new user?"
 	if [ "${ANSWER}" = "yes" ]
@@ -563,9 +565,10 @@ then
 		while [ "${USER_UID}" = "" ]
 		do
 			echo -e ""
-			readee -p "${LCYN}Enter the new users' UID: ${NRML}" USER_UID_TEMP
+			readee -p "${LCYN}Enter the new users' UID [${HOTDESK_UID_MIN}-${HOTDESK_UID_MAX}]: ${NRML}" USER_UID_TEMP
+
 			# Check that the UID is valid.
-			test_valid_integer "${USER_UID_TEMP}" 1000 100000
+			test_valid_integer "${USER_UID_TEMP}" ${HOTDESK_UID_MIN} ${HOTDESK_UID_MAX}
 			if [ "${VALID_INTEGER}" = "yes" ]
 			then
 				question_yes_no "\nYou have entered '${NRML}${USER_UID_TEMP}${LCYN}' as the new users' UID.\nIs this correct?"
@@ -574,40 +577,91 @@ then
 					USER_UID=${USER_UID_TEMP}
 				fi
 			else
-				echo -e "\n${LRED}ERROR:${NRML} The new users' UID can not be '${ORNG}${USER_UID}${NRML}'."
-				echo -e "       It must contain only numbers, greater than 1000 and less than 100000.\n"
+				echo -e "\n${LRED}ERROR:${NRML} The new users' UID can not be '${ORNG}${USER_UID_TEMP}${NRML}'."
+				echo -e "       It must contain only numbers, greater than ${HOTDESK_UID_MIN} and less than ${HOTDESK_UID_MAX}.\n"
 			fi
 		done
 	fi
 fi
+
 echo -e ""
-if [ "${USER_UID}" != "" ]
+
+# Get lists of in use uid numbers from local, nis and hotdesk.conf.
+ALL_CURRENT_LOCAL_UIDS=`cat /etc/passwd | sed "/^#/d" | cut -d: -f3 | sed "s:[^0-9]*::g"`
+ALL_CURRENT_NIS_UIDS=`ypcat passwd | sed "/^#/d" | cut -d: -f3 | sed "s:[^0-9]*::g"`
+ALL_CURRENT_UCL_UIDS=""
+USER_INDEX=0
+while [ `${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}` != "null" ]
+do
+	UCL_USER_UID=`${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}.uid`
+	ALL_CURRENT_UCL_UIDS="${ALL_CURRENT_UCL_UIDS}${CARRIAGE_RETURN}${UCL_USER_UID}"
+	USER_INDEX=$(( ${USER_INDEX} + 1 ))
+done
+
+if [ "${USER_UID}" = "" ]
 then
-	test_valid_integer "${USER_UID}" 1000 100000
-	if [ "${VALID_INTEGER}" = "no" ]
+	# We get here if the uid is unspecified, let us automatically assign the next available.
+
+	# Get next available uid within allowed range.
+	NEXT_USER_UID_FOUND=false
+	NEXT_USER_UID=${HOTDESK_UID_MIN}
+	while [ ${NEXT_USER_UID_FOUND} = false ] && [ ${NEXT_USER_UID} -lt ${HOTDESK_UID_MAX} ]
+	do
+		echo "${ALL_CURRENT_LOCAL_UIDS}" | grep -w "${NEXT_USER_UID}" > /dev/null 2>&1
+		RESULT1=${?}
+		echo "${ALL_CURRENT_NIS_UIDS}" | grep -w "${NEXT_USER_UID}" > /dev/null 2>&1
+		RESULT2=${?}
+		echo "${ALL_CURRENT_UCL_UIDS}" | grep -w "${NEXT_USER_UID}" > /dev/null 2>&1
+		RESULT3=${?}
+		if [ ${RESULT1} -ne 0 ] && [ ${RESULT2} -ne 0 ] && [ ${RESULT3} -ne 0 ]
+		then
+			NEXT_USER_UID_FOUND=true
+			USER_UID=${NEXT_USER_UID}
+		fi
+		NEXT_USER_UID=$(( ${NEXT_USER_UID} + 1 ))
+	done
+	if [ ${NEXT_USER_UID_FOUND} = false ]
 	then
-		echo -e "\n${LRED}ERROR:${NRML} The USER_UID specified is not valid!\n       Aborting."
+		echo -e "\n${LRED}ERROR:${NRML} Could not find the next available UID for the Hotdesk user!\n       Aborting."
 		undo_add_user
 		exit 1
 	fi
-	if [ "${USER_PASSWORD}" = "" ]
-	then
-		pw useradd -n ${USERNAME} -c "${DISPLAY_NAME}" -d /home/${USERNAME} -g users -s /bin/bash -u ${USER_UID}
-		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
-	else
-		echo "${USER_PASSWORD}" | pw useradd -n ${USERNAME} -c "${DISPLAY_NAME}" -d /home/${USERNAME} -g users -s /bin/bash -u ${USER_UID} -h 0
-		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
-	fi
 else
-	if [ "${USER_PASSWORD}" = "" ]
+	# Test if specified uid is valid.
+	test_valid_integer "${USER_UID}" ${HOTDESK_UID_MIN} ${HOTDESK_UID_MAX}
+	if [ "${VALID_INTEGER}" = "no" ]
 	then
-		pw useradd -n ${USERNAME} -c "${DISPLAY_NAME}" -d /home/${USERNAME} -g users -s /bin/bash
-		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
-	else
-		echo "${USER_PASSWORD}" | pw useradd -n ${USERNAME} -c "${DISPLAY_NAME}" -d /home/${USERNAME} -g users -s /bin/bash -h 0
-		ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+		echo -e "\n${LRED}ERROR:${NRML} The Hotdesk user UID specified is not valid!\n       Aborting."
+		undo_add_user
+		exit 1
+	fi
+
+	# Test if specified uid is not already in use.
+	echo "${ALL_CURRENT_LOCAL_UIDS}" | grep -w "${USER_UID}" > /dev/null 2>&1
+	RESULT1=${?}
+	echo "${ALL_CURRENT_NIS_UIDS}" | grep -w "${USER_UID}" > /dev/null 2>&1
+	RESULT2=${?}
+	echo "${ALL_CURRENT_UCL_UIDS}" | grep -w "${USER_UID}" > /dev/null 2>&1
+	RESULT3=${?}
+	if [ ${RESULT1} -eq 0 ] || [ ${RESULT2} -eq 0 ] || [ ${RESULT3} -eq 0 ]
+	then
+		echo -e "\n${LRED}ERROR:${NRML} The Hotdesk user UID specified is already in use!\n       Aborting."
+		undo_add_user
+		exit 1
 	fi
 fi
+
+# Add the user to the local system.
+if [ "${USER_PASSWORD}" = "" ]
+then
+	pw useradd -n ${USERNAME} -c "${DISPLAY_NAME}" -d /home/${USERNAME} -g users -s /bin/bash -u ${USER_UID}
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+else
+	echo "${USER_PASSWORD}" | pw useradd -n ${USERNAME} -c "${DISPLAY_NAME}" -d /home/${USERNAME} -g users -s /bin/bash -u ${USER_UID} -h 0
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+fi
+
+# If using interactive mode and password is not specified via environment variable, set it manually.
 if [ "${IS_INTERACTIVE}" = "yes" ] && [ "${USER_PASSWORD}" = "" ]
 then
 	echo -e ""
@@ -666,6 +720,8 @@ cat /etc/master.passwd | egrep "^${USERNAME}:" >> master.passwd
 ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
 echo -e ""
+
+# Update the new NIS domain.
 make
 ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
@@ -694,6 +750,7 @@ then
 	exit 2
 fi
 
+# Since everything seems successful, we can remove the backup configs.
 undo_backup_file /etc/exports ${SCRIPT_NAME}
 undo_backup_file /var/yp/master.passwd ${SCRIPT_NAME}
 undo_backup_file /etc/passwd ${SCRIPT_NAME}
diff --git a/scripts/usr/local/sbin/fdo-hotdesk-list-users b/scripts/usr/local/sbin/fdo-hotdesk-list-users
--- a/scripts/usr/local/sbin/fdo-hotdesk-list-users
+++ b/scripts/usr/local/sbin/fdo-hotdesk-list-users
@@ -35,6 +35,8 @@ HOST_CONF_PATH=${HOST_CONF_PATH:-"${FDO_CONFIG_ROOT}/host.conf"}
 HOTDESK_CONF_PATH=${HOTDESK_CONF_PATH:-"${FDO_CONFIG_ROOT}/hotdesk.conf"}
 SYSTEM_STATE_ROOT=${SYSTEM_STATE_ROOT:-"/var/db"}
 BACKUPZ_STATE_PATH=${STATE_PATH:-"${SYSTEM_STATE_ROOT}/fdo-backupz.state"}
+HOTDESK_UID_MIN=5001
+HOTDESK_UID_MAX=9999
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -116,6 +118,61 @@ test_if_host ()
 	fi
 }
 
+check_user_home_status ()
+{
+	HAS_NFS_EXPORTED="No"
+	HAS_BACKUP_FS="No"
+
+	# Determine if current user has an FDo hotdesk home filesystem.
+	zfs list -H -o name ${HOME_ZFS_NAME}/${USERNAME} > /dev/null 2>&1
+	if [ ${?} -eq 0 ]
+	then
+		# Determine if the current user has an FDo hotdesk home directory NFS export.
+		showmount -E | awk '{print $1}' | grep "^${HOME_MP}/${USERNAME}$" > /dev/null 2>&1
+		if [ ${?} -eq 0 ]
+		then
+			HAS_NFS_EXPORTED="Yes"
+		fi
+
+		# If the backupz state file exists, try to find the backup of hotdesk users' home directory.
+		HAS_BACKUP_FS="No"
+		if [ -e "${BACKUPZ_STATE_PATH}" ]
+		then
+
+			# Try to find the backup pool filesystem that holds the hotdesk users' home directory.
+			for POOL_NAME in `zpool list -H -o name | grep -v "${HOME_POOL}"`
+			do
+				TEST_BACKUP_POOL=`${UCL_CMD} get -f ${BACKUPZ_STATE_PATH} -u .pools.${POOL_NAME}`
+				if [ "${TEST_BACKUP_POOL}" != "" ]
+				then
+					# ASSUME: the hotdesk users' home directory can be in a backup pool in only one of two possible filesystem topologies:
+					#         (i)  ${BACKUP_POOL}/${HOME_POOL}/${HOME_FS}/${USERNAME}
+					#         (ii) ${BACKUP_POOL}/${HOME_POOL}__${HOME_FS}/${USERNAME}
+					TEST_HOME_POOL=`${UCL_CMD} get -f ${BACKUPZ_STATE_PATH} -u .pools.${POOL_NAME}.filesystems.${HOME_POOL}`
+					if [ "${TEST_HOME_POOL}" != "" ]
+					then
+						zfs list -H -o name "${POOL_NAME}/${HOME_POOL}/${HOME_FS}/${USERNAME}" > /dev/null 2>&1
+						if [ ${?} -eq 0 ]
+						then
+							HAS_BACKUP_FS="Yes"
+							break
+						fi
+					fi
+					TEST_HOME_FS=`${UCL_CMD} get -f ${BACKUPZ_STATE_PATH} -u .pools.${POOL_NAME}.filesystems.${HOME_POOL}/${HOME_FS}`
+					if [ "${TEST_HOME_FS}" != "" ]
+					then
+						zfs list -H -o name "${POOL_NAME}/${HOME_POOL}__${HOME_FS}/${USERNAME}" > /dev/null 2>&1
+						if [ ${?} -eq 0 ]
+						then
+							HAS_BACKUP_FS="Yes"
+							break
+						fi
+					fi
+				fi
+			done
+		fi
+	fi
+}
 
 ##### SANITY TESTS #############################################################
 
@@ -157,6 +214,24 @@ then
 	exit 2
 fi
 
+# Check that the hotdesk subsystem is initialised.
+HOTDESK_SUBSYS_COMPAT=`${UCL_CMD} get -f ${HOST_CONF_PATH} -q .subsystems.hotdesk_compat`
+if [ "${HOTDESK_SUBSYS_COMPAT}" = "null" ] || [ "${HOTDESK_SUBSYS_COMPAT}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} It appears that the Hotdesk subsystem is not initialised."
+	echo -e "       Consider using the command:"
+	echo -e "       ${LBLU}${SCRIPT_NAME} init-hotdesk${NRML}\n       Aborting.\n"
+	return 1
+fi
+
+# Check that the hotdesk.conf file is accessible.
+TEST_UCL=`${UCL_CMD} get -u -f ${HOTDESK_CONF_PATH} .general 2>&1`
+if [ ${?} -ne 0 ] || [ "${TEST_UCL}" = "null" ] || [ "${TEST_UCL}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Failed to access the config file '${HOTDESK_CONF_PATH}'!\n       Aborting.\n"
+	exit 2
+fi
+
 
 ##### MAIN EXECUTION THREAD ####################################################
 
@@ -190,72 +265,112 @@ then
 fi
 
 HOME_ZFS_NAME="${HOME_POOL}/${HOME_FS}"
+USERNAMES_MISSING_FROM_UCL=false
+USERNAMES_MISSING_FROM_SYSTEM=false
+USER_UID_MISMATCHES=false
 
 # Display hotdesk users table header.
 echo -e ""
 echo -e "${GREY}==============================================================================${NRML}"
-echo -e "${NRML}Username                      NFS export?   Backup Found?                     ${NRML}"
+echo -e "${NRML}Username                      UID   NFS export?   Backup Found?               ${NRML}"
 echo -e "${GREY}==============================================================================${NRML}"
 
-# Display hotdesk users table data, iterate through user in YP passwd map.
-for USERNAME in `ypcat passwd | cut -d: -f1`
+# Display hotdesk users table data, iterate through users in NIS passwd map.
+for USERNAME in `ypcat passwd | cut -d: -f1 | sort`
 do
-	# Determine if current user has an FDo hotdesk home filesystem.
-	zfs list -H -o name ${HOME_ZFS_NAME}/${USERNAME} > /dev/null 2>&1
-	if [ ${?} -eq 0 ]
+	# Set default output formatting colours.
+	USERNAME_COLOUR=${NRML}
+	USER_UID_COLOUR=${NRML}
+
+	# Get the users uid from YP passwd map.
+	USER_UID=`ypcat passwd | grep "^${USERNAME}:" | cut -d: -f3`
+
+	# Check if the username exists in the hotdesk.conf users list.
+	USER_INDEX=0
+	USERNAME_FOUND_IN_UCL=false
+	while [ `${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}` != "null" ]
+	do
+		TEST_USERNAME=`${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}.username`
+		if [ "${USERNAME}" = "${TEST_USERNAME}" ]
+		then
+			USERNAME_FOUND_IN_UCL=true
+			USERNAME_COLOUR=${LGRN}
+
+			# Check that the users uid matches that of the same user in hotdesk.conf.
+			TEST_USER_UID=`${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}.uid`
+			if [ "${USER_UID}" = "${TEST_USER_UID}" ]
+			then
+				USER_UID_COLOUR=${LGRN}
+			else
+				USER_UID_COLOUR=${ORNG}
+				USER_UID_MISMATCHES=true
+			fi
+		fi
+		USER_INDEX=$(( ${USER_INDEX} + 1 ))
+	done
+	if [ ${USERNAME_FOUND_IN_UCL} = false ]
 	then
-		# Determine if the current user has an FDo hotdesk home directory NFS export.
-		showmount -E | awk '{print $1}' | grep "^${HOME_MP}/${USERNAME}$" > /dev/null 2>&1
-		if [ ${?} -eq 0 ]
+		USERNAMES_MISSING_FROM_UCL=true
+		USERNAME_COLOUR=${ORNG}
+	fi
+
+	check_user_home_status
+
+	# Print the table row data for the current FDo hotdesk user found on the system NIS maps.
+	printf "${USERNAME_COLOUR}%-30s${USER_UID_COLOUR}%-6s${NRML}%-14s%-14s\n" ${USERNAME} ${USER_UID} ${HAS_NFS_EXPORTED} ${HAS_BACKUP_FS}
+	echo -e "${GREY}------------------------------------------------------------------------------${NRML}"
+done
+
+# Display remaining hotdesk users table data, iterate through hotdesk.conf looking for users missing from the system.
+USER_INDEX=0
+while [ `${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}` != "null" ]
+do
+	USERNAME=`${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}.username`
+	USER_UID=`${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}.uid`
+
+	USERNAME_FOUND_IN_SYSTEM=false
+	for TEST_USERNAME in `ypcat passwd | cut -d: -f1`
+	do
+		if [ "${USERNAME}" = "${TEST_USERNAME}" ]
 		then
-			HAS_NFS_EXPORTED="Yes"
-		else
-			HAS_NFS_EXPORTED="No"
+			USERNAME_FOUND_IN_SYSTEM=true
 		fi
+	done
 
-		# If the backupz state file exists, try to find the backup of hotdesk users' home directory.
-		HAS_BACKUP_FS="No"
-		if [ -e "${BACKUPZ_STATE_PATH}" ]
-		then
+	if [ ${USERNAME_FOUND_IN_SYSTEM} = false ]
+	then
+		USERNAMES_MISSING_FROM_SYSTEM=true
 
-			# Try to find the backup pool filesystem that holds the hotdesk users' home directory.
-			for POOL_NAME in `zpool list -H -o name | grep -v "${HOME_POOL}"`
-			do
-				TEST_BACKUP_POOL=`${UCL_CMD} get -f ${BACKUPZ_STATE_PATH} -u .pools.${POOL_NAME}`
-				if [ "${TEST_BACKUP_POOL}" != "" ]
-				then
-					# ASSUME: the hotdesk users' home directory can be in a backup pool in only one of two possible filesystem topologies:
-					#         (i)  ${BACKUP_POOL}/${HOME_POOL}/${HOME_FS}/${USERNAME}
-					#         (ii) ${BACKUP_POOL}/${HOME_POOL}__${HOME_FS}/${USERNAME}
-					TEST_HOME_POOL=`${UCL_CMD} get -f ${BACKUPZ_STATE_PATH} -u .pools.${POOL_NAME}.filesystems.${HOME_POOL}`
-					if [ "${TEST_HOME_POOL}" != "" ]
-					then
-						zfs list -H -o name "${POOL_NAME}/${HOME_POOL}/${HOME_FS}/${USERNAME}" > /dev/null 2>&1
-						if [ ${?} -eq 0 ]
-						then
-							HAS_BACKUP_FS="Yes"
-							break
-						fi
-					fi
-					TEST_HOME_FS=`${UCL_CMD} get -f ${BACKUPZ_STATE_PATH} -u .pools.${POOL_NAME}.filesystems.${HOME_POOL}/${HOME_FS}`
-					if [ "${TEST_HOME_FS}" != "" ]
-					then
-						zfs list -H -o name "${POOL_NAME}/${HOME_POOL}__${HOME_FS}/${USERNAME}" > /dev/null 2>&1
-						if [ ${?} -eq 0 ]
-						then
-							HAS_BACKUP_FS="Yes"
-							break
-						fi
-					fi
-				fi
-			done
-		fi
+		check_user_home_status
 
-		# Print the table row data for the current valid FDo hotdesk user.
-		printf "%-30s%-14s%-14s\n" ${USERNAME} ${HAS_NFS_EXPORTED} ${HAS_BACKUP_FS}
+		# Print the table row data for the current FDo hotdesk user in hotdesk.conf but missing from the system NIS maps.
+		printf "${LRED}%-30s%-6s${NRML}%-14s%-14s\n" ${USERNAME} ${USER_UID} ${HAS_NFS_EXPORTED} ${HAS_BACKUP_FS}
 		echo -e "${GREY}------------------------------------------------------------------------------${NRML}"
 	fi
+
+	USER_INDEX=$(( ${USER_INDEX} + 1 ))
 done
+
+if [ ${USERNAMES_MISSING_FROM_UCL} = true ]
+then
+	echo -e "\n${ORNG}WARNING:${NRML} At least one hotdesk user on the system is missing from the"
+	echo -e "         hotdesk subsystem config file: '${HOTDESK_CONF_PATH}'."
+	echo -e "         The username of these users is ${ORNG}highlighted${NRML} in the table above.\n"
+fi
+
+if [ ${USER_UID_MISMATCHES} = true ]
+then
+	echo -e "\n${ORNG}WARNING:${NRML} At least one hotdesk user on the system has a uid mismatch with the"
+	echo -e "         hotdesk subsystem config file: '${HOTDESK_CONF_PATH}'."
+	echo -e "         The uid of these users is ${ORNG}highlighted${NRML} in the table above.\n"
+fi
+
+if [ ${USERNAMES_MISSING_FROM_SYSTEM} = true ]
+then
+	echo -e "\n${ORNG}ERROR:${NRML} At least one hotdesk user is missing from the system NIS (yp) maps,"
+	echo -e "       according to the hotdesk subsystem config file: '${HOTDESK_CONF_PATH}'."
+	echo -e "       The username and uid of these users is ${LRED}highlighted${NRML} in the table above.\n"
+fi
 
 echo -e ""
 
diff --git a/scripts/usr/local/sbin/fdo-hotdesk-remove-user b/scripts/usr/local/sbin/fdo-hotdesk-remove-user
--- a/scripts/usr/local/sbin/fdo-hotdesk-remove-user
+++ b/scripts/usr/local/sbin/fdo-hotdesk-remove-user
@@ -40,6 +40,8 @@ NOW=`${DATE_CMD} +%Y-%m-%d_%H-%M`
 FORCE_MODE="no"
 IS_INTERACTIVE="yes"
 RENAME_BACKUP_FS=${RENAME_BACKUP_FS:-"yes"}
+HOTDESK_UID_MIN=5001
+HOTDESK_UID_MAX=9999
 
 TERM="xterm"
 LRED="\033[1;31m"
@@ -144,6 +146,37 @@ test_if_host ()
 	fi
 }
 
+ucl_array_length ()
+{
+	UCL_ARRAY_LENGTH_FILE_PATH="${1}"
+	UCL_ARRAY_LENGTH_VARIABLE="${2}"
+	UCL_ARRAY_LENGTH=0
+
+	UCL_ARRAY_LENGTH_OBJECT=`${UCL_CMD} get -f "${UCL_ARRAY_LENGTH_FILE_PATH}" "${UCL_ARRAY_LENGTH_VARIABLE}" 2> /dev/null`
+	if [ ${?} -ne 0 ]
+	then
+		# Unexpected error accessing the UCL file.
+		return 2
+	fi
+
+	if [ "${UCL_ARRAY_LENGTH_OBJECT}" != "[array]" ]
+	then
+		# The variable was not a valid array, return expected error.
+		return 1
+	fi
+
+	while [ "${UCL_ARRAY_LENGTH_OBJECT}" != "null" ]
+	do
+		UCL_ARRAY_LENGTH_OBJECT=`${UCL_CMD} get -f "${UCL_ARRAY_LENGTH_FILE_PATH}" "${UCL_ARRAY_LENGTH_VARIABLE}.${UCL_ARRAY_LENGTH}"`
+		if [ "${UCL_ARRAY_LENGTH_OBJECT}" != "null" ]
+		then
+			UCL_ARRAY_LENGTH=$(( ${UCL_ARRAY_LENGTH} + 1 ))
+		fi
+	done
+
+	return 0
+}
+
 backup_file ()
 {
 	FILE_PATH="${1}"
@@ -222,6 +255,7 @@ undo_remove_user ()
 
 	echo -e "\n${ORNG}Undoing user removal process...${NRML}\n"
 
+	# Restore local system and NIS users database.
 	restore_file /etc/exports ${SCRIPT_NAME}
 	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	restore_file /etc/passwd ${SCRIPT_NAME}
@@ -243,6 +277,10 @@ undo_remove_user ()
 	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 	cd -
 	service mountd reload
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+	# Restore hotdesk.conf UCL config file.
+	restore_file ${HOTDESK_CONF_PATH} ${SCRIPT_NAME}
 	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
 	if [ ${ERROR_COUNT} -ne 0 ]
@@ -294,10 +332,40 @@ then
 	exit 2
 fi
 
+# Check that the hotdesk subsystem is initialised.
+HOTDESK_SUBSYS_COMPAT=`${UCL_CMD} get -f ${HOST_CONF_PATH} -q .subsystems.hotdesk_compat`
+if [ "${HOTDESK_SUBSYS_COMPAT}" = "null" ] || [ "${HOTDESK_SUBSYS_COMPAT}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} It appears that the Hotdesk subsystem is not initialised."
+	echo -e "       Consider using the command:"
+	echo -e "       ${LBLU}${SCRIPT_NAME} init-hotdesk${NRML}\n       Aborting.\n"
+	return 1
+fi
+
+# Check that the hotdesk.conf file is accessible.
+TEST_UCL=`${UCL_CMD} get -u -f ${HOTDESK_CONF_PATH} .general 2>&1`
+if [ ${?} -ne 0 ] || [ "${TEST_UCL}" = "null" ] || [ "${TEST_UCL}" = "" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Failed to access the config file '${HOTDESK_CONF_PATH}'!\n       Aborting.\n"
+	exit 2
+fi
+
+# Check for unsaved registered host config files.
+echo -e "\n${YELL}Now we need to check if there are any unsaved changes to this hosts registered\nconfig files...${NRML}\n"
+${FDO_SERVER_SCRIPT} check-configs --script > /dev/null 2>&1
+if [ ${?} -gt 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} One or more host config files are not updated in the repo."
+	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} check-configs${NRML}' subcommand to see what's out-of-date."
+	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} update-config${NRML}' subcommannd to keep the repo up-to-date.\n       Aborting.\n"
+	exit 1
+fi
+
 # Check that we are not currently running a backupz operation.
-ps aux | grep "backupz"  | grep -v "grep backupz"
-if [ ${?} -eq 0 ]; then
-	echo -e "\n${LRED}ERROR:${NRML} A backupz operation is running, try again later!\n       Aborting.\n"
+pgrep -fl "fdo-backupz " > /dev/null 2>&1
+if [ ${?} -eq 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} There appears to be a backupz operation running!\n       Aborting.\n"
 	exit 1
 fi
 
@@ -335,8 +403,35 @@ then
 	fi
 fi
 
+# Check that user exists in hotdesk.conf.
+USER_INDEX=0
+USERNAME_FOUND_IN_UCL=false
+while [ `${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}` != "null" ]
+do
+	TEST_USERNAME=`${UCL_CMD} get -f ${HOTDESK_CONF_PATH} -q .users.${USER_INDEX}.username`
+	if [ "${USERNAME}" = "${TEST_USERNAME}" ]
+	then
+		USERNAME_FOUND_IN_UCL=true
+		HOTDESK_USERS_ARRAY_INDEX=${USER_INDEX}
+	fi
+	USER_INDEX=$(( ${USER_INDEX} + 1 ))
+done
+if [ ${USERNAME_FOUND_IN_UCL} = false ]
+then
+	if [ "${FORCE_MODE}" =  "yes" ]
+	then
+		echo -e "\n${ORNG}WARNING:${NRML} Can't find the user in the Hotdesk subsystem config file!\n"
+	else
+		echo -e "\n${LRED}ERROR:${NRML} Can't find the user in the Hotdesk subsystem config file:"
+		echo -e "       '${ORNG}${HOST_CONF_PATH}${NRML}'\n       Aborting.\n"
+		exit 1
+	fi
+fi
+
 
 ##### MAIN EXECUTION THREAD ####################################################
+
+trap 'undo_remove_user ; exit 3' HUP INT QUIT KILL TERM
 
 ERROR_COUNT=0
 
@@ -394,6 +489,13 @@ backup_file /etc/pwd.db ${SCRIPT_NAME}
 ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 backup_file /etc/spwd.db ${SCRIPT_NAME}
 ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+backup_file ${HOTDESK_CONF_PATH} ${SCRIPT_NAME}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+
+# Remove user from  hotdesk.conf.
+echo -e "\n${YELL}Removing the user from the Hotdesk subsystem config file...${NRML}\n"
+${UCL_CMD} remove -f ${HOTDESK_CONF_PATH} -o ${HOTDESK_CONF_PATH} .users.${HOTDESK_USERS_ARRAY_INDEX}
+ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 
 # Remove users' home directory from /etc/exports.
 echo -e "\n${YELL}Removing the user from the exports file...${NRML}\n"
@@ -419,6 +521,7 @@ make
 ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
 cd -
 
+# Remove user from the local system.
 echo -e "\n${YELL}Removing the user from system...${NRML}\n"
 rmuser -y ${USERNAME}
 ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
@@ -505,6 +608,7 @@ then
 
 	done
 
+	# If we found a backup of the home directory filesystem, handle it.
 	if [ "${BACKUP_FS}" = "" ]
 	then
 		echo -e "\n${YELL}INFO:${NRML} No backup filesystem found for the users' home directory."
@@ -536,12 +640,31 @@ then
 	fi
 fi
 
+# Update configuration in the local repo and if interactive mode then push to remote repo.
+echo -e "\n${YELL}Updating configuration to the repo...${NRML}\n"
+if [ "${IS_INTERACTIVE}" = "no" ]
+then
+	CHANGE_MESSAGE="remove hotdesk user '${USERNAME}'" GIT_NO_PUSH="yes" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config "${HOTDESK_CONF_PATH}"
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+else
+	CHANGE_MESSAGE="remove hotdesk user '${USERNAME}'" FETCH_LATEST_SELF="no" ${FDO_SERVER_SCRIPT} update-config "${HOTDESK_CONF_PATH}"
+	ERROR_COUNT=$(( ${ERROR_COUNT} + ${?} ))
+fi
+
+if [ ${ERROR_COUNT} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Something went wrong saving the configuration to the repo!\n"
+	exit 2
+fi
+
+# Since everything seems successful, we can remove the backup configs.
 undo_backup_file /etc/exports ${SCRIPT_NAME}
 undo_backup_file /var/yp/master.passwd ${SCRIPT_NAME}
 undo_backup_file /etc/passwd ${SCRIPT_NAME}
 undo_backup_file /etc/master.passwd ${SCRIPT_NAME}
 undo_backup_file /etc/pwd.db ${SCRIPT_NAME}
 undo_backup_file /etc/spwd.db ${SCRIPT_NAME}
+undo_backup_file ${HOTDESK_CONF_PATH} ${SCRIPT_NAME}
 
 echo -e "\n${LGRN}Successfully removed the hotdesk user '${NRML}${USERNAME}${LGRN}'.${NRML}\n"
 
