sshfs-daemon: completed initial development of subsystem.

diff --git a/scripts/usr/local/sbin/fdo-sshfs-add-connection b/scripts/usr/local/sbin/fdo-sshfs-add-connection
--- a/scripts/usr/local/sbin/fdo-sshfs-add-connection
+++ b/scripts/usr/local/sbin/fdo-sshfs-add-connection
@@ -264,12 +264,13 @@ then
 fi
 
 # Test that the remote user is valid
-TEST=`echo "${REMOTE_USER}" | sed "s/^[a-zA-Z0-9._-]\{3,\}$//" | wc -w`
+TEST=`echo "${REMOTE_USER}" | sed "s/^[a-zA-Z0-9._-]\{3,\}$//" | wc -L`
 if [ ${TEST} -ne 0 ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The remote user '${REMOTE_USER}' is invalid!"
 	echo -e "       It must only contain letters, numbers, hyphens, underscores and periods "
-	echo -e "       with a minumum of 3 characters.\n"
+	echo -e "       with a minumum of 3 characters."
+	echo -e "       Aborting.\n"
 	exit 5
 fi
 
@@ -286,42 +287,71 @@ then
 	exit 6
 fi
 
-# TODO: Test that the remote_path and local_path are valid. Considering that
-# UNIX paths can contain just about any character, this may not be practical.
-# Use exit codes 7 and 8.
+# Check if the remote_path does not end in a forward slash or a space
+TEST=`echo "${REMOTE_PATH}" | sed -r "s/.+.*[/ ]+$//" | wc -L`
+if [ ${TEST} -eq 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The remote path is invalid!"
+	echo -e "       It must not end with a forward slash or a space."
+	echo -e "       Aborting.\n"
+	exit 7
+fi
 
 
+# Check if the local_path already exists in sshfsd_shares.conf
+cat "${SSHFSD_CONF_PATH}" | grep -v "^#" | awk -F "///" '{print $2}' | grep "^${LOCAL_PATH}$" > /dev/null 2>&1
+if [ ${?} -eq 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} A connection already exists with the local path;"
+	echo -e "       '${LOCAL_PATH}'"
+	echo -e "       Aborting.\n"
+	exit 8
+fi
+
+# Check if the local_path is a valid directory
+if [ ! -d "${LOCAL_PATH}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} Cannot find the local path (mountpoint);"
+	echo -e "       '${LOCAL_PATH}'"
+	echo -e "       Aborting.\n"
+	exit 9
+fi
+
+# Check if the local_path is a valid absolute path
+LOCAL_PATH_CHAR1=`echo "${LOCAL_PATH}" | cut -c1`
+if [ "${LOCAL_PATH_CHAR1}" != "/" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The local path (mountpoint) is not a valid absolute path!"
+	echo -e "       It must begin with a forward slash ('/')."
+	echo -e "       Aborting.\n"
+	exit 10
+fi
+LOCAL_PATH_DIRNAME=`dirname "${LOCAL_PATH}"`
+LOCAL_PATH_BASENAME=`basename "${LOCAL_PATH}"`
+if [ "${LOCAL_PATH_DIRNAME}/${LOCAL_PATH_BASENAME}" != "${LOCAL_PATH}" ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} The local path (mountpoint) is not a valid absolute path!"
+	echo -e "       It must not use any redundant forward slashes ('/')."
+	echo -e "       Consider using the following path;"
+	echo -e "       '${LOCAL_PATH_DIRNAME}/${LOCAL_PATH_BASENAME}'"
+	echo -e "       Aborting.\n"
+	exit 11
+fi
+
+# Check if the port number is valid
 test_valid_integer "${REMOTE_PORT}" 1 65535
 if [ "${VALID_INTEGER}" = "no" ]
 then
 	echo -e "\n${LRED}ERROR:${NRML} The port number '${REMOTE_PORT}' is invalid!"
 	echo -e "       It must be a number between 1 and 65535."
 	echo -e "       Aborting.\n"
-	exit 9
+	exit 12
 fi
+
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
-
-# Check if the local_path already exists in sshfsd_shares.conf
-cat "${SSHFSD_CONF_PATH}" | grep -v "^#" | awk '{print $2}' | grep "^${LOCAL_PATH}$" > /dev/null 2>&1
-if [ ${?} -eq 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} A connection already exists with the local path;"
-	echo -e "       '${LOCAL_PATH}'"
-	echo -e "       Aborting.\n"
-	exit 10
-fi
-
-# Check if the local_path is a valid directory
-if [ ! -d "${LOCAL_PATH}" ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} Cannot find the local path;"
-	echo -e "       '${LOCAL_PATH}'"
-	echo -e "       Aborting.\n"
-	exit 11
-fi
 
 # Warn if the local_path is not empty
 TEST=`ls -A1 "${LOCAL_PATH}" | wc -l`
@@ -332,18 +362,20 @@ then
 	question_yes_no "Would you like to continue regardless of the mountpoint state?"
 	if [ "${ANSWER}" = "no" ]
 	then
-		exit 12
+		exit 13
 	fi
 fi
 
 # Ask if we should create an ssh key and copy it to the remote users' authorized keys
 # for an unattended login.
+SSHFSD_KEY="none"
 question_yes_no "\nUNATTENDED LOGIN: Would you like to use an SSH key to authenticate as the remote user?"
 if [ "${ANSWER}" = "yes" ]
 then
 	# Flatten the local_path so we can use it in a file name
 	LOCAL_PATH_FLAT=`echo ${LOCAL_PATH} | sed "s/\//_/g"`
-	SSHFSD_KEY="${SSHFSD_KEY_PREFIX}${LOCAL_PATH_FLAT}"
+	LOCAL_PATH_MD5=`echo "${LOCAL_PATH}" | md5 -q`
+	SSHFSD_KEY="${SSHFSD_KEY_PREFIX}_${LOCAL_PATH_MD5}${LOCAL_PATH_FLAT}"
 	echo -e ""
 	# Generate an SSH key and store it in a programatically accessible place
 	ssh-keygen -q -f "${SSHFSD_KEY}" -N ""
@@ -354,7 +386,7 @@ then
 		echo -e "       Aborting.\n"
 		rm ${SSHFSD_KEY}
 		rm ${SSHFSD_KEY}.pub
-		exit 13
+		exit 14
 	fi
 
 	echo -e "\n${YELL}SSH key generated!${NRML}"
@@ -369,23 +401,37 @@ then
 		echo -e "       Aborting.\n"
 		rm ${SSHFSD_KEY}
 		rm ${SSHFSD_KEY}.pub
-		exit 14
+		exit 15
 	fi
 
 fi
 
 # Now let's add the entry to the sshfs daemon config file
-echo "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH} ${LOCAL_PATH} ${REMOTE_PORT}" >> "${SSHFSD_CONF_PATH}"
+echo "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}///${LOCAL_PATH}///${REMOTE_PORT}" >> "${SSHFSD_CONF_PATH}"
 
 # Update configuration in the local repo and if interactive mode then push to remote repo
 if [ "${IS_INTERACTIVE}" = "no" ]
 then
+	if [ "${SSHFSD_KEY}" != "none" ]
+	then
+		echo -e "\n${FDO_SERVER_SCRIPT} add-config ${SSHFSD_KEY} ...\n"
+		GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} add-config "${SSHFSD_KEY}"
+		echo -e "\n${FDO_SERVER_SCRIPT} add-config ${SSHFSD_KEY}.pub ...\n"
+		GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} add-config "${SSHFSD_KEY}.pub"
+	fi
 	echo -e "\n${FDO_SERVER_SCRIPT} update-config ${SSHFSD_CONF_PATH} ...\n"
 	CHANGE_MESSAGE="add sshfs connection for local_path '${LOCAL_PATH}'" GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} update-config "${SSHFSD_CONF_PATH}"
 else
-	question_yes_no "\nWould you like to update the repo with the config changes?"
+	question_yes_no "\nWould you like to update the repo with the config changes? (RECOMMENDED)"
 	if [ "${ANSWER}" = "yes" ]
 	then
+		if [ "${SSHFSD_KEY}" != "none" ]
+		then
+			echo -e "\n${FDO_SERVER_SCRIPT} add-config ${SSHFSD_KEY} ...\n"
+			GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} add-config "${SSHFSD_KEY}"
+			echo -e "\n${FDO_SERVER_SCRIPT} add-config ${SSHFSD_KEY}.pub ...\n"
+			GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} add-config "${SSHFSD_KEY}.pub"
+		fi
 		echo -e "\n${FDO_SERVER_SCRIPT} update-config ${SSHFSD_CONF_PATH} ...\n"
 		CHANGE_MESSAGE="add sshfs connection for local_path '${LOCAL_PATH}'" ${FDO_SERVER_SCRIPT} update-config "${SSHFSD_CONF_PATH}"
 	fi
@@ -395,7 +441,7 @@ echo -e ""
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 15
+	exit 16
 fi
 
 ################################################################################
diff --git a/scripts/usr/local/sbin/fdo-sshfs-remove-connection b/scripts/usr/local/sbin/fdo-sshfs-remove-connection
--- a/scripts/usr/local/sbin/fdo-sshfs-remove-connection
+++ b/scripts/usr/local/sbin/fdo-sshfs-remove-connection
@@ -130,6 +130,20 @@ test_if_host ()
 	fi
 }
 
+is_mounted () {
+
+	IFS=${CARRIAGE_RETURN}
+	SSHFS_MOUNTPOINTS=`mount -p -t fusefs.sshfs | awk -F '\t'+ '{print $2}' | awk -F " fusefs.sshfs" '{print $1}'`
+	for MOUNTPOINT in ${SSHFS_MOUNTPOINTS}
+	do
+		if [ "${MOUNTPOINT}" = "${1}" ]
+		then
+			return 0
+		fi
+	done
+	return 1
+}
+
 
 ##### SANITY TESTS #############################################################
 
@@ -155,27 +169,23 @@ then
 	exit 4
 fi
 
-# TODO: Test that the local_path is valid. Considering that
-# UNIX paths can contain just about any character, this may not be practical.
-# Use exit code 5.
+# Check if the local_path exists in sshfsd_shares.conf
+cat "${SSHFSD_CONF_PATH}" | grep -v "^#" | awk -F "///" '{print $2}' | grep "^${LOCAL_PATH}$" > /dev/null 2>&1
+if [ ${?} -ne 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} No connection exists with the local path;"
+	echo -e "       '${LOCAL_PATH}'"
+	echo -e "       Aborting.\n"
+	exit 5
+fi
 
 
 ##### MAIN EXECUTION THREAD ####################################################
 
 ERROR_COUNT=0
 
-# Check if the local_path exists in sshfsd_shares.conf
-cat "${SSHFSD_CONF_PATH}" | grep -v "^#" | awk '{print $2}' | grep "^${LOCAL_PATH}$" > /dev/null 2>&1
-if [ ${?} -ne 0 ]
-then
-	echo -e "\n${LRED}ERROR:${NRML} No connection exists with the local path;"
-	echo -e "       '${LOCAL_PATH}'"
-	echo -e "       Aborting.\n"
-	exit 6
-fi
-
 # Warn if the local_path is mounted
-mount | grep "${LOCAL_PATH}" > /dev/null 2>&1
+is_mounted "${LOCAL_PATH}"
 if [ ${?} -eq 0 ]
 then
 	echo -e "\n${ORNG}WARNING:${NRML} The following local path appears to be mounted;"
@@ -183,7 +193,7 @@ then
 	question_yes_no "Would you like to continue regardless of the mount state?"
 	if [ "${ANSWER}" = "no" ]
 	then
-		exit 7
+		exit 6
 	else
 		# Unmount the connection
 		echo -e "\n${YELL}Unmounting the connection...${NRML}\n"
@@ -193,34 +203,52 @@ fi
 
 # Flatten the local_path so we can use it in a file name
 LOCAL_PATH_FLAT=`echo ${LOCAL_PATH} | sed "s/\//_/g"`
-SSHFSD_KEY="${SSHFSD_KEY_PREFIX}${LOCAL_PATH_FLAT}"
+LOCAL_PATH_MD5=`echo "${LOCAL_PATH}" | md5 -q`
+SSHFSD_KEY="${SSHFSD_KEY_PREFIX}_${LOCAL_PATH_MD5}${LOCAL_PATH_FLAT}"
+
+# Remove the connection from the sshfsd shares config file
+echo -e "\n${YELL}Removing sshfs connection...${NRML}\n"
+LOCAL_PATH_ESCAPED=`echo "${LOCAL_PATH}" | sed "s|\/|\\\\\/|g"`
+sed -i "" "/\/\/\/${LOCAL_PATH_ESCAPED}\/\/\//d" "${SSHFSD_CONF_PATH}"
 
 # Remove any ssh keys
 echo -e "\n${YELL}Removing any SSH keys...${NRML}\n"
 if [ -f "${SSHFSD_KEY}" ]
 then
 	rm "${SSHFSD_KEY}"
-	# TODO: add message explaining the need to manually remove ssh public key from remoter users autrhorized_keys file
 fi
 if [ -f "${SSHFSD_KEY}.pub" ]
 then
 	rm "${SSHFSD_KEY}.pub"
+	echo -e "\n${ORNG}You may need to manually remove any public ssh keys from the remote users' ${NRML}"
+	echo -e "${ORNG}authorized_keys file on the remote system.${NRML}\n"
+else
+	SSHFSD_KEY="none"
 fi
-
-# Remove the connection from the sshfsd shares config file
-sed -i "" "/ ${LOCAL_PATH} /d" "${SSHFSD_CONF_PATH}"
-
-# TODO: test for failure of above
 
 # Update configuration in the local repo and if interactive mode then push to remote repo
 if [ "${IS_INTERACTIVE}" = "no" ]
 then
+	if [ "${SSHFSD_KEY}" != "none" ]
+	then
+		echo -e "\n${FDO_SERVER_SCRIPT} remove-config ${SSHFSD_KEY} ...\n"
+		GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} remove-config "${SSHFSD_KEY}"
+		echo -e "\n${FDO_SERVER_SCRIPT} remove-config ${SSHFSD_KEY}.pub ...\n"
+		GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} remove-config "${SSHFSD_KEY}.pub"
+	fi
 	echo -e "\n${FDO_SERVER_SCRIPT} update-config ${SSHFSD_CONF_PATH} ...\n"
 	CHANGE_MESSAGE="remove sshfs connection for local_path '${LOCAL_PATH}'" GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} update-config "${SSHFSD_CONF_PATH}"
 else
-	question_yes_no "\nWould you like to update the repo with the config changes?"
+	question_yes_no "\nWould you like to update the repo with the config changes? (RECOMMENDED)"
 	if [ "${ANSWER}" = "yes" ]
 	then
+		if [ "${SSHFSD_KEY}" != "none" ]
+		then
+			echo -e "\n${FDO_SERVER_SCRIPT} remove-config ${SSHFSD_KEY} ...\n"
+			GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} remove-config "${SSHFSD_KEY}"
+			echo -e "\n${FDO_SERVER_SCRIPT} remove-config ${SSHFSD_KEY}.pub ...\n"
+			GIT_NO_PUSH="yes" ${FDO_SERVER_SCRIPT} remove-config "${SSHFSD_KEY}.pub"
+		fi
 		echo -e "\n${FDO_SERVER_SCRIPT} update-config ${SSHFSD_CONF_PATH} ...\n"
 		CHANGE_MESSAGE="remove sshfs connection for local_path '${LOCAL_PATH}'" ${FDO_SERVER_SCRIPT} update-config "${SSHFSD_CONF_PATH}"
 	fi
@@ -230,7 +258,7 @@ echo -e ""
 
 if [ ${ERROR_COUNT} -gt 0 ]
 then
-	exit 15
+	exit 7
 fi
 
 ################################################################################
