scripts: add 'fdo-server check-configs' to sanity checks of remaining scripts that alter the repo.

diff --git a/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule b/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
--- a/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
+++ b/scripts/usr/local/sbin/fdo-ppp-add-port-forward-rule
@@ -396,6 +396,17 @@ then
 	exit 1
 fi
 
+# Check for unsaved registered host config files.
+echo -e "\n${YELL}Now we need to check if there are any unsaved changes to this hosts registered\nconfig files...${NRML}\n"
+${FDO_SERVER_SCRIPT} check-configs --script > /dev/null 2>&1
+if [ ${?} -gt 0 ]
+then
+	echo -e "\n${LRED}ERROR:${NRML} One or more host config files are not updated in the repo."
+	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} check-configs${NRML}' subcommand to see what's out-of-date."
+	echo -e "       Please use '${LBLU}${FDO_SERVER_SCRIPT} update-config${NRML}' subcommannd to keep the repo up-to-date.\n       Aborting.\n"
+	exit 1
+fi
+
 # Test if rule_name is valid.
 test_valid_rule_name "${RULE_NAME}"
 if [ "${VALID_RULE_NAME}" = "no" ]
